### PR TITLE
SPOSiteDesign: Add site design webtemplate groupless team site

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description
Add support for WebTemplate = 1 (GrouplessTeamSite) in site designs resource

#### This Pull Request (PR) fixes the following issues
None

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1105)

### CODE REVIEW

**Comment by ykuijs** [comment]
@jensotto One request before we can merge the PR: Could you please add an entry to the changelog for this fix?

**Comment by jensotto** [comment]
Changelog updated

**Comment by ykuijs** [comment]
@jensotto, please target this PR to the dev branch instead of the master branch

**Comment by jensotto** [comment]
It might get to late but I don't seem to get this right. There are many commits that I can't get rid of. Do you have any insights @ykuijs ?

**Comment by ykuijs** [comment]
@jensotto, I think quickest is to create a new branch in your fork based on the Dev branch and implement that change in that branch. The change is quite small, so doesn't require too much work to reimplement.

**Comment by jensotto** [comment]
@ykuijs done with PR #1120

**Pull request closed without merging**
