### PR TITLE
IntuneDeviceEnrollmentPlatformRestriction: Remove Windows Mobile support

### LINKED ISSUE #3303: IntuneDeviceEnrollmentPlatformRestriction: Deprecated Windows Mobile support results in error when applying config
#### Details of the scenario you tried and the problem that is occurring

Exporting the default IntuneDeviceEnrollmentPlatformRestriction policy assigned to all users results in having Windows Mobile restrictions in the exported blueprint even though they are not visible in MEM portal, but when trying to apply that blueprint it will result in the issue reported below that Windows Phone/Mobile is not supported any longer.

#### Verbose logs showing the problem

[...] cut for brevity

```powershell
{
  "_version": 3,
  "Message": "Windows Phone operations are no longer supported. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID:
80f9cf6b-e2d9-4d2b-b9bc-bf887ebe7498 - Url: https://fef.msub07.manage.microsoft.com/StatelessOnboardingService/deviceManagement/deviceEnrollmentConfigurations('5a5666cb-081a-4b70-
a3ed-6892e85c2528_DefaultPlatformRestrictions')?api-version=5023-01-11",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
    + CategoryInfo          : InvalidOperation: ({ DeviceEnrollm...Configuration }:) [], CimException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementDeviceEnrollmentConfiguration_Update1
    + PSComputerName        : localhost

VERBOSE: [DC]: LCM:  [ End    Set      ]  [[IntuneDeviceEnrollmentPlatformRestriction]IntuneDeviceEnrollmentPlatformRestriction-All users and all devices]  in 4.3920 seconds.
The PowerShell DSC resource '[IntuneDeviceEnrollmentPlatformRestriction]IntuneDeviceEnrollmentPlatformRestriction-All users and all devices' with SourceInfo
'C:\agent\_work\r2\a\_BuildDeploy\DeployPackage\Tenants\v55qj.onmicrosoft.com\M365Configuration.ps1::20::9::IntuneDeviceEnrollmentPlatformRestriction' threw one or more
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this
channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

VERBOSE: [DC]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 16.004 seconds
```

#### Suggested solution to the issue

Remove Windows Mobile support

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated with Microsoft365DSC version 1.23.510.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration test
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.510.1'

    Node localhost
    {
        IntuneDeviceEnrollmentPlatformRestriction "IntuneDeviceEnrollmentPlatformRestriction-All users and all devices"
        {
            AndroidForWorkRestriction         = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $False
                personalDeviceEnrollmentBlocked = $False
            };
            AndroidRestriction                = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $False
                personalDeviceEnrollmentBlocked = $False
            };
            ApplicationId                     = $ConfigurationData.NonNodeData.ApplicationId;
            Assignments                       = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.allDevicesAssignmentTarget'
                });
            CertificateThumbprint             = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Description                       = "This is the default Device Type Restriction applied with the lowest priority to all users regardless of group membership.";
            DeviceEnrollmentConfigurationType = "platformRestrictions";
            DisplayName                       = "All users and all devices";
            Ensure                            = "Present";
            Identity                          = "20e486c4-c6e2-4594-a875-73953e64c4dd_DefaultPlatformRestrictions";
            IosRestriction                    = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $False
                personalDeviceEnrollmentBlocked = $False
            };
            MacOSRestriction                  = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $False
                personalDeviceEnrollmentBlocked = $False
            };
            MacRestriction                    = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $False
                personalDeviceEnrollmentBlocked = $False
            };
            TenantId                          = $OrganizationName;
            WindowsHomeSkuRestriction         = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $False
                personalDeviceEnrollmentBlocked = $False
            };
            WindowsMobileRestriction          = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $True
                personalDeviceEnrollmentBlocked = $False
            };
            WindowsRestriction                = MSFT_DeviceEnrollmentPlatformRestriction{
                platformBlocked = $False
                personalDeviceEnrollmentBlocked = $False
            };
        }
    }
}

test -ConfigurationData .\ConfigurationData.psd1

```

#### The operating system the target node is running

Win10

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.23.510.1

### PR DESCRIPTION
**Pull request by ricmestre**
#### Pull Request (PR) description

Windows Mobile support is already deprecated and when applying blueprints with it then it will fail to apply the configuration, this PR fixes this by removing support for it.

#### This Pull Request (PR) fixes the following issues

 - Fixes #3303

### CODE REVIEW

**Comment by ricmestre** [comment]
Well, it seems that my code was acting up and changing the subproperty PlatformBlocked automatically to $False which makes the Graph error appear. So how about when on method Set check if WindowsMobileRestriction is present and then check if PlatformBlocked is $False changing it back to $True and warning the user?

This is far more easier and less intrusive change.

**Comment by NikCharlebois** [comment]
I agree that this would be less intrusive, and then wouldn't be a breaking change.

**Comment by ricmestre** [comment]
Just tested latest change and works as advertised, when trying to change WinMobile platformBlocked to $false it changes back to $true automatically and this is displayed in the console.

```powershell
VERBOSE: [REDACTED]:                            [[IntuneDeviceEnrollmentPlatformRestriction]IntuneDeviceEnrollmentPlatformRestriction-All users and all
devices] Windows Mobile platform is deprecated and cannot be unblocked, reverting back to blocked
```

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
If the property is deprecated, we should also make sure the Get-TargetResource function stops returning it.

**Comment by ricmestre** [comment]
Remove it only from Get? What about Export? Shouldn't it be removed from there also?

**Comment by ricmestre** [comment]
@andikrueger I'm not asking about the parameters, that was what I did in first revision I just removed them. What I'm asking now is about the conditions from line 697 to 708 and then again from 796 to 799.

**Comment by andikrueger** [comment]
I would remove both, if there is no further set-function for theses values. On the other hand: As long as there is valuable information in the export of the property, we should stick to it.

**Comment by ricmestre** [comment]
On that note I kept those conditions for the Export and removed it from Get

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
