### PR TITLE
FIXES #3046

### LINKED ISSUE #3046: Export-M365DSCConfiguration: "Organization cannot be a Guid, please enter the name of the tenant instead." when exporting SC config
#### Details of the scenario you tried and the problem that is occurring
Use https://export.microsoft365dsc.com/ to generate the command to export from Security and Compliance Centre and Exchange
Select Cetrificate as the authentication method.
Run the command with an appropriate TenantId, AppId and Cert thumbprint.
#### Verbose logs showing the problem
VERBOSE: Dependencies were already successfully validated.
VERBOSE: ApplicationId, TenantId, CertificateThumbprint were specified. Connecting via Service Principal
Connecting to {ExchangeOnline}...VERBOSE: Returning precomputed version info: 3.1.0
VERBOSE: POST https://outlook.office365.com/adminapi/beta/bd13c3bf-aa4a-4fb4-a11c-fcf976c42a1d/InvokeCommand with -1-byte payload
VERBOSE: received 1306-byte response of content type application/json;charset=utf-8
✅
Connecting to {SecurityComplianceCenter}...VERBOSE: Returning precomputed version info: 3.1.0
VERBOSE: ModuleVersion: 3.1.0
VERBOSE: ConnectionContext Removed
❌
Organization cannot be a Guid, please enter the name of the tenant instead.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Getting application information for Application + Certificate authentication
$ApplicationId = "<GUID>"
$CertificateThumbprint = "<thumbprint>"
$TenantId = "<GUID>"

# Exporting resources using certificate
Export-M365DSCConfiguration -Components @("EXOAntiPhishPolicy", 
    "EXOAntiPhishRule", 
    "EXOAtpPolicyForO365", 
    "EXOHostedContentFilterPolicy", 
    "EXOHostedContentFilterRule", 
    "EXOHostedOutboundSpamFilterPolicy", 
    "EXOHostedOutboundSpamFilterRule", 
    "EXOMalwareFilterPolicy", 
    "EXOMalwareFilterRule", 
    "EXOSafeAttachmentPolicy", 
    "EXOSafeAttachmentRule", 
    "EXOSafeLinksPolicy", 
    "EXOSafeLinksRule", 
    "EXOTransportRule", 
    "SCAutoSensitivityLabelPolicy", 
    "SCAutoSensitivityLabelRule", 
    "SCDLPCompliancePolicy", 
    "SCDLPComplianceRule",
    "SCLabelPolicy", 
    "SCSensitivityLabel") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.23.315.1

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
* Enforcing tenant ID to be in the tenant.onmicrosoft.com form.

#### This Pull Request (PR) fixes the following issues
* FIXES #3046

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@andikrueger @ykuijs Thoughts on this implementation?

**Comment by andikrueger** [comment]
Shall we add a test for the correct format of the tenant name as well? 

Something like 

$_ -notmatch “.onmicrosoft.com$”

**Comment by ykuijs** [comment]
Agree with Andi, if the goal is to enforce the tenantname.onmicrosoft.com format, why not check for it.

**Comment by ykuijs** [comment]
Another thought: Shouldn't we check this with all resources? Everywhere the TenantId parameter is used, should be in this format. Not just the export. So maybe we should check this in the New-M365DSCConnection cmdlet as well.

**Comment by andikrueger** [comment]
@ykuijs this is a good idea. We should add this check to the New-M365DSCconnection too.

**Comment by NikCharlebois** [comment]
Ok, logic has been updated to also handle case where tenant id isn't a GUID, but also isn't in the *.onmicrosoft.* format. I've also added validation logic to the NEw-M365DSCConnection cmdlet. Please provide a Code Review. Thanks

**Comment by andikrueger** [comment]
We should add the new requirement for the username to be in the form of tenant.onmicrosoft.com to the blog post. This will for sure break several scheduled tasks.

**Comment by desmay** [comment]
what about gov customers onmicrosoft.us ?

**Comment by NikCharlebois** [comment]
> what about gov customers onmicrosoft.us ? Just looked at commits looks fine

I am checking for *.onmicrosoft.* instead of *.onmicrosoft.com. @desmay any concerns with this approach for sovereign customers?

**Comment by NikCharlebois** [comment]
> We should add the new requirement for the username to be in the form of tenant.onmicrosoft.com to the blog post. This will for sure break several scheduled tasks.

But is it working then if they use something other than *.onmicrosoft.*? I was under the impression that this wasn't even working to begin with?

**Comment by NikCharlebois** [comment]
Then we probably shouldn't force the .onmicrosoft. format if using domain accounts work. Let's hold off on this PR

**Comment by NikCharlebois** [comment]
Great Idea. 

If GUID, throw error, if not .onmicrosoft. print warning

**Pull request merged**
