### PR TITLE
Aad servce principal

### PR DESCRIPTION
**Pull request by ThorstenLoeschmann**
#### This Pull Request (PR) fixes the following issues

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780)

### CODE REVIEW

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Few minor coments

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-:-MHHbwda7RLrDYZNbk8K:b-lbtdhr)* status: all files reviewed, 6 unresolved discussions (waiting on @ThorstenLoeschmann)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 261 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHb8HdAhT1elIMW9qp:-MHHb8HdAhT1elIMW9qq:bj1kw2y) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L261)):*
> ```PowerShell
> 
>     # ServicePrincipal should exist but it doesn't
>     if ($Ensure -eq "Present" -and $currentAADServicePrincipal.Ensure -eq "Absent")
> ```

Can you just add a Write-Verbose at the top of each of the 3 scenarios below to indicate where in the logic branch we are? Something like "Creating new Service Principal", "Updating existing Service Principal", "Removing Service Principal". Makes it easier to troubleshoot down the road.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 263 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHarjv782Gu47LlgRy:-MHHarjv782Gu47LlgRz:b-twup5z) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L263)):*
> ```PowerShell
>     if ($Ensure -eq "Present" -and $currentAADServicePrincipal.Ensure -eq "Absent")
>     {
>         New-AzureADServicePrincipal @currentParameters
> ```

The New-AzureADServicePrincipal cmdlet doesn't seem to accept the ObjectID as a param. We should remove it from the $currentParameters
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 268 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHb1na7lNjtHArBsNC:-MHHb1na7lNjtHArBsND:b-76w5kh) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L268)):*
> ```PowerShell
>     if ($Ensure -eq 'Present' -and $currentAADServicePrincipal.Ensure -eq 'Present')
>     {
>         Set-AzureADServicePrincipal -ObjectID $currentAADServicePrincipal.ObjectID @currentParameters
> ```

There may be a duplicate of the ObjectId param if we don't remove it above
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 372 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHbUTp6kNOd9z--jzS:-MHHbUTp6kNOd9z--jzT:b4zw8f0) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L372)):*
> ```PowerShell
> 
>     $ValuesToCheck = $PSBoundParameters
>     $ValuesToCheck.Remove('GlobalAdminAccount') | Out-Null
> ```

We should also remove ApplicationID, CertificateThumbprint and TenantId
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/readme.md, line 12 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHbjAQ2RQNaI2p35NA:-MHHbjARA54YwtpKhKNL:b-3xppw5) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/readme.md#L12)):*
> ```Markdown
> 
> * **Automate**
>   * None
> ```

Have we confirmed that no permissions are required here when using an AzureAD Application?
___
*[Modules/Microsoft365DSC/Examples/Resources/AADServicePrincipal/1-ConfigureAADServicePrincipal.ps1, line 19 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHbqHN5rxAgP634Hkk:-MHHbqHN5rxAgP634Hkl:bb7kry6) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/Examples/Resources/AADServicePrincipal/1-ConfigureAADServicePrincipal.ps1#L19)):*
> ```PowerShell
>         AADServicePrincipal AADServicePrincipal1
>         {
>             
> ```

Remove empty line

**Review by NikCharlebois — COMMENTED** [review]
Forgot to mention, please update the ChangeLog with an entry for:

* AADServicePrincipal
  * Initial Release (Issue #492)

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-:-MHIw9V-1jWcyRhKJZ2x:b-amxc2l)* status: all files reviewed, 6 unresolved discussions (waiting on @ThorstenLoeschmann)

**Review by ThorstenLoeschmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780)* status: all files reviewed, 6 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 261 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHb8HdAhT1elIMW9qp:-MHHqRJ52BTe5hrCO73D:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L261)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Can you just add a Write-Verbose at the top of each of the 3 scenarios below to indicate where in the logic branch we are? Something like "Creating new Service Principal", "Updating existing Service Principal", "Removing Service Principal". Makes it easier to troubleshoot down the road.
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 263 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHarjv782Gu47LlgRy:-MHHpuVIBihLhUJbHfpO:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L263)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

The New-AzureADServicePrincipal cmdlet doesn't seem to accept the ObjectID as a param. We should remove it from the $currentParameters
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 268 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHb1na7lNjtHArBsNC:-MHHpuBp9NtGHaub87ZW:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L268)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

There may be a duplicate of the ObjectId param if we don't remove it above
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 372 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHbUTp6kNOd9z--jzS:-MHHqApm2aI6WRVR9PQj:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L372)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

We should also remove ApplicationID, CertificateThumbprint and TenantId
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/readme.md, line 12 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHbjAQ2RQNaI2p35NA:-MHM6Rva5YdtkbnBkIOx:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/readme.md#L12)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Have we confirmed that no permissions are required here when using an AzureAD Application?
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/Examples/Resources/AADServicePrincipal/1-ConfigureAADServicePrincipal.ps1, line 19 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHHbqHN5rxAgP634Hkk:-MHHrpcDAbEynnYvKwwU:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/fbf3ce7ebb9c0bc559818aaf166f0a9f8634aad7/Modules/Microsoft365DSC/Examples/Resources/AADServicePrincipal/1-ConfigureAADServicePrincipal.ps1#L19)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Remove empty line
</blockquote></details>

Done.

**Review by ThorstenLoeschmann — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-:-MHM6XTAE9ZS8l3AFlN6:bb6un1j)* status: all files reviewed, 6 unresolved discussions (waiting on @NikCharlebois)

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Forgot to remove empty line, and found additional typo

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-:-MHMFR2p1mkoHS7QebaA:b-smwius)* status: all files reviewed, 2 unresolved discussions (waiting on @NikCharlebois and @ThorstenLoeschmann)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 259 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHMFADx3BED-FMKnwys:-MHMFADx3BED-FMKnwyt:b-nddlfh) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b7d9626011217f5c8b75c7d937e837179799ac26/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L259)):*
> ```PowerShell
>     $currentParameters.Remove("GlobalAdminAccount") | Out-Null
>     $currentParameters.Remove("Ensure") | Out-Null
>     $currentParameters.Remove("OjectID") | Out-Null
> ```

Typo in Object

**Review by ThorstenLoeschmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1, line 259 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-MHMFADx3BED-FMKnwys:-MHMH2GpD-1LM0b0JwZi:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b7d9626011217f5c8b75c7d937e837179799ac26/Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1#L259)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Typo in Object
</blockquote></details>

Done.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780#-:-MHMIkiP84QMLv1U6t2H:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Review by NikCharlebois — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/780)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
