### PR TITLE
Feat/windows 10 baseline

### PR DESCRIPTION
**Pull request by nee-source**
#### Pull Request (PR) description
Add Intune Security Baseline for Windows 10

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x ] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ x] Resource parameter descriptions added/updated in the schema.mof.
- [ x] Resource documentation added/updated in README.md.
- [ x] Resource settings.json file contains all required permissions.
- [ x] Examples appropriately added/updated.
- [x ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

### CODE REVIEW

**Comment by FabienTschanz** [comment]
@ykuijs @NikCharlebois I'll be reviewing this PR. There probably will be some additional changes necessary.

**Comment by FabienTschanz** [comment]
Working on it, not yet ready.

**Comment by FabienTschanz** [comment]
We will work on this PR in the coming days. No ETA, but we're confident in finalizing it for next week's release.

**Comment by FabienTschanz** [comment]
@NikCharlebois Ready for review.

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
