### PR TITLE
MSFT_AADConditionalAccessPolicy [BUG] Prevent null objects, allow IncludePlatforms without Exclusions

### PR DESCRIPTION
**Pull request by AlfredSchreuder**
#### Pull Request (PR) description
The PR solves adding null objects to the $NewParameter when not applicable for $sessioncontrols and $sessioncontrols.applicationEnforcedRestrictions, which causes errors on deployment. Next to that it provides the possibility to include platforms without excluding but expects included platforms when excluding.

#### This Pull Request (PR) fixes the following issues
None

### CODE REVIEW

**Comment by AlfredSchreuder** [comment]
@microsoft-github-policy-service agree [company="Fellowmind"]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="Microsoft"

**Comment by AlfredSchreuder** [comment]
@microsoft-github-policy-service agree company="Fellowmind"

**Comment by ykuijs** [comment]
Hi @AlfredSchreuder, thanks for fixing this issue and submitting this PR.

One question though: Could you please also add an entry to the changelog, so we keep track of all changes in a version? Just like is done [here](https://github.com/microsoft/Microsoft365DSC/blob/9f315062f4711ce043e995066dc80c9ab9efc0c7/CHANGELOG.md?plain=1#L11-L13).

**Review by ykuijs — APPROVED** [review]
LGTM

**Pull request merged**
