### PR TITLE
IntuneASRRulesPolicyWindows10: Fix possible values for properties EmailContentExecutionType and UntrustedExecutableType

### LINKED ISSUE #3434: IntuneASRRulesPolicyWindows10: Incorrect set of possible values for properties EmailContentExecutionType and UntrustedExecutableType
#### Details of the scenario you tried and the problem that is occurring

One of my Attack Surface Reduction policies has the property EmailContentExecutionType set to *warn* which gets exported into a blueprint without issues, but when trying to compile it into a MOF it fails due to incorrect possible values in both its schema and the module, even though the current possible values don't even match between them.

image

#### Verbose logs showing the problem

##[error]The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: At least one of the values 'warn' is not supported or valid for property 'EmailContentExecutionType' on class 'IntuneASRRulesPolicyWindows10'. Please specify only supported values: 
notConfigured, block, auditMode, userDefined, disable.

##[error]PowerShell exited with code '1'.

#### Suggested solution to the issue

Change possible values of property EmailContentExecutionType in both schema and module, and make sure they both match, which are 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
   IntuneASRRulesPolicyWindows10 "IntuneASRRulesPolicyWindows10-REDACTED"
        {
            AdobeReaderLaunchChildProcess                   = "notConfigured";
            AdvancedRansomewareProtectionType               = "notConfigured";
            ApplicationId                                   = $ConfigurationData.NonNodeData.ApplicationId;
            Assignments                                     = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = 'REDACTED'
            }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = 'REDACTED'
            });
            BlockPersistenceThroughWmiType                  = "auditMode";
            CertificateThumbprint                           = $ConfigurationData.NonNodeData.CertificateThumbprint;
            DisplayName                                     = "REDACTED";
            EmailContentExecutionType                       = "warn";
            Ensure                                          = "Present";
            GuardMyFoldersType                              = "auditMode";
            Identity                                        = "REDACTED";
            OfficeAppsExecutableContentCreationOrLaunchType = "auditMode";
            OfficeAppsLaunchChildProcessType                = "auditMode";
            OfficeAppsOtherProcessInjectionType             = "auditMode";
            OfficeCommunicationAppsLaunchChildProcess       = "auditMode";
            OfficeMacroCodeAllowWin32ImportsType            = "auditMode";
            PreventCredentialStealingType                   = "notConfigured";
            ProcessCreationType                             = "userDefined";
            ScriptDownloadedPayloadExecutionType            = "auditMode";
            ScriptObfuscatedMacroCodeType                   = "auditMode";
            TenantId                                        = $OrganizationName;
            UntrustedExecutableType                         = "warn";
            UntrustedUSBProcessType                         = "userDefined";
        }
```

#### The operating system the target node is running

Win10

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.23.628.1

### PR DESCRIPTION
**Pull request by ricmestre**
#### Pull Request (PR) description

Fix possible values for properties EmailContentExecutionType and UntrustedExecutableType

#### This Pull Request (PR) fixes the following issues

- Fixes #3434

### CODE REVIEW

**Comment by andikrueger** [comment]
Could you have a look at this file:

image

Usually, GitHub displays the files contents.

**Comment by ricmestre** [comment]
@andikrueger How? I actually was never able to see the diffs of MOFs in GH, I don't have any issues locally though.

**Comment by NikCharlebois** [comment]
This is a breaking change. We either need to wait for the first release of October to release, or we update to accept all values (old and new) and print a warning when old/invalid values are used until we have our major change in October.

**Comment by ricmestre** [comment]
@nikcharlebois Most of these properties are incorrect, I'm still not finished up the whole list, so clearly people are not testing this resource by deploying it or at least compiling it.

Best I can do is revert all these changes back and to just set all of these properties with possible value list of "notConfigured", "userDefined", "enable", "disable", "auditMode", "warn" which are basically all values. Adding more churn to print the incorrect value here seems to much for me due to the above paragraph.

**Comment by andikrueger** [comment]
> > Could you have a look at this file:
> > image
> > Usually, GitHub displays the files contents.
> 
> MOF files are binary and would not be shown by GitHub.

That is very interesting. The mofs are visible in other PRs...

image

**Comment by ricmestre** [comment]
For reference this is the list I created with the possible values per each option/variable. Note that the Unit Tests are failing since I didn't change the properties' values in those.

Block persistence through WMI event subscription: $BlockPersistenceThroughWmiType :
- 'notConfigured', 'block', 'auditMode' , 'disable'

Block credential stealing from the Windows local security authority subsystem (lsass.exe): $PreventCredentialStealingType :
- 'notConfigured', 'userDefined', 'enable', 'auditMode', 'warn'

Block Adobe Reader from creating child processes: $AdobeReaderLaunchChildProcess :
- 'notConfigured', 'userDefined', 'enable', 'auditMode', 'warn'

Block Office applications from injecting code into other processes: $OfficeAppsOtherProcessInjectionType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block Office applications from creating executable content: $OfficeAppsLaunchChildProcessType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block all Office applications from creating child processes: $OfficeAppsExecutableContentCreationOrLaunchType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block Win32 API calls from Office macro: $OfficeMacroCodeAllowWin32ImportsType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block Office communication apps from creating child processes: $OfficeCommunicationAppsLaunchChildProcess :
- 'notConfigured', 'userDefined', 'enable', 'auditMode', 'warn'

Block execution of potentially obfuscated scripts (js/vbs/ps): $ScriptObfuscatedMacroCodeType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block JavaScript or VBScript from launching downloaded executable content: $ScriptDownloadedPayloadExecutionType :
- 'notConfigured', 'block', 'auditMode', 'disable'

Block process creations originating from PSExec and WMI commands: $ProcessCreationType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block untrusted and unsigned processes that run from USB: $UntrustedUSBProcessType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block executable files from running unless they meet a prevalence, age, or trusted list criteria: $UntrustedExecutableType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Block executable content download from email and webmail clients: $EmailContentExecutionType :
- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

Use advanced protection against ransomware: $AdvancedRansomewareProtectionType :
- 'notConfigured', 'userDefined', 'enable', 'auditMode'

Enable folder protection: $GuardMyFoldersType :
- 'notConfigured', 'enable', 'auditMode', 'blockDiskModification', 'auditDiskModification'

**Comment by ricmestre** [comment]
Just to be clear, this resource has been created for quite some time now (last year?) and no one noticed before that almost all parameters had an incorrect set of possible values (not sure if they changed since resource creation, but very unlikely) which means that it's not being used except for maybe exports, which as I initially mentioned is working fine.

So with that being said is it really useful to print a warning if an incorrect value is being used? This basically means that someone that exported a tenant's config, correctly, and then manually sets one of the properties to an incorrect value the warning is printed but then the cmdlets will fail anyway and the resource is not deployed, even if the ValidateSets are updated. Unless of course the code is also updated to acomodate this and automatically set the incorrect values always to "notConfigured" but from my point of view this would be too intrusive and not useful since it seems the resource is not being used for deployments otherwise people would have complained by now.

Any better ideas? I can update the PR to changed the ValidateSets of all affected properties, see below the incorrect values they have now, to allow all possible values (old and new).

```powershell
$IncorrectParameters = @{
    BlockPersistenceThroughWmiType                  = @("userDefined", "warn")
    OfficeAppsOtherProcessInjectionType             = "userDefined"
    OfficeAppsLaunchChildProcessType                = "userDefined"
    OfficeAppsExecutableContentCreationOrLaunchType = "userDefined"
    OfficeMacroCodeAllowWin32ImportsType            = "userDefined"
    OfficeCommunicationAppsLaunchChildProcess       = @("userDefined", "disable")
    ScriptObfuscatedMacroCodeType                   = "userDefined"
    ScriptDownloadedPayloadExecutionType            = @("userDefined", "warn")
    ProcessCreationType                             = "userDefined"
    UntrustedUSBProcessType                         = "userDefined"
    UntrustedExecutableType                         = "userDefined"
    EmailContentExecutionType                       = "userDefined"
    GuardMyFoldersType                              = "userDefined"
}
```

**Comment by andikrueger** [comment]
I just want to make sure, that I get it right: I just reviewed #3434 and your screenshot of the admin portal. Within the screenshot, there is a value 'warn'  which is not valid to use within the Set-Method of the used cmdLets? 

image

The Get-Method of said cmdLet does return warn and all the other values:

notConfigured, block, auditMode, userDefined, disable.

which are supported by the set-cmdlet. Is this correct? If yes, this is more likely to be an issue on the MS Graph/UI side, that needs to be fixed, prior us creating a workaround to avoid a breaking change.

**Comment by ricmestre** [comment]
The Get-Method gets the correct values from the tenant, so for this specific case the property EmailContentExecutionType should have values of:

- 'notConfigured', 'block', 'auditMode', 'warn', 'disable'

but the ValidateSet in psm1, which is incorrect, is:

- 'userDefined', 'block', 'auditMode', 'warn', 'disable'

but also on the other hand, the schema is also incorrect with different set of values:

- "notConfigured", "block","auditMode", "userDefined", "disable"

**Comment by andikrueger** [comment]
If we would change the validate set of the schema and the module to be

- 'notConfigured', 'block', 'auditMode', 'warn', 'disable' > which are the supported values

and 

- 'userDefined' > which is the **not** supported value

We would not have a breaking change and would make sure that all current values are supported.

Within the module we would need to add a warning/error that the value *userDefined* is not supported.

**Comment by ricmestre** [comment]
My previous question was exactly if the ValidateSets should be changed to accept all values, including the incorrect ones, the problem with printing the warning is why print it at all if the deployment will fail with an incorrect value?

**Comment by andikrueger** [comment]
This is very true. I totally understand the dilemma.

If we change the validate set, existing configurations with the value 'userDefined' will no longer compile -> This would be a breaking change - see Nik's comment about the Breaking Change policy.

On the other hand, no-one was able to successfully apply this configuration anyways and the configuration could not be set to 'warn' - even if this was the returned value within an export...

I would focus on making the non breaking change and having allow exports to be compiled, rather than worrying about users who might change the value to a not supported value. They should be warned in addition to getting a system error.

**Comment by ricmestre** [comment]
OK great, I'll revert back all changes and start changing the sets in both the schema and module to accept current values (old) plus the correct ones (new). In the meantime please check if the below would be enough to add in Set-TargetResource method to error out on invalid values.

```powershell
$IncorrectParameters = @{
    BlockPersistenceThroughWmiType                  = @("userDefined", "warn")
    OfficeAppsOtherProcessInjectionType             = "userDefined"
    OfficeAppsLaunchChildProcessType                = "userDefined"
    OfficeAppsExecutableContentCreationOrLaunchType = "userDefined"
    OfficeMacroCodeAllowWin32ImportsType            = "userDefined"
    OfficeCommunicationAppsLaunchChildProcess       = @("userDefined", "disable")
    ScriptObfuscatedMacroCodeType                   = "userDefined"
    ScriptDownloadedPayloadExecutionType            = @("userDefined", "warn")
    ProcessCreationType                             = "userDefined"
    UntrustedUSBProcessType                         = "userDefined"
    UntrustedExecutableType                         = "userDefined"
    EmailContentExecutionType                       = "userDefined"
    GuardMyFoldersType                              = "userDefined"
}

foreach ($PSBoundParameter in $PSBoundParameters.Keys)
{
    $InvalidValue = $IncorrectParameters[$PSBoundParameter]
    if (![string]::IsNullOrEmpty($InvalidValue))
    {
        if ($PSBoundParameters.$PSBoundParameter -in $InvalidValue)
        {
            $ExceptionMessage = "Property {0} set to invalid value: {1}" -f $PSBoundParameter, $PSBoundParameters.$PSBoundParameter

            New-M365DSCLogEntry -Message 'Error updating data:' `
                -Exception $ExceptionMessage `
                -Source $($MyInvocation.MyCommand.Source) `
                -TenantId $TenantId `
                -Credential $Credential

            return $nullresult
        }
    }
}
```

**Comment by andikrueger** [comment]
I'm checking the values right now.

Just two remarks: 

1. Why is there a $nullresult?
2. It would be good to post a verbose message as well:

            Write-Verbose -Message "The Value is not supported. Please update your configuration."

**Comment by ricmestre** [comment]
@andikrueger I didn't test that code, it was just a quick mock up to show it, this is the commit I'm going to push now.

```powershell
    $IncorrectParameters = @{
        BlockPersistenceThroughWmiType                  = @("userDefined", "warn")
        OfficeAppsOtherProcessInjectionType             = "userDefined"
        OfficeAppsLaunchChildProcessType                = "userDefined"
        OfficeAppsExecutableContentCreationOrLaunchType = "userDefined"
        OfficeMacroCodeAllowWin32ImportsType            = "userDefined"
        OfficeCommunicationAppsLaunchChildProcess       = "disable"
        ScriptObfuscatedMacroCodeType                   = "userDefined"
        ScriptDownloadedPayloadExecutionType            = @("userDefined", "warn")
        ProcessCreationType                             = "userDefined"
        UntrustedUSBProcessType                         = "userDefined"
        UntrustedExecutableType                         = "userDefined"
        EmailContentExecutionType                       = "userDefined"
        GuardMyFoldersType                              = "userDefined"
    }

    $ExceptionMessage = $null
    foreach ($Key in $PSBoundParameters.Keys)
    {
        $InvalidValue = $IncorrectParameters[$Key]
        if (![string]::IsNullOrEmpty($InvalidValue))
        {
            $Value = $PSBoundParameters.$Key
            if ($Value -in $InvalidValue)
            {
                $ExceptionMessage += "Property {0} set to invalid value {1}`n" -f $Key, $Value
            }
        }
    }

    if (![string]::IsNullOrEmpty($ExceptionMessage))
    {
        $ExceptionMessage += "Please update your configuration."
        Write-Verbose -Message $ExceptionMessage

        New-M365DSCLogEntry -Message 'Error updating data:' `
            -Exception $ExceptionMessage `
            -Source $($MyInvocation.MyCommand.Source) `
            -TenantId $TenantId `
            -Credential $Credential

        return $null
    }
```

**Comment by ricmestre** [comment]
All tests pass with my changes and they correctly fail (only during Set, others pass) if I set one of the properties in the test to an invalid value.

**Comment by andikrueger** [comment]
Just removed the Breaking Changes label as the current solution will not be a Breaking change.

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
