### PR TITLE
PR: Fixes 3335

### PR DESCRIPTION
**Pull request by William-Francillette**
#### This Pull Request (PR) fixes the following issues

* Intune Resources
  * Fixes an issue with trailing charaters in the export job
    FIXES [#3335](https://github.com/microsoft/Microsoft365DSC/issues/3335)
- IntuneApplicationControlPolicyWindows10
- IntuneDeviceConfigurationDeliveryOptimizationPolicyWindows10
- IntuneDeviceConfigurationEndpointProtectionPolicyWindows10
- IntuneDeviceConfigurationHealthMonitoringConfigurationPolicyWindows10
- IntuneDeviceConfigurationIdentityProtectionPolicyWindows10
- IntuneWindowsUpdateForBusinessFeatureUpdateProfileWindows10
- IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10

### CODE REVIEW

**Comment by ricmestre** [comment]
@William-Francillette LGTM but it still misses the same chunk of code, inserted below, in one of the affected resources I reported (IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled). As I initially reported there might be other resources affected but these were the ones I was able to figure out for now, if I find others I'll let you know.

https://github.com/microsoft/Microsoft365DSC/blob/0866c08d62737cf0cd535e754c9a0ea2f31d35f5/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.psm1#L1161

**Comment by ricmestre** [comment]
A quick grep shows me that both IntuneWindowsAutopilotDeploymentProfileAzureADHybridJoined and IntuneWindowsAutopilotDeploymentProfileAzureADJoined are also affected.

**Comment by ricmestre** [comment]
@William-Francillette Hi, please have a look at my PR #3364 , as mentioned there "Chunk of code added to all resources that call Convert-DSCStringParamToVariable and that at least one of those calls has an object with an array of CIM instances (or may have depending on the exported resource)."

**Comment by ricmestre** [comment]
Yes I saw your discussion with Andi about this on the other thread, but at least for the currently available resources I need this resolved since I'm soon going to production and this is one of the major issues I've still have opened so I'd like to get this in ASAP.

**Comment by NikCharlebois** [comment]
Would #3364 also address this. I want to make sure we only fix this in a central location and to me, fixing it in ReverseDSC is the logical thing to do.

**Comment by ricmestre** [comment]
@NikCharlebois I have a PR opened in ReverseDSC to address this issue https://github.com/microsoft/ReverseDSC/pull/33, as mentioned there #3362 and #3364 can be cancelled once that fix is in.

**Comment by William-Francillette** [comment]
Makes more sense to fix ReverseDSC imo - this can be cancelled if that's the case

**Pull request closed without merging**
