### PR TITLE
Adding EXOFocusedInbox Resource

### PR DESCRIPTION
**Pull request by kasaxena5**

### CODE REVIEW

**Comment by ykuijs** [comment]
Hi @kasaxena5, thanks for your PR. Can you please make sure an entry is added in the Changelog under the Unreleased section (in alphabetical order please)?

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Please add an entry in the ChangeLog

**Comment by kasaxena5** [comment]
> Hi @kasaxena5, thanks for your PR. Can you please make sure an entry is added in the Changelog under the Unreleased section (in alphabetical order please)?

Added Changelog entry. Thanks :)

**Comment by kasaxena5** [comment]
Added Change Logs

**Pull request merged**
