### PR TITLE
Fixes for Issue #763

### LINKED ISSUE #763: Extracting [EXOAvailabilityAddressSpace] Logging a new Error. Cannot bind argument to parameter 'ResourceName' because it is an empty string.
#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}

#### Version of the DSC module that was used:- dev

sorry still getting the error, opening new case as #729 was closed

in ps admin ran
Install-M365DSCDevBranch
closed

in ps admin ran lite version of
Export-M365DSCConfiguration

gets to here and errors
[13/101] Extracting [EXOAvailabilityAddressSpace]...
    |---[1/1] dxxxxno.nxxxxxxxxxxxo.co.uk❌ Logging a new Error
PS C:\WINDOWS\system32>

[2020/09/02 08:08:13]
{InvalidData}
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'ResourceName' because it is an empty string.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
""

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Added error handling across multiple EXO resources. @Nlangsto this one is for you :)

#### This Pull Request (PR) fixes the following issues
- Fixes #763

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/801)

### CODE REVIEW

**Comment by nlangsto** [comment]
You legend, giving it a go now.

**Comment by NikCharlebois** [comment]
@ykuijs could you review when you get a chance? Thanks

**Comment by nlangsto** [comment]
How do I pull this version?

**Comment by NikCharlebois** [comment]
It would be a manual process. Download the zip file:
https://github.com/NikCharlebois/Microsoft365DSC/archive/Issue763.zip

Then manually copy the xxx/Modules/Microsoft365DSC folder under C:\Program Files\WindowsPowerShell\Modules

**Comment by nlangsto** [comment]
Don't know what you did with error handling, but that now works. :-) Do you need anything from me? Did see any logs created.
Thanks!!

**Comment by NikCharlebois** [comment]
Nope, all good. Glad to hear it fixes it. The problem was that some cmdlets are now available on some tenants. The tool was failing if it was the case, now it simply moves on to the next component. Just sit tight until next Wednesday when we will have this fix released to the PowerShell Gallery 😄

**Comment by nlangsto** [comment]
Well, thank you very much for sorting! Much appreciated.

**Comment by nlangsto** [comment]
Found a new one,...

[49/122] Extracting [EXOSharingPolicy]...
    |---[1/2] Def************rardy✅
[50/122] Extracting [IntuneDeviceCategory]...❌ Logging a new Error
PS C:\Users\micro>

Guess I need to give you a break tho. :-)

**Comment by nlangsto** [comment]
And another one, not sure if its because of the build I have or something more fundamental.

[54/105] Extracting [SCComplianceSearchAction]...
    Tenant Wide Actions:
        |---[1/8] Jaxxxxxxxxxxxxxxxxxxxxnly✅
        |---[2/8] PartnerTrainingCSP-DirectBill-ALL_ReportsOnly✅
        |---[3/8] PartnerTrainingCSP-DirectBill-ALL_Preview❌ Logging a new Error
PS C:\WINDOWS\system32>



[2020/09/25 09:51:50]
{AuthenticationError}
Microsoft.Open.Azure.AD.CommonLibrary.AadAuthenticationFailedException: One or more errors occurred.: AADSTS50034: The user account {EmailHidden} does not exist in the nexxxxxxxxxxk directory. To sign into this application, the account must be added to the directory.
Trace ID: 9664f448-500b-4e88-825e-668beef30d00
Correlation ID: 4020b1bf-0bdd-4c55-925d-03f57c6d103a
Timestamp: 2020-09-25 08:51:49Z ---> System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS50034: The user account {EmailHidden} does not exist in the nerxxxxxxxxxxxxxxx directory. To sign into this application, the account must be added to the directory.
Trace ID: 9664f448-500b-4e88-825e-668beef30d00
Correlation ID: 4020b1bf-0bdd-4c55-925d-03f57c6d103a
Timestamp: 2020-09-25 08:51:49Z ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (BadRequest). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_grant","error_description":"AADSTS50034: The user account {EmailHidden} does not exist in the nexxxxxxxxxxk directory. To sign into this application, the account must be added to the directory.\r\nTrace ID: 9664f448-500b-4e88-825e-668beef30d00\r\nCorrelation ID: 4020b1bf-0bdd-4c55-925d-03f57c6d103a\r\nTimestamp: 2020-09-25 08:51:49Z","error_codes":[50034],"timestamp":"2020-09-25 08:51:49Z","trace_id":"9664f448-500b-4e88-825e-668beef30d00","correlation_id":"4020b1bf-0bdd-4c55-925d-03f57c6d103a","error_uri":"https://login.microsoftonline.com/error?code=50034"}: Unknown error
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.DoAcquireToken(AdalConfiguration config, PromptBehavior promptBehavior, String userId, SecureString password) in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 228
   at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.SafeAquireToken(AdalConfiguration config, ShowDialog showDialog, String userId, SecureString password, Exception& ex) in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 152
   --- End of inner exception stack trace ---
   at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.AcquireToken(AdalConfiguration config, ShowDialog promptBehavior, String userId, SecureString password) in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 134
   at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.GetAccessToken(AdalConfiguration config, ShowDialog promptBehavior, String userId, SecureString password, AccountType credentialType) in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 57
   at Microsoft.Open.Azure.AD.CommonLibrary.AuthenticationFactory.Authenticate(AzureAccount account, AzureEnvironment environment, String tenantId, SecureString password, ShowDialog promptBehavior, TokenCache tokenCache, Endpoint resourceId) in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\AuthenticationFactory.cs:line 59
   at Microsoft.Open.Azure.AD.CommonLibrary.RMProfileClient.AcquireAccessToken(AzureAccount account, AzureEnvironment environment, String tenantId, SecureString password, ShowDialog promptBehavior) in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\RMProfileClient.cs:line 127
   at Microsoft.Open.Azure.AD.CommonLibrary.RMProfileClient.Login(AzureAccount account, AzureEnvironment environment, String tenantId, SecureString password) in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\RMProfileClient.cs:line 55
   at Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD.ProcessRecord() in X:\bt\1110322\repo\src\dev\PowerShell.V2\CommonLibrary\ConnectAzureAD.cs:line 163
""

""

And the error from my previous post.


[2020/09/25 09:54:59]
{ObjectNotFound}
System.Management.Automation.CommandNotFoundException: The term 'Connect-MSCloudLoginIntune' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Test-MSCloudLogin(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()


[2020/09/25 09:59:56]
{NotSpecified}
System.InvalidOperationException: There is currently no connection yet. Use Connect-PnPOnline to connect.
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.BeginProcessing()
   at PnP.PowerShell.Commands.PnPSharePointCmdlet.BeginProcessing()
   at PnP.PowerShell.Commands.Base.PnPAdminCmdlet.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
"Failed to get Tenant client sync settings"

**Comment by NikCharlebois** [comment]
Ok, so at least we know how to fix those. Hand on tight, we will do a major refactor and update the error handling mechanisms on all resource across the board.

**Comment by NikCharlebois** [comment]
@ykuijs ready for review....take 2

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 132 of 132 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/801#-:-MI60ean-W3zKMncTYv0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
