### PR TITLE
EXOHostedContentFilterPolicy: Removed depricated options 

### LINKED ISSUE #950: EXOHostedContentFilterPolicy: Fails with EndUserSpamNotificationCustomFromAddress as ""
#### Details of the scenario you tried and the problem that is occurring
When trying to set EXOHostedContentFilterPolicy, the EndUserSpamNotificationCustomFromAddress fails to be set because it is not a SMTP address.
Changing it to `$null` works.
#### Verbose logs showing the problem
```
Cannot process argument transformation on parameter 'EndUserSpamNotificationCustomFromAddress'. Cannot convert value "" to type "Microsoft.Exchange.Data.SmtpAddress". Error: "The email address '' isn't correct.  Please use this format: user name, the @ sign, followed by the domain name. For example, tonysmith@contoso.com or tony.smith@contoso.com."
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-HostedContentFilterPolicy
    + PSComputerName        : localhost
```
#### Suggested solution to the issue
Either change the parameter to $null if it is "", or remove the parameter since the doc says it is deprecated: 
https://docs.microsoft.com/en-us/powershell/module/exchange/set-hostedcontentfilterpolicy?view=exchange-ps
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        EXOHostedContentFilterPolicy 3534b8f4-109b-43c9-a3cc-1d848d4aa593
        {
            AddXHeaderValue                          = "";
            AdminDisplayName                         = "";
            AllowedSenderDomains                     = @();
            AllowedSenders                           = @();
            BlockedSenderDomains                     = @();
            BlockedSenders                           = @();
            BulkSpamAction                           = "NoAction";
            BulkThreshold                            = 7;
            DownloadLink                             = $False;
            EnableEndUserSpamNotifications           = $True;
            EnableLanguageBlockList                  = $False;
            EnableRegionBlockList                    = $False;
            EndUserSpamNotificationCustomFromAddress = "";
            EndUserSpamNotificationCustomFromName    = "";
            EndUserSpamNotificationCustomSubject     = "";
            EndUserSpamNotificationFrequency         = 3;
            EndUserSpamNotificationLanguage          = "Default";
            Ensure                                   = "Present";
            GlobalAdminAccount                       = $Credsglobaladmin;
            HighConfidenceSpamAction                 = "MoveToJmf";
            Identity                                 = "Security_Spam_Filter";
            IncreaseScoreWithBizOrInfoUrls           = "Off";
            IncreaseScoreWithImageLinks              = "Off";
            IncreaseScoreWithNumericIps              = "Off";
            IncreaseScoreWithRedirectToOtherPort     = "Off";
            InlineSafetyTipsEnabled                  = $True;
            LanguageBlockList                        = @();
            MakeDefault                              = $False;
            MarkAsSpamBulkMail                       = "Off";
            MarkAsSpamEmbedTagsInHtml                = "Off";
            MarkAsSpamEmptyMessages                  = "Off";
            MarkAsSpamFormTagsInHtml                 = "Off";
            MarkAsSpamFramesInHtml                   = "Off";
            MarkAsSpamFromAddressAuthFail            = "Off";
            MarkAsSpamJavaScriptInHtml               = "Off";
            MarkAsSpamNdrBackscatter                 = "Off";
            MarkAsSpamObjectTagsInHtml               = "Off";
            MarkAsSpamSensitiveWordList              = "Off";
            MarkAsSpamSpfRecordHardFail              = "Off";
            MarkAsSpamWebBugsInHtml                  = "Off";
            ModifySubjectValue                       = "";
            PhishSpamAction                          = "MoveToJmf";
            PhishZapEnabled                          = $True;
            QuarantineRetentionPeriod                = 15;
            RedirectToRecipients                     = @();
            RegionBlockList                          = @();
            SpamAction                               = "MoveToJmf";
            SpamZapEnabled                           = $True;
            TestModeAction                           = "None";
            TestModeBccToRecipients                  = @();
        }
        EXOHostedContentFilterRule d67fa97d-7aa6-4c0d-8804-8fadaa6553d2
        {
            Enabled                   = $True;
            Ensure                    = "Present";
            GlobalAdminAccount        = $Credsglobaladmin;
            HostedContentFilterPolicy = "Security_Spam_Filter";
            Identity                  = "Anti-Spam Policy";
            Priority                  = 0;
            RecipientDomainIs         = @("$OrganizationName");
        }
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows 10 Enterprise Evaluation
OsOperatingSystemSKU : 72
OsArchitecture       : 64-bit
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.1125.1

### PR DESCRIPTION
**Pull request by Swampen**
#### Pull Request (PR) description
Removed depricated options EndUserSpamNotificationCustomFromAddress and EndUserSpamNotificationCustomFromName.
Updated example with ZapEnabled options.

Doc: https://docs.microsoft.com/en-us/powershell/module/exchange/set-hostedcontentfilterpolicy?view=exchange-ps

#### This Pull Request (PR) fixes the following issues
Fixes #950

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/999)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@Swampen Removing a parameter is considered a breaking change since it would break any existing configuration making use of that parameter. To get around this, we recommend using the following pattern:

**Get-TargetResource:**
Remove the deprecated parameter from the returned Hashtable;
 
**Set-TargetResource:**
Remove the deprecated parameters from the set of parameters used with the New/Set cmdlets & print a message to let the user know that it is deprecated.
 
**Test-TargetResource:**
Remove the deprecated parameters from the set of parameters to be evaluated
 
**Export-TargetResource:**
No Changes

Can you please update your PR accordingly? Thanks

**Comment by Swampen** [comment]
Sure! Did not realize it would break existing configurations.

@NikCharlebois Is the changes what you asked for?

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
One small comment regarding the schemamof

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/999#-:-MPAeORI5COaCLqMWrb0:bsy0uu6)* status: all files reviewed, 1 unresolved discussion (waiting on @Swampen)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOHostedContentFilterPolicy/MSFT_EXOHostedContentFilterPolicy.schema.mof, line 17 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/999#-MPAeHLJ4r-mzMPUWv_2:-MPAeHLK4aajVRoDlKvb:b-8r2dw9) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81343171478105b0ccddff4429554ed5b81b1b41/Modules/Microsoft365DSC/DSCResources/MSFT_EXOHostedContentFilterPolicy/MSFT_EXOHostedContentFilterPolicy.schema.mof#L17)):*
> ```
>     [Write, Description("The EnableLanguageBlockList parameter enables or disables blocking email messages that are written in specific languages, regardless of the message contents. Valid input for this parameter is $true or $false. The default value is $false.")] Boolean EnableLanguageBlockList;
>     [Write, Description("The EnableRegionBlockList parameter enables or disables blocking email messages that are sent from specific countries or regions, regardless of the message contents. Valid input for this parameter is $true or $false. The default value is $false.")] Boolean EnableRegionBlockList;
>     [Write, Description("The EndUserSpamNotificationCustomFromAddress parameter specifies a custom From address for end-user spam notification messages. Valid input for this parameter is an SMTP email address or an empty string.")] String EndUserSpamNotificationCustomFromAddress;
> ```

The schema.mof file needs to continue to define these. Simply update the description to reflect that they are deprecated.

**Review by NikCharlebois — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/999#-:-MQOIso9AyF9RLS5J-Lt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Swampen)

**Pull request merged**
