### PR TITLE
M365DSCRuleEvaluation: Log both matching and not matching resources and in XML format

### PR DESCRIPTION
**Pull request by ricmestre**
#### Pull Request (PR) description

This PR aims to log both the matching and not matching resources instead of only the latter.

While here since I'll be starting to use this it's preferred to handle the log as XML like it's already done for the drifts logging than to fiddle with string parsing.

The schema is as follows and I'm open to suggestions if it needs improvement:

```xml
<M365DSCRuleEvaluation>
  <ResourceName>String</ResourceName>
  <RuleDefinition>String</RuleDefinition>
  <AfterRuleCount>
    <Query>String</Query>
    <MetQuery>Boolean</MetQuery>
  </AfterRuleCount>
  <Match>
    <ResourceInstanceName>String</ResourceInstanceName>
    <ResourceInstanceName>...</ResourceInstanceName>
  </Match>
  <NotMatch>
    <ResourceInstanceName>String</ResourceInstanceName>
    <ResourceInstanceName>...</ResourceInstanceName>
  </NotMatch>
</M365DSCRuleEvaluation>
```

### CODE REVIEW

**Comment by andikrueger** [comment]
I like the idea to add this information.

Looks like there is something off with the XML. The opening and closing XML tags do not match.

<ResourceInstanceName>String</ResourceName>
 <ResourceInstanceName>...</ResourceName>

**Comment by ricmestre** [comment]
@andikrueger It was just a typo in the PR summary, in the code it's actually correct as <ResourceInstanceName>...</ResourceInstanceName>, I'll update the summary.

**Comment by ricmestre** [comment]
Couple of examples below I've ran on my test tenant and got in event viewer:

RuleDefinition matches but AfterRuleCountQuery is defined and doesn't match (there's only one ODSettings, not 2):

```xml
<M365DSCRuleEvaluation>
  <ResourceName>ODSettings</ResourceName>
  <RuleDefinition>$_.ODBAccessRequests -eq "Unspecified"</RuleDefinition>
  <AfterRuleCount>
    <Query>-eq 2</Query>
    <MetQuery>False</MetQuery>
  </AfterRuleCount>
  <Match>
    <ResourceInstanceName>[ODSettings]ODSettings</ResourceInstanceName>
  </Match>
  <NotMatch></NotMatch>
</M365DSCRuleEvaluation>
```

There's 2 TeamsCallingPolicy with ```$_.AllowCallForwardingToPhone -eq $false```, which are inside ```<Match>``` and inside *<NotMatch>* there are 3 extra policies included which don't match the rule. Additionally ```AfterRuleCountQuery = "-eq 2"``` and since it matches the number of matching resources ```<MetQuery>``` is set to True, if it didn't it would be set to False:

```xml
<M365DSCRuleEvaluation>
  <ResourceName>TeamsCallingPolicy</ResourceName>
  <RuleDefinition>$_.AllowCallForwardingToPhone -eq $false</RuleDefinition>
  <AfterRuleCount>
    <Query>-eq 2</Query>
    <MetQuery>True</MetQuery>
  </AfterRuleCount>
  <Match>
    <ResourceInstanceName>[TeamsCallingPolicy]TeamsCallingPolicy-Tag:DisallowCalling</ResourceInstanceName>
    <ResourceInstanceName>[TeamsCallingPolicy]TeamsCallingPolicy-Tag:AllowCallingPreventForwardingtoPhone</ResourceInstanceName>
  </Match>
  <NotMatch>
    <ResourceInstanceName>[TeamsCallingPolicy]TeamsCallingPolicy-Global</ResourceInstanceName>
    <ResourceInstanceName>[TeamsCallingPolicy]TeamsCallingPolicy-Tag:AllowCalling</ResourceInstanceName>
    <ResourceInstanceName>[TeamsCallingPolicy]TeamsCallingPolicy-Tag:AllowCallingPreventTollBypass</ResourceInstanceName>
  </NotMatch>
</M365DSCRuleEvaluation>
```

**Review by andikrueger — APPROVED** [review]
LGTM

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
