### PR TITLE
Aad role settings

### LINKED ISSUE #2227: AADRoleSetting throws an error if there are no AAD P2 licenses in a tenant
#### Details of the scenario you tried and the problem that is occurring
Call Export-M365DSCConfiguration -Workload AAD
throws an error when attempting to export AADRoleSettings

#### Verbose logs showing the problem
[8/11] Extracting [AADRoleSetting]...
    |---[1/92] Global AdministratorGet-MgPolicyRoleManagementPolicyAssignment : The tenant needs an AAD Premium 2 licens
e.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.824.1\DSCResources\MSFT_AADRoleSetting\MSFT_AADRoleS
etting.psm1:215 char:5
+     $Policy = Get-MgPolicyRoleManagementPolicyAssignment -Filter $Fil ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgPolic
   yRol...ssignment_List1], RestException`1
    + FullyQualifiedErrorId : AadPremiumLicenseRequired,Microsoft.Graph.PowerShell.Cmdlets.GetMgPolicyRoleManagementPo
   licyAssignment_List1
Cannot bind argument to parameter 'UnifiedRoleManagementPolicyId' because it is an empty string.

#### Suggested solution to the issue
Fail gracefully if cmdlet throws an error

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.5246.amd64fre.rs1_release.220701-1744
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
'dev' (1.22.824.1)

### PR DESCRIPTION
**Pull request by sandrola**

### CODE REVIEW

**Comment by andikrueger** [comment]
Please add an entry with the changed to the changelog under a unreleased section.

**Comment by NikCharlebois** [comment]
Unfortunately renaming an existing resource is a breaking change. Either we stick with the current naming or we need to wait until October to release as part of the breaking change release.

**Comment by sandrola** [comment]
Ok, we can keep the old name (issue with P2 License is resolved). Can the Pull request be deleted? I will then create a new one.

**Comment by NikCharlebois** [comment]
Sure, let me close it. Thanks

**Pull request closed without merging**
