### PR TITLE
Update Manifest.psd1

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
* Removed dependency for Microsoft.Graph.Beta.Identity.DirectoryManagement since we already require the beta module.

#### This Pull Request (PR) fixes the following issues
* N/A

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@William-Francillette somehow I missed this in your PR. Since we are already requiring the Microsoft.Graph.Beta.Identity.DirectoryManagement module, we shouldn't be also requiring the v1.0 version. Can you please confirm that this won't have any impact on your stuff? Thanks

**Comment by William-Francillette** [comment]
@NikCharlebois, it will break AADAdministrativeUnit as developed using v1.0
I can migrate teh feature and test it quickly - it shouldn't take too long will raise a new PR

**Comment by NikCharlebois** [comment]
My understanding is that AADAdministrativeUnit is already updated to run on Beta.

**Comment by William-Francillette** [comment]
> My understanding is that AADAdministrativeUnit is already updated to run on Beta.

My bad I missed that so we should be good to go

**Pull request merged**
