### PR TITLE
EXO Fixes

### LINKED ISSUE #1097: The Test-TargetSource for resource EXOOwaMailboxPolicy returns a false (non-compliant) when it should be in 1.21.224.1
I can manually invoke-dscresource for get, set without issues.  When I run test it fails stating that it was throttled by O365 due to too many open PSSessions; but this is a rabbit hole.  When I run in debug mode and Start-DSCConfiguration.  The Get-TargetSource does not add the fields CertificateThumbprint, ApplicationId TenantId to the returned CurrentValues hashtable and when calling Test-M365DSCParameterState to compare current values hashtable to the provided parameters which has those fields because we are using a certificate rather than a cloud account it returns a false.  I copied the file, update the get-dscresource to add the fields and the issue was resolved.  

39 of the 43 EXO resource are impacted with this issue which only occurs if a certificate is used.  I fixed the issue by adding the below code snippet to the Get-TargetResource method.

$result = @{
                .
                .
                .
                .

                ApplicationId  = $ApplicationId
                CertificateThumbprint = $CertificateThumbprint
                CertificatePath = $CertificatePath
                CertificatePassword = $CertificatePassword
                TenantId = $TenantId
            }

A few resources also needed the same elements added to the $nullReturn for resources that didn't implement $nullReturn = $PSBoundParameters, but instead creates the a hashtable to return.  Below is the list of impacted resources.

MSFT_EXOAddressBookPolicy
MSFT_EXOAddressList
MSFT_EXOAntiPhishPolicy
MSFT_EXOAntiPhishRule
MSFT_EXOApplicationAccessPolicy
MSFT_EXOAtpPolicyForO365
MSFT_EXOAvailabilityAddressSpace
MSFT_EXOAvailabilityConfig
MSFT_EXOCASMailboxPlan
MSFT_EXOClientAccessRule
MSFT_EXODkimSigningConfig
MSFT_EXOEmailAddressPolicy
MSFT_EXOGlobalAddressList
MSFT_EXOHostedConnectionFilterPolicy
MSFT_EXOHostedContentFilterPolicy
MSFT_EXOHostedContentFilterRule
MSFT_EXOHostedOutboundSpamFilterPolicy
MSFT_EXOInboundConnector
MSFT_EXOIntraOrganizationConnector
MSFT_EXOMailboxSettings
MSFT_EXOMailTips
MSFT_EXOMalwareFilterPolicy
MSFT_EXOMalwareFilterRule
MSFT_EXOManagementRole
MSFT_EXOMobileDeviceMailboxPolicy
MSFT_EXOOfflineAddressBook
MSFT_EXOOnPremisesOrganization
MSFT_EXOOrganizationConfig
MSFT_EXOOrganizationRelationship
MSFT_EXOOutboundConnector
MSFT_EXOOwaMailboxPolicy
MSFT_EXOPartnerApplication
MSFT_EXOPolicyTipConfig
MSFT_EXORemoteDomain
MSFT_EXORoleAssignmentPolicy
MSFT_EXOSafeAttachmentPolicy
MSFT_EXOSafeAttachmentRule
MSFT_EXOSharedMailbox			*
MSFT_EXOSharingPolicy

### LINKED ISSUE #1101: Export-M365DSCConfiguration hanging during run
#### Details of the scenario you tried and the problem that is occurring
Export-M365DSCConfiguration configuration is hanging and not progressing while exporting simple OneDrive configuration. The authentication is done through App Registration and Certificate Auth as shown in the picture below. 
image
image

#### Verbose logs showing the problem
image

#### Suggested solution to the issue
N/A
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A
#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.224.1

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Fixed issue in most EXO resources where AzureAD App information was not returned by the Get-TargetResource function

#### This Pull Request (PR) fixes the following issues
- Fixes #1101 
- Fixes #1097

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1132)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs can you please do a code review? Thanks

**Review by ykuijs — CHANGES_REQUESTED** [review]
Just a thought: Shouldn't we update the Test-M365ParameterState function to skip checking the GlobalAdminAccount, ApplicationId, TenantId, CertificateThumbprint, CertificatePath and CertificatePassword parameters?? That solution would be generic for all resources instead having to implement a solution for each current AND future resource.

> Reviewed 42 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1132#-:-MXISNgp2H_BwlEfa5yY:bd0ge74)* status: 42 of 43 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAddressBookPolicy/MSFT_EXOAddressBookPolicy.psm1, line 102 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1132#-MXIFCC17IPrNAPQwZYy:-MXIFCC2Bcyh1ZCRfQbo:b-bvphp8) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6154108556815dc69291b28f015570d6a56bc04e/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAddressBookPolicy/MSFT_EXOAddressBookPolicy.psm1#L102)):*
> ```PowerShell
>                 RoomList              = $AddressBookPolicy.RoomList
>                 Ensure                = 'Present'
>                 GlobalAdminAccount    = $GlobalAdmin
> ```

Why did you change this variable? $GlobalAdmin does not exist, right?

**Review by NikCharlebois — COMMENTED** [review]
Probably a good idea. We needed the Get-TargetResource to return these params for ReverseDSC for sure, but I agree that on the Tes-tTargetResource front, skipping these params would be a long lasting solution

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1132#-:-MXITtd52ikm4-xhlZe2:b-yk02zk)* status: 42 of 43 files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAddressBookPolicy/MSFT_EXOAddressBookPolicy.psm1, line 102 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1132#-MXIFCC17IPrNAPQwZYy:-MXIU4hRCBGeg1QtqLnV:b9wj1zk) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6154108556815dc69291b28f015570d6a56bc04e/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAddressBookPolicy/MSFT_EXOAddressBookPolicy.psm1#L102)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Why did you change this variable? $GlobalAdmin does not exist, right?
</blockquote></details>

It actually got pushed onto the next line :) It should be ApplicationID and not AccountApplicationId. Good catch. Done!

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1132#-:-MXIhGN75eebdoLL5Fmk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
