### PR TITLE
MSFT_AADPolicy : Initial Release

### LINKED ISSUE #491: AADPolicy

### PR DESCRIPTION
**Pull request by Timsto**
#### This Pull Request (PR) fixes the following issues

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/883)

### CODE REVIEW

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Few items to review

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-:-MLmZLxbAcozAUaJypgN:b-725i8g)* status: all files reviewed, 11 unresolved discussions (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 18 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmX70f7vdDyCKaKsrr:-MLmX70g-4aBe393zvLr:b-k0km2x) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L18)):*
> ```PowerShell
>         [System.String]
>         $AlternativeIdentifier,
>      
> ```

Remove empty spaces
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 20 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYTv07WV2HTiVkxDF:-MLmYTv07WV2HTiVkxDG:b-krh4zs) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L20)):*
> ```PowerShell
>      
>         [Parameter()]
>         [System.Collections.Generic.List`1[System.String]]
> ```

These should be defined as String[]
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 22 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmX8cbEwtpO9chmkMC:-MLmX8cbEwtpO9chmkMD:bjmrdx) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L22)):*
> ```PowerShell
>         [System.Collections.Generic.List`1[System.String]]
>         $Definition,
>      
> ```

Same remove empty spaces across the resource
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 28 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYQ_39hf3uiPauZQd:-MLmYQ_39hf3uiPauZQe:b-krh4zs) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L28)):*
> ```PowerShell
>      
>         [Parameter()]
>         [System.Collections.Generic.List`1[System.String]]
> ```

These should be defined as String[]
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 199 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmXqi1Ejc7aWR2jac9:-MLmXqi1Ejc7aWR2jacA:b-iklc40) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L199)):*
> ```PowerShell
>     Add-M365DSCTelemetryEvent -Data $data
>     #endregion
> ```

You are missing a call to New-M365DSCConnection somewhere in here to ensure you are connected to AzureAD.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 255 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYhCn6hanpblnLLbN:-MLmYhCn6hanpblnLLbO:b-7x4wvi) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L255)):*
> ```PowerShell
>         [Parameter()]
>         [Boolean]
>         $isOrganizationDefault,
> ```

Use Capital letters to start the name of your parameters Should be IsOrganizationDefault across all 3 methods (get/set/test)
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 287 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYd2e6heI70NzdvAD:-MLmYd2e6heI70NzdvAE:b-chjyfl) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L287)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message	"Testing configuration of AzureAD Policy"
> ```

Looks like you have an invalid character after message
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 295 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmXy4iANytYtH_NwX2:-MLmXy4iANytYtH_NwX3:b-8vc9ao) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L295)):*
> ```PowerShell
>     $ValuesToCheck = $PSBoundParameters
>     $ValuesToCheck.Remove('GlobalAdminAccount') | Out-Null
>     $ValuesToCheck.Remove("Id") | Out-Null   
> ```

You should also remove ApplicationId, TenantId and CertificateThumbprint from the evaluation logic.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 346 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYH6KD2Ly3iGeWI_n:-MLmYH6KD2Ly3iGeWI_o:b-x5t76x) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L346)):*
> ```PowerShell
>     {
>         $AADPolicy = Get-AzureADPolicy -ErrorAction Stop
>         foreach($AADPolicy in $AADPolicys)
> ```

AADPolicys doesn't exist as a variable. Make sure you recheck the entire logic here.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/readme.md, line 5 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmZ5Cl-1CwW-Ig0ORK:-MLmZ5Cl-1CwW-Ig0ORL:bq35wi0) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/readme.md#L5)):*
> ```Markdown
> ## Description
> 
> This resource configures the Azure AD Policys
> ```

'Policies' with 'ies'
___
*[Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1, line 21 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmZBjqDilUc7VCxUsR:-MLmZBjr7IZaEVzx75Mh:b-3c9q7w) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1#L21)):*
> ```PowerShell
>             DisplayName                   = "PolicyDisplayName"
>             Definition                    = @('{"TokenIssuancePolicy":{"Version": 1,"SigningAlgorithm": "http://www.w3.org/2000/09/xmldsig#rsa-sha1","TokenResponseSigningPolicy": "TokenOnly","SamlTokenVersion": "2.0"}}')
>             IsOrganizationDefault         = $false
> ```

Any chances you could also add the KeyCredentials parameters as part of your example? I am not exactly sure how to use it, and people reading our doc will want to know as well.

**Review by Timsto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/883)* status: all files reviewed, 11 unresolved discussions (waiting on @NikCharlebois and @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 20 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYTv07WV2HTiVkxDF:-MLmi0Jv-A0bAFotBCFQ:b-7ql1td) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L20)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

These should be defined as String[]
</blockquote></details>

fixed
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 22 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmX8cbEwtpO9chmkMC:-MLmlVKSEo8bDhiCEEQI:bo8n1mc) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L22)):*
> update branch AAD Policy
didnt find any extra emtpy spaces..  did we made some changes around the visibality and didnt make and spaces between the Paramters? 
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 199 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmXqi1Ejc7aWR2jac9:-MLmanQM65eWGDarjgUp:bb3vxba) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L199)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

You are missing a call to New-M365DSCConnection somewhere in here to ensure you are connected to AzureAD.
</blockquote></details>

but i call the Get-TargetResource which call New-M365DSCConnection and etablished the connection.   so it would be dublicated or? 
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 255 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYhCn6hanpblnLLbN:-MLmbW6b5XMahskdq6R-:b-7ql1td) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L255)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Use Capital letters to start the name of your parameters Should be IsOrganizationDefault across all 3 methods (get/set/test)
</blockquote></details>

fixed
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 287 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYd2e6heI70NzdvAD:-MLmbeQ72NEqz7sGjYK3:b-7ql1td) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L287)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Looks like you have an invalid character after message
</blockquote></details>

fixed
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 295 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmXy4iANytYtH_NwX2:-MLmbtJ457aadMSRakHL:b-7ql1td) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L295)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

You should also remove ApplicationId, TenantId and CertificateThumbprint from the evaluation logic.
</blockquote></details>

fixed
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 346 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYH6KD2Ly3iGeWI_n:-MLmc3SDBBFYREpq_eHt:bdrn5z3) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L346)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

AADPolicys doesn't exist as a variable. Make sure you recheck the entire logic here.
</blockquote></details>

was a missing 's' -> fixed
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/readme.md, line 5 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmZ5Cl-1CwW-Ig0ORK:-MLmcVru5-Z6a0yNtjr-:b-7ql1td) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/readme.md#L5)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

'Policies' with 'ies'
</blockquote></details>

fixed
___
*[Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1, line 21 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmZBjqDilUc7VCxUsR:-MLmepxTAloumG3NuKuZ:b4aledn) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1#L21)):*
> Any chances you could also add the KeyCredentials parameters as part of your example? I
i search for the meaning but the problem is that there is documantion about this paramter.  not internal or external.. is think this is a preview paramter or would be decrapted.   i will monitor it and add/remove it in thr future.

**Review by Timsto — COMMENTED** [review]
reviewd and comment and fixed

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-:-MLmlo8G9IJ5agOwy5Og:b-qyphg8)* status: all files reviewed, 11 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 18 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmX70f7vdDyCKaKsrr:-MLmltKpBRBmPC0jb9HD:bjwlp7o) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L18)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Remove empty spaces
</blockquote></details>

same as bottom
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 28 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYQ_39hf3uiPauZQd:-MLmlkeYETc2ltQNybGw:b-7ql1td) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L28)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

These should be defined as String[]
</blockquote></details>

fixed

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/883)* status: all files reviewed, 3 unresolved discussions (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 20 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYTv07WV2HTiVkxDF:-MLn1LHAE1UEbnlp_Z7t:b-3agfnz) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L20)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

I still see it as a System.COllections. It should be:

[Parameter()]
[System.String[]]
$Definition
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 28 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYQ_39hf3uiPauZQd:-MLn1Xc8D_iMDm5cU6QQ:b-34nkn1) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L28)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

I still see it as a System.COllections. It should be:

[Parameter()]
[System.String[]]
$KeyCredentials
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 199 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmXqi1Ejc7aWR2jac9:-MLn1hFT7NB4NSTW1uIs:b-pi9uam) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L199)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

but i call the Get-TargetResource which call New-M365DSCConnection and etablished the connection.   so it would be dublicated or? 
</blockquote></details>

Good call. No, my bad, you are right, it will be connecting inside the Get
___
*[Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1, line 21 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmZBjqDilUc7VCxUsR:-MLn5juy1vpsWYJT5AhN:bf806bn) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1#L21)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

> Any chances you could also add the KeyCredentials parameters as part of your example? I
i search for the meaning but the problem is that there is documantion about this paramter.  not internal or external.. is think this is a preview paramter or would be decrapted.   i will monitor it and add/remove it in thr future.  

</blockquote></details>

We should probably remove this parameter then if we can't find examples on how to use it

**Review by Timsto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/883)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 20 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYTv07WV2HTiVkxDF:-MLqt2D39rx8oKNbI-dD:b-k9g1is) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L20)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I still see it as a System.COllections. It should be:

[Parameter()]
[System.String[]]
$Definition

</blockquote></details>

changed it to systemString.    i created it as an System.Collection because the docu from cmdlet told it to be an System.Collection
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 28 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmYQ_39hf3uiPauZQd:-MLqsnWlEx54F_PfFmEY:b-bvdkm9) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L28)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I still see it as a System.COllections. It should be:

[Parameter()]
[System.String[]]
$KeyCredentials


</blockquote></details>

parameter is completly removed
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1, line 199 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmXqi1Ejc7aWR2jac9:-MLqsmdc0uZD_OJqSYl1:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/DSCResources/MSFT_AADPolicy/MSFT_AADPolicy.psm1#L199)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Good call. No, my bad, you are right, it will be connecting inside the Get
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1, line 21 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-MLmZBjqDilUc7VCxUsR:-MLqsOagDlNTf2RTY0eO:bi9ooud) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e804588f46a9034478e2e98b765708fd96bac1be/Modules/Microsoft365DSC/Examples/Resources/AADPolicy/1-ConfigureAADPolicy.ps1#L21)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

We should probably remove this parameter then if we can't find examples on how to use it
</blockquote></details>

ok is removed.

**Review by NikCharlebois — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/883#-:-MLrQm1T5h9EJHdWSRt3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Timsto)

**Pull request merged**
