### PR TITLE
Fix Android Open Source Project Basic Wi-Fi Profile

### LINKED ISSUE #3976: IntuneWifiConfigurationPolicyAndroidOpenSourceProject: Policy gets created but Test-DSCConfiguration fails with error
### Description of the issue

Same problem as described in https://github.com/microsoft/Microsoft365DSC/issues/3970 and https://github.com/microsoft/Microsoft365DSC/issues/3971, https://github.com/microsoft/Microsoft365DSC/issues/3973 and #3975, the policy gets created but the Id field is bogus so when running Test-DSCConfiguration it says that it found a policy with that Id (which isn't true) and Graph complains that it actually doesn't exist. Trying to deploy any changes to the policy result in same error message.

### Microsoft 365 DSC Version

1.23.1122.1

### Which workloads are affected

other

### The DSC configuration

```powershell
# Generated with Microsoft365DSC version 1.23.1122.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration IntuneWifiConfigurationPolicyAndroidOpenSourceProject
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.1122.1'

    Node localhost
    {
        IntuneWifiConfigurationPolicyAndroidOpenSourceProject "IntuneWifiConfigurationPolicyAndroidOpenSourceProject-IntuneWifiConfigurationPolicyAndroidOpenSourceProject_1"
        {
            Assignments                    = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = '053dc89a-be83-411a-bad3-909904b7239e'
                }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = 'b0b8fd3f-af2a-453b-be57-80182d599f02'
                }
            );
            ConnectAutomatically           = $False;
            ConnectWhenNetworkNameIsHidden = $True;
            Credential                     = $Credscredential;
            DisplayName                    = "IntuneWifiConfigurationPolicyAndroidOpenSourceProject_1";
            Ensure                         = "Present";
            Id                             = "7cb1c5e8-58e2-497e-b544-faac420e025d";
            NetworkName                    = "sf";
            PreSharedKeyIsSet              = $True;
            Ssid                           = "sf";
            WiFiSecurityType               = "wpaPersonal";
        }
    }
}

IntuneWifiConfigurationPolicyAndroidOpenSourceProject -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential
```

### Verbose logs showing the problem

```powershell
[[IntuneWifiConfigurationPolicyAndroidOpenSourceProject]IntuneWifiConfigurationPolicyAndroidOpenSourceProject-IntuneWifiConfigurationPolicyAndroidOpenSourceProject_1] Testing configuration of
{7cb1c5e8-58e2-497e-b544-faac420e025d}
VERBOSE: [REDACTED]:
[[IntuneWifiConfigurationPolicyAndroidOpenSourceProject]IntuneWifiConfigurationPolicyAndroidOpenSourceProject-IntuneWifiConfigurationPolicyAndroidOpenSourceProject_1] Found something with id
{7cb1c5e8-58e2-497e-b544-faac420e025d}
[ResourceNotFound] : {
  "_version": 3,
  "Message": "DeviceConfigurations not found: Profile 7cb1c5e8-58e2-497e-b544-faac420e025d - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID:
20363475-83a8-41bd-bd4f-20e2f559a2eb - Url: https://fef.msub07.manage.microsoft.com/DeviceConfiguration_2311/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations('7cb1c5e8-58e2-497e-b544-
faac420e025d')/assignments?api-version=5023-10-14",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
    + CategoryInfo          : InvalidOperation: ({ DeviceConfigu...ndProperty =  }:) [], CimException
    + FullyQualifiedErrorId : ResourceNotFound,Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaDeviceManagementDeviceConfigurationAssignment_List
    + PSComputerName        : localhost
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, pt-PT}

Name                           Value
----                           -----
PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by FabienTschanz**
#### Pull Request (PR) description
**Attention**: Based on https://github.com/microsoft/Microsoft365DSC/pull/3992

This pull request updates the DSC resource for the Android Open Source Project Wi-Fi profile, specifically the "Basic" version of that Wi-Fi profile.

This change most likely results in a breaking change because the old DSC resource no longer exists.

Renames the `IntuneWiFiConfigurationPolicyAndroidOpenSourceProject` to [...]Basic, making clear that this is the "Basic" Wi-Fi profile. Management of the "Enterprise" variant will be implemented with a separate pull request.
Updates the modifiable properties and allowed values. For a "Basic" Wi-Fi profile, the WiFiSecurityType is either open, wep or wpaPersonal. Only Enterprise profiles have the wpaEnterprise possibility.

#### This Pull Request (PR) fixes the following issues ####
Fixes #3976

### CODE REVIEW

**Comment by ykuijs** [comment]
Same as with issue #3989:
A rename of the resource would indeed mean a breaking change, unless it never could have worked anyways. In that case existing configurations couldn't have used the resource and therefore renaming it will never break existing configurations.

I don't have much Intune expertise, so can't say much about the original resource. @William-Francillette Can you share your insights into this issue? Would the original resource have worked and is this a breaking change or not?

**Comment by FabienTschanz** [comment]
The policy is found in the Intune portal, but after selecting the policy, another popup for the Wi-Fi type appears. And that one mandates us to chose either "Basic" or "Enterprise". Depending on the selection, either a "Basic" or a "Enterprise" version of the policy is created, both with their respective (and some overlapping) properties, but different `@odata.type`s. 

Because there are far more properties and dependent settings inside the Enterprise one, I strongly encourage to differentiate both of these types, otherwise the configuration would be enormous and separating the properties from each other is a very tidious process. 

Additionally, if either of those policy types is used, they cannot be converted to the other one without creating a new policy. That in my opinion already necessitates the utilization of two different DSC resources. 

image

**Comment by William-Francillette** [comment]
To be honest, I'm not comfortable with changing how the resource was built - the reason being is that we used the Graph API schema as the based structure for the resource and not the parameter sets (if I can called them like that in PowerShell terms)/configuration settings  
We have created a dsc resource per @odata.type. I'm not aware if the the configuration settings are included in the schema or even publicly available so that we can generate the resource automatically that way.

**Comment by FabienTschanz** [comment]
@William-Francillette Depending on the chosen Wi-Fi type, the @odata.type differs. I understand that only having one resource for a specific policy in Intune is "better" than having two, but I already explained that the Wi-Fi types are not interoperable. Let's say I choose the "Basic" Wi-Fi type, I can then afterwards not switch to "Enterprise" or the other way around. 

Generating the resources automatically is difficult, as the @odata.types both support a common set of properties with specific types, but in the basic profile only selected options can be chosen in correlation. That makes for an extensive validation before deploying and a huge potential mistake opportunity. On the other hand, if the resources are split, a simpler validation can be performed. 

The way the resources are now they simply cannot work. Please let me know what the next steps are.

**Comment by FabienTschanz** [comment]
Hope you all had a great Christmas and start into the new year. 

I would like to continue the discussion. Any news on that front? We all want to use the resources without any issues, so the quicker we can come to an agreement on how to proceed, the better it is for all customers / users of the PowerShell module.

**Pull request closed without merging**
