### PR TITLE
Remove Id from PSBoundParameters in Test-TargetResource

### LINKED ISSUE #3888: Intune: Some resources can be deployed but fail test on Test-TargetResource method
### Description of the issue

The resources below can be deployed to other tenants after exporting from another source tenant, nevertheless the *Test-TargetResource* fails so the resources keep updating every time when *Start-DSCConfiguration* is called.

This is happening since in *Test-TargetResource* the property *Id* is not being removed from being checked just like it was done on #3886, additionally *CertificateThumbprint* and *ManagedIdentity* should also be removed from that check or better yet in this case just call *Remove-M365DSCAuthenticationParameter* (defined in M365DSCUtil.psm1) to remove all authentication parameters.

```powershell
IntuneDeviceConfigurationDeliveryOptimizationPolicyWindows10
IntuneDeviceConfigurationHealthMonitoringConfigurationPolicyWindows10
IntuneDeviceConfigurationIdentityProtectionPolicyWindows10
IntuneWindowsAutopilotDeploymentProfileAzureADHybridJoined
IntuneWindowsAutopilotDeploymentProfileAzureADJoined
```

### Microsoft 365 DSC Version

1.23.1108.1

### Which workloads are affected

other

### The DSC configuration

```powershell
N/A
```

### Verbose logs showing the problem

```powershell
N/A
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, pt-PT}

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by ricmestre**
#### Pull Request (PR) description
After deploy the resources below they always show up as not in desired state, this is because the *Id* parameter is not being removed from *PSBoundParameters* in Test-TargetResource, by removing it the issue is solved, except that the Autopilot ones also have a problem with *Assignments* property not being correctly set and therefore will not be completely fixed with this PR but I raised a separate issue for that.

IntuneDeviceConfigurationDeliveryOptimizationPolicyWindows10
IntuneDeviceConfigurationHealthMonitoringConfigurationPolicyWindows10
IntuneDeviceConfigurationIdentityProtectionPolicyWindows10
IntuneWindowsAutopilotDeploymentProfileAzureADHybridJoined
IntuneWindowsAutopilotDeploymentProfileAzureADJoined

EDIT: IntuneDeviceConfigurationEndpointProtectionPolicyWindows10 is affected by similar problem but not by not removing *Id* but *CertificateThumbprint*.
EDIT2: IntuneDeviceEnrollmentStatusPageWindows10 has both problems, it needs to have *Id* and all auth methods removed from Test, but also has problems with *Assignments* as reported on #3892 

#### This Pull Request (PR) fixes the following issues
- Fixes #3888

### CODE REVIEW

**Comment by ricmestre** [comment]
@William-Francillette If you have time and this PR is accepted could you please check the DRG in order to have similar changes as I have here?

**Comment by William-Francillette** [comment]
@NikCharlebois, @ykuijs @andikrueger 
Is there any use cases in checking Id in Test-TargetResource? If not, we may update Test-M365DSCParameterState from M365DSCUtil (around line 614) and force skipping Id as we do for the credentials parameters

**Comment by andikrueger** [comment]
I just try to understand why to remove the ID from test-TargetResource. Usually we would compare the ID if it’s passed into the resource as a desired parameter. 

If it is set, we should compare it. 

E.g. someone wants to change the DisplayName (key) of an object. This would only work, if we monitor the ID as well.

Please correct me if I got the purpose wrong or the context of this change.

**Comment by ricmestre** [comment]
@andikrueger If Id is not removed and is kept in the blueprint then when applying the policy to another tenant is not an issue but will complain that the resource is not in desired state because of course the Ids are different between tenants.

This is the same situation if Id is removed, now that it's not mandatory you can remove it therefore since the property is not there it will fallback to DisplayName and will just work, as long as the resource has been updated to do that, I know of some really old resources that if cannot be found by Id it won't fallback to DisplayName but that's another issue for another day.

**Comment by NikCharlebois** [comment]
> @NikCharlebois, @ykuijs @andikrueger Is there any use cases in checking Id in Test-TargetResource? If not, we may update Test-M365DSCParameterState from M365DSCUtil (around line 614) and force skipping Id as we do for the credentials parameters

There are cases where even if the property is named Id (or Identity) it is represented by a friendly display name instead of a GUID. In these cases we need to keep ID as a param in the Test-TargetResource.

**Review by ykuijs — APPROVED** [review]
LGTM

**Pull request merged**
