### PR TITLE
Certificate based authentication for Security and Compliance Workloads

### PR DESCRIPTION
**Pull request by manualbashing**
#### Pull Request (PR) description

With the ExchangeOnlineManagement module 3.0.0, certificate-based authentication for the Security and Compliance PowerShell was introduced.

Support for this was already merged to https://github.com/microsoft/MSCloudLoginAssistant/pull/133 but has not yet been released.

This PR adds certificate-based authentication accordingly to all SC workloads.

### CODE REVIEW

**Comment by NikCharlebois** [comment]
currently a bug in the Exo Management Shell Module that prevents connecting to security and compliance using thumbprint. Until this is fixed, we unfortunately cannot roll this out.

**Comment by NikCharlebois** [comment]
Plan is to have a new version of the module that will fix this issue released next week.

**Comment by andikrueger** [comment]
https://www.powershellgallery.com/packages/ExchangeOnlineManagement/3.0.1-Preview1 has a fix for cert based authentication.

**Review by NikCharlebois — APPROVED** [review]

**Comment by bjoernf73** [comment]
@manualbashing Du you have time for this one? I need this PR too - thanks for sharing!

**Comment by NikCharlebois** [comment]
Overridden by #2778

**Pull request closed without merging**
