### PR TITLE
Add deprecation notice to Intune resources

### LINKED ISSUE #5073: IntuneAccountProtectionPolicyWindows10 - Successor to IntuneAccountProtectionPolicy
### Description
Microsoft announced the [deprecation of the Account Protection Policy (Preview)](https://learn.microsoft.com/en-us/mem/intune/fundamentals/whats-new#consolidation-of-intune-profiles-for-identity-protection-and-account-protection-) in Microsoft Intune. This policy type is a intent policy that is available as the `IntuneAccountProtectionPolicy` resource in Microsoft365DSC. Currently, creating this policy in the Intune Portal is not possible anymore, although it does work by API. 

Also affected by that is the resource `IntuneDeviceConfigurationIdentityProtectionPolicyWindows10`. This one would be replaced by the new resource as well. 

### Suggestion
It would be best to remove this resource and replace it with a new one based on the Settings Catalog named `IntuneAccountProtectionPolicyWindows10`. This resource would be the successor to the other one. Because removal is difficult and backwards compatibility should be considered, adding a warning message to the previous resource and a mention in the change log should be enough for now. 

As soon as #5056 is merged, I can take a look at implementing the new Intune resource.

### PR DESCRIPTION
**Pull request by FabienTschanz**
#### Pull Request (PR) description
This PR adds the deprecation notice to the `IntuneAccountProtectionPolicy` and  `IntuneDeviceConfigurationIdentityProtectionPolicyWindows10` resources. 

#### This Pull Request (PR) fixes the following issues
- Fixes #5073

### CODE REVIEW

**Comment by FabienTschanz** [comment]
Unit tests failing because of the Graph Permission list not up to date.

**Comment by NikCharlebois** [comment]
> Unit tests failing because of the Graph Permission list not up to date.

This is something we need to look into ASAP. I will try to generate an exhaustive list of all possible permissions so that we don't run into these issues again. Stay tuned

**Comment by FabienTschanz** [comment]
> > Unit tests failing because of the Graph Permission list not up to date.
> 
> This is something we need to look into ASAP. I will try to generate an exhaustive list of all possible permissions so that we don't run into these issues again. Stay tuned

I don't know why, but they seem to be getting overwritten time and time again. But I don't really know why they are, and GitHub isn't that friendly to just tell us what the differences in the commit are (since it thinks the txt file is binary...).

**Comment by ricmestre** [comment]
It's complaining on *O365ExternalConnection* about *ExternalConnection.Read.All* again so my fix, which had been merged into Dev, was actually lost somewhere in a newer merge.

**Comment by FabienTschanz** [comment]
> It's complaining on _O365ExternalConnection_ about _ExternalConnection.Read.All_ again so my fix, which had been merged into Dev, was actually lost somewhere in a newer merge.

The problem of merge commits and not fast-forward merging 😢 But fast-forward has the disadvantage that every branch must be up to date with Dev at all times when merging...

**Comment by NikCharlebois** [comment]
I have generated a complete list of all possible permissions and will keep it up to date. Please make sure you merge the latest permissions file and update your branch.

**Comment by FabienTschanz** [comment]
Let's fetzzz

**Comment by FabienTschanz** [comment]
@NikCharlebois Now, the resource `AADConnectorGroupApplicationProxy` fails because its read permission is `Directory.ReadWrite.All`.

**Comment by NikCharlebois** [comment]
If you merge upstream you all issues should now be fixed.

**Comment by FabienTschanz** [comment]
@NikCharlebois Thank you, will try again.

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
