### PR TITLE
#3621: Dependencies Make Scope available

### PR DESCRIPTION
**Pull request by fasteiner**
#Pull Request (PR) description
Updated Install-M365DSCDevBranch, Update-M365DSCDependencies and Update-M365DSCModule to be usable with -Scope, allowing the user to install/update the module dependencies without admin rights, using current user scope. Confirm-M365DSCDependencies error message changed to reflect this change.

#This Pull Request (PR) fixes the following issues
[#3621](https://github.com/microsoft/Microsoft365DSC/issues/3621)

Co-authored-by: Thomas Subotitsch @tbone4711

### CODE REVIEW

**Comment by ykuijs** [comment]
I am fine with merging these changes, but **please keep in mind:** 
Installing the modules in the CurrentUser scope has a major downside: It works fine for an export, but doesn't work for a config deployment. A config deployment is executed by the LCM, which is running as System by default. So if you install the modules in your user scope, the LCM is unable to access these.

**Review by ykuijs — APPROVED** [review]
LGTM

**Comment by ykuijs** [comment]
Your change to the M365DSCUtil.psm1 file is incorrect. It is missing a closing } somewhere. Could you please check and fix?

**Comment by fasteiner** [comment]
Curly bracket added

**Comment by fasteiner** [comment]
> You have deleted the closing brace on line 4089. Please add that back in, which will fix the unit tests

done with commit: https://github.com/microsoft/Microsoft365DSC/pull/3622/commits/2a346fc5721bd22fe57a60886afe3a04e72bea46

**Comment by ykuijs** [comment]
I noticed that commit shortly after adding my previous comment 😉 Have already restarted the unit tests.

**Comment by ykuijs** [comment]
One last request: Could you please update with Dev? We just performed a new release and therefore a new Unreleased section has to be created. The GitHub merge features does not understand how to do that correctly 😛

**Pull request merged**
