### PR TITLE
Microsoft365 DSC for Intune Mobile Threat Defense connector.

### PR DESCRIPTION
**Pull request by Kajalp1079**

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Can you update your branch with the latest changes please? Thanks

**Comment by Kajalp1079** [comment]
> Can you update your branch with the latest changes please? Thanks

This is the one waiting on DisplayName input from your. This resource does not have DisplayName. Once I get your reply, I will do the correct merging.

**Comment by FabienTschanz** [comment]
@Kajalp1079 The current PR includes changes to many resources, including new ones (that are coming from other PRs). Please only include changes to the resource you're working on, except it's for something bigger.

**Comment by Kajalp1079** [comment]
was out for too long, too many conflicts. Closing this. Created a new one.

**Pull request closed without merging**
