### PR TITLE
Dev

### LINKED ISSUE #4275: MSFT_SCLabelSetting : Failing to create Sensitivity Labels
### Description of the issue

Exporting sensitivity labels from one tenant to another doesnt seen to work in multiple areas.

The parent ID is a GUID but this cannot even be adjusted as it looks like Set-Label doesnt support updating the parent ID guid post creation. 

Some of the code refers to the label name which is good and allows for the code to be tenant agnostic.

However the advanced section for parent labels

AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'parentid'
                    Value = '11111111-1111-1111-1111-11111111' # This is an issue
                }

It also doesnt seem to like creating the sensitivity label if it has templated encryption settings.

### Microsoft 365 DSC Version

V1.24.124.1

### Which workloads are affected

Security & Compliance Center

### The DSC configuration

```powershell
AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'parentid'
                    Value = '11111111-1111-1111-1111-11111111'
                }
```

### Verbose logs showing the problem

```powershell
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY] Testing AdvancedSettings
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY] Test AdvancedSettings returns True
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY] Testing LocaleSettings
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY] Test LocaleSettings returns True
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY] Test-TargetResource returned True
VERBOSE: [SomePC]: LCM:  [ End    Test     ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY]  in 4.6280 seconds.
VERBOSE: [SomePC]: LCM:  [ Skip   Set      ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY]
VERBOSE: [SomePC]: LCM:  [ End    Resource ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY]
VERBOSE: [SomePC]: LCM:  [ Start  Resource ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name]
VERBOSE: [SomePC]: LCM:  [ Start  Test     ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name]
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Testing configuration of Sensitivity label for 
LabelRef0406
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Getting configuration of Sensitivity Label for 
LabelRef0406
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Sensitivity label LabelRef0406 does not exist.
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Current Values: AdvancedSettings=({Key=parentid
; Value=22222222-2222-2222-2222-22222222},{Key=isparent; Value=False},{Key=color; Value=#FFFFFF})
ApplicationId=***
ApplyContentMarkingHeaderAlignment=Left
ApplyContentMarkingHeaderEnabled=True
ApplyContentMarkingHeaderFontColor=#000000
ApplyContentMarkingHeaderFontSize=10
ApplyContentMarkingHeaderMargin=5
ApplyContentMarkingHeaderText=ACME CONTROLLED\PROPRIETARY ~ Some Label Name
CertificateThumbprint=***
Comment=Label Name:LabelRef0406
Display Name: PROPRIETARY ~ Some Label Name
Scope: File, Email, Teamwork
Protection: Content Marking, Encryption
Auto labelling: Disabled
ContentType=(File, Email,Teamwork)
DisplayName=PROPRIETARY ~ Some Label Name
EncryptionContentExpiredOnDateInDaysOrNever=Never
EncryptionEnabled=True
EncryptionOfflineAccessDays=-1
EncryptionProtectionType=Template
EncryptionRightsDefinitions=Email@M365.onmicrosoft.com:VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EDITRIGHTSDATA,
EXPORT,OBJMODEL,OWNER;test.co.uk:VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL;test.co.uk:VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REP
LY,REPLYALL,FORWARD,OBJMODEL
Ensure=Absent
LocaleSettings=({localeKey=displayName; LabelSettings=MSFT_SCLabelSetting},{localeKey=tooltip; LabelSettings=MSFT_SCLabelSetting})
Name=LabelRef0406
ParentId=LabelRef0400
Priority=9
TenantId=***
Tooltip=Use this marking for.....
Verbose=True
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Target Values: AdvancedSettings=({Key=parentid;
 Value=22222222-2222-2222-2222-22222222},{Key=isparent; Value=False},{Key=color; Value=#FFFFFF})
ApplicationId=***
ApplyContentMarkingHeaderAlignment=Left
ApplyContentMarkingHeaderEnabled=True
ApplyContentMarkingHeaderFontColor=#000000
ApplyContentMarkingHeaderFontSize=10
ApplyContentMarkingHeaderMargin=5
ApplyContentMarkingHeaderText=ACME CONTROLLED\PROPRIETARY ~ Some Label Name
CertificateThumbprint=***
Comment=Label Name:LabelRef0406
Display Name: PROPRIETARY ~ Some Label Name
Scope: File, Email, Teamwork
Protection: Content Marking, Encryption
Auto labelling: Disabled
ContentType=(File, Email,Teamwork)
DisplayName=PROPRIETARY ~ Some Label Name
EncryptionContentExpiredOnDateInDaysOrNever=Never
EncryptionEnabled=True
EncryptionOfflineAccessDays=-1
EncryptionProtectionType=Template
EncryptionRightsDefinitions=Email@M365.onmicrosoft.com:VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EDITRIGHTSDATA,
EXPORT,OBJMODEL,OWNER;dev.co.uk:VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL;test.co.uk:VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REP
LY,REPLYALL,FORWARD,OBJMODEL
Ensure=Present
LocaleSettings=({localeKey=displayName; LabelSettings=MSFT_SCLabelSetting},{localeKey=tooltip; LabelSettings=MSFT_SCLabelSetting})
Name=LabelRef0406
ParentId=LabelRef0400
Priority=9
TenantId=***
Tooltip=Use this marking for information where the customer has stipulated be protected (e.g. within a bid or invitation to tender).
Verbose=True
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Testing AdvancedSettings
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Test AdvancedSettings returns True
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Testing LocaleSettings
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Test LocaleSettings returns True
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Test-TargetResource returned False
VERBOSE: [SomePC]: LCM:  [ End    Test     ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name]  in 1.4840 seconds.
VERBOSE: [SomePC]: LCM:  [ Start  Set      ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name]
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Setting configuration of Sensitivity label for 
LabelRef0406
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Getting configuration of Sensitivity Label for 
LabelRef0406
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Sensitivity label LabelRef0406 does not exist.
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Label {LabelRef0406} doesn't already exist, crea
ting it from the Set-TargetResource function.
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Creating Label {LabelRef0406}
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Returning precomputed version info: 3.4.0
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] POST with -1-byte payload
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Query 1 failed.
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Getting message from error object
|Microsoft.Exchange.Management.UnifiedPolicy.RmsException|An error occured in the Rms component: 'Your TenantId: '11111111-ad70-409c-95d4-11111111' is not found in 
Azure RMS. Please check your RMS license. If you have a valid license, please contact Microsoft support to resolve the issue.
'
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [TimeStamp=Wed, 31 Jan 2024 17:59:30 GMT],Write-ErrorMessage
    + PSComputerName        : localhost
 
VERBOSE: [SomePC]:                            [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name] Updating the priority for newly created label {
LabelRef0406}
|Microsoft.Exchange.Management.UnifiedPolicy.ErrorRuleNotFoundException|There is no rule matching identity 'LabelRef0406'.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : [TimeStamp=Wed, 31 Jan 2024 17:59:35 GMT],Write-ErrorMessage
    + PSComputerName        : localhost
 
VERBOSE: [SomePC]: LCM:  [ End    Set      ]  [[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name]  in 11.1110 seconds.
The PowerShell DSC resource '[SCSensitivityLabel]SCSensitivityLabel-PROPRIETARY ~ Some Label Name' with SourceInfo 
'D:\scripts\M365-Germany\SC.ps1::1831::9::SCSensitivityLabel' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors 
are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
```

### Environment Information + PowerShell Version

_No response_

### PR DESCRIPTION
**Pull request by tayhall**

### CODE REVIEW

**Comment by andikrueger** [comment]
Hi @tayhall,

thanks for your contribution. Could you please outline, what this PR will add to M365DSC? The current changes are duplicating existing elements in the validate set.

**Comment by tayhall** [comment]
> Hi @tayhall,
> 
> thanks for your contribution. Could you please outline, what this PR will add to M365DSC? The current changes are duplicating existing elements in the validate set.

The File and Email are currently linked in the validate set. I have added them separately. I wasnt 100% sure whether to leave the "File, Email" in as well as having the "File" and "Email" given that's the default used with new-label and how the current DSC exports populate the ContentType

**Comment by andikrueger** [comment]
Looks like the same applies to 'Site, UnifiedGroup' as well. This is the part of the documentation in this case.

https://learn.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps#-contenttype

Changing the validate set to exclude the previous values would be a breaking change - I'm not really sure, if this would really break a configration though as the values of the validate set are the same.
@NikCharlebois Could you have a look into this as well?

**Comment by tayhall** [comment]
> Looks like the same applies to 'Site, UnifiedGroup' as well. This is the part of the documentation in this case.
> 
> https://learn.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps#-contenttype
> 
> Changing the validate set to exclude the previous values would be a breaking change - I'm not really sure, if this would really break a configration though as the values of the validate set are the same. @NikCharlebois Could you have a look into this as well?

Reading the doc it says values can be combined. So all these are valid but obviously cannot be used with the way the validate set is specifying the second Params example. This is in line with the updates they made about a year ago to Sensitivity labels.

@Params {
ContentType = @("File","Email")
}
@Params {
ContentType = @("File,Email")
}
@Params {
ContentType = @("File")
}
@Params {
ContentType = @("Email")
}
New-Label @Params

Hopefully we can change without it being a breaking change

**Comment by tayhall** [comment]
> Looks like the same applies to 'Site, UnifiedGroup' as well. This is the part of the documentation in this case.
> 
> https://learn.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps#-contenttype
> 
> Changing the validate set to exclude the previous values would be a breaking change - I'm not really sure, if this would really break a configration though as the values of the validate set are the same. @NikCharlebois Could you have a look into this as well?

Hi, Any update on this was it decided to be a breaking change or was their an action on me?

**Comment by NikCharlebois** [comment]
@tayhall can you please ensure you updated your branch with the latest code (git merge), it appears that there are a few conflicts left. Thanks

**Pull request closed without merging**
