### PR TITLE
Update VSCode settings

### LINKED ISSUE #2326: Update to .vscode/settings.json - AvoidUsingDoubleQuotesForConstantString
There is a new setting for PowerShell Formatting available, that is not configured so far. This setting has big impact on the code formatting within this project. All strings are going to be transformed from strings with double quotes to strings single quotes. This transformation happens as soon as a user has different setting configured within its environment compared to the settings.json for VSCode within the project.

```powershell
"powershell.codeFormatting.useConstantStrings": true
```

Further description and discussion can be found there:

        Good point. Looks like we need to implement this change within the .vscode settings. This was introduced with V 1.19.1 and targets the PSScriptAnalyzer Rule: https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidusingdoublequotesforconstantstring?view=ps-modules

Prior to implementing this change, we need to consider the impact.

_Originally posted by @andikrueger in https://github.com/microsoft/Microsoft365DSC/issues/2306#issuecomment-1253765809_

### PR DESCRIPTION
**Pull request by ChaseKnowlden**
#### Pull Request (PR) description
Add a new setting to PowerShell formatting

#### This Pull Request (PR) fixes the following issues
Fixes #2326

### CODE REVIEW

**Comment by andikrueger** [comment]
Could you modify the code format for all files within this repo accordingly? Otherwise we would see this update having impact on every PR from now on.

**Comment by mlhickey** [comment]
Could this be amended to also incorporate a ScriptAnalyzer.psd1 update to exclude PSAvoidUsingWriteHost, or should that be a separate PR?

**Comment by andikrueger** [comment]
Just added a new comment to #2326. We should stick with Write-Host in any place we make use of output formatting. You could include the changes within this PR.

**Comment by mlhickey** [comment]
Not stepping on someone else's PR, separate PR - #2373

**Pull request closed without merging**
