### PR TITLE
Export error handling & backup

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Creates a temporary file as the export process is being executed so that if an error occurs, the user can still retrieve the components exported up to the failure point.

#### This Pull Request (PR) fixes the following issues
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs could you please do the code review on that one? Thanks

**Review by desmay — COMMENTED** [review]
> Reviewed 52 of 145 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237)* status: 52 of 145 files reviewed, all discussions resolved (waiting on @ykuijs)

**Review by ykuijs — CHANGES_REQUESTED** [review]
Few small comments

> Reviewed 91 of 145 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-:-MaccyOG9J_b9PC8v78b:b-ag9xuu)* status: 143 of 145 files reviewed, 3 unresolved discussions (waiting on @desmay and @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1, line 409 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-MacUxJ3ELBBe1qjpBBM:-MacUxJ3ELBBe1qjpBBN:bfyh7s8) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/8ed53edb153d88cf969d56595a9b9b8c4a1777bd/Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1#L409)):*
> ```PowerShell
>                 -Results $Results
>             $dscContent += Get-M365DSCExportContentForResource -ResourceName $ResourceName `
>                 currentDSCBlocktonMode $ConnectionMode `
> ```

This change doesn't look good. Is this Reviewable or a editing mistake
```
 currentDSCBlocktonMode $ConnectionMode `
```
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1, line 450 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-Mac_2722UR-ch6VGlor:-Mac_2732zXTAiV83udo:b-argn2e) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/8ed53edb153d88cf969d56595a9b9b8c4a1777bd/Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1#L450)):*
> ```PowerShell
> Export-ModuleMember -Function *-TargetResource
> ```

Two empty lines at the bottom
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpgradePolicy/MSFT_TeamsUpgradePolicy.psm1, line 229 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-MaccVE2ELve7fHj0LLF:-MaccVE2ELve7fHj0LLG:bztzvn) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/8ed53edb153d88cf969d56595a9b9b8c4a1777bd/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpgradePolicy/MSFT_TeamsUpgradePolicy.psm1#L229)):*
> ```PowerShell
>             $currentDSCBlock = "        TeamsUpgradePolicy " + (New-Guid).ToString() + "`r`n"
>             $currentDSCBlock += "        {`r`n"
>             $currentDSCBlock2 = Get-DSCBlock -Params $result -ModulePath $PSScriptRoot
> ```

Would a more descriptive variable name be better? What is the difference between currentDSCBlock and currentDSCBlock2?

**Review by NikCharlebois — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237)* status: 143 of 145 files reviewed, 3 unresolved discussions (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1, line 409 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-MacUxJ3ELBBe1qjpBBM:-Mach9-K210iJnQXRidT:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/8ed53edb153d88cf969d56595a9b9b8c4a1777bd/Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1#L409)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

This change doesn't look good. Is this Reviewable or a editing mistake
```
 currentDSCBlocktonMode $ConnectionMode `
```
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1, line 450 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-Mac_2722UR-ch6VGlor:-MachBd-9-WnxKc9LNc-:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/8ed53edb153d88cf969d56595a9b9b8c4a1777bd/Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.psm1#L450)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Two empty lines at the bottom
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpgradePolicy/MSFT_TeamsUpgradePolicy.psm1, line 229 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-MaccVE2ELve7fHj0LLF:-MachLWH1s16pG-DI5Zv:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/8ed53edb153d88cf969d56595a9b9b8c4a1777bd/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpgradePolicy/MSFT_TeamsUpgradePolicy.psm1#L229)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Would a more descriptive variable name be better? What is the difference between currentDSCBlock and currentDSCBlock2?
</blockquote></details>

Done.

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1237#-:-MadDO774rzKbwKa32VR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
