### PR TITLE
Assert-M365DSCBlueprint: Fixes the report not showing metadata

### LINKED ISSUE #2104: Assert-M365DSCBlueprint: Reporting not displaying metadata
#### Details of the scenario you tried and the problem that is occurring
I have a Blueprint that I am trying to run against a tenant.  I can successfully run it and it identifies the correct deltas, but it is not picking up the reporting metadata, as in it is missing the "### L1|Message" and therefore not printing it in the output HTML report.

Through debugging I have been able to conclude it is because the detail for the $IncludeComments in ConvertTo-DSCObject  is $false and therefore the calls from within the Reporting Module for Microsoft365DSC needs to pass the parameter of $ture for $IncludeComments.

I am happy to complete the change and raise a PR for this.
#### Verbose logs showing the problem
NA
#### Suggested solution to the issue
ConvertTo-DSCObject -Content $fileContent needs to change to ConvertTo-DSCObject -Content $fileContent -IncludeComments $true

I can currently see five instances in the M365DSCReport.psm1 module but am not convinced all of them need to be changed.  At least [Array] $DestinationObject = ConvertTo-DSCObject -Content $FileContent on line 485 of version 1.22.713.1 needs to change but potentially the other four need to as well.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell 
Assert-M365DSCBlueprint -BluePrintUrl $fileLocation -OutputReportPath "C;\temp\report.html" -Credentials $credentials

# insert configuration here
Blueprint as follows:
        AADNamedLocationPolicy 3d3322be-9f3c-4b68-b741-2f070cfbf727 {
            Credential  = $Credscredential;
            DisplayName = "My Named Location";
            Ensure      = "Present";
            IpRanges    = "x.x.x.x/32"; ### L1|You should have the IP access restriction here.
            IsTrusted   = $True;
            OdataType   = "#microsoft.graph.ipNamedLocation";
        }
```
#### The operating system the target node is running
NA
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.713.1

### PR DESCRIPTION
**Pull request by mpiederiet**
#### Pull Request (PR) description
This PR fixed the Assert-M365DSCBlueprint not showing metadata in the report

#### This Pull Request (PR) fixes the following issues
Fixes #2104

### CODE REVIEW

**Review by NikCharlebois — APPROVED** [review]
LGTM

**Comment by andikrueger** [comment]
Currently. we are facing issues with the publishing the module to PSGallery. Your change is included in V 1.22.727.1. 

https://github.com/microsoft/Microsoft365DSC/blob/6626905888c155a7e69748e797be3303a2fa12bc/Modules/Microsoft365DSC/Modules/M365DSCReport.psm1#L873-L887


You can download the V1.22.727.1 from here: https://github.com/microsoft/Microsoft365DSC/releases/tag/1.22.727.1

**Comment by mpiederiet** [comment]
Thanks @andikrueger for your answer. How did you find that commit in the 1.22.727.1 build? Because if I'm looking at the 1.22.727.1 tag https://github.com/microsoft/Microsoft365DSC/commits/1.22.727.1 I only see commits until the 20th of July, which is why I was wondering why my fix was not there... So I guess my question in general would be: how do I know which commits are included in which build?

**Comment by andikrueger** [comment]
It was included in this PR https://github.com/microsoft/Microsoft365DSC/pull/2144 and therefor was merged into the master branch. 

Your PR did not include any updates to the changelog. This makes it harder to track the change. Usually I track the release by using this query: https://github.com/microsoft/Microsoft365DSC/pulls?q=is%3Apr+is%3Aclosed+release

**Comment by mpiederiet** [comment]
Hi @andikrueger, unfortunately the link you sent for the 1.22.727.1 release also contained the "old" 1.22.720.1 files (version 1.22.720.1 is in the .psd1 file), which might have been the reason why the upload to the gallery failed (version conflict?).

Anyway, we've downloaded the code from the Dev branch which we know has the fix included and confirmed that works, so we are now eagerly awaiting the next successful uploaded version to the PS gallery so our pipeline will generate the blueprint reports successfully. Thanks again!

**Comment by andikrueger** [comment]
Thanks for this hint. It really is the wrong version within the package..

Glad you were able to get it running with the dev branch version.

**Pull request merged**
