### PR TITLE
Adds biometric access requirements in "IntuneAppProtectionPolicyAndroid"

### LINKED ISSUE #3642: IntuneAppProtectionPolicyAndroid: Add class 3 biometrics setting
### Description of the issue

Within Android MAM, it's possible to require Class 3 biometrics, with the option to override with PIN if there is a change in the biometrics. These two settings (`requireClass3Biometrics` and `requirePinAfterBiometricChange`) 

It's probably something that needs to be changed in this file: Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAppProtectionPolicyAndroid/MSFT_IntuneAppProtectionPolicyAndroid.psm1

The function that is being used to deploy the MAM policy( *-MgBetaDeviceAppManagementAndroidManagedAppProtection) has parameters to configure the settings in the MAM policy (`[-RequireClass3Biometrics]` `[-RequirePinAfterBiometricChange]`).

### Microsoft 365 DSC Version

1.23.830.1

### Which workloads are affected

other

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### PR DESCRIPTION
**Pull request by jeffreycloudlife**
#### Pull Request (PR) description
Added parameters to the resource "IntuneAppProtectionPolicyAndroid" to add Biometrics parameters, including documentation and test files.

#### This Pull Request (PR) fixes the following issues
- Fixes #3642

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Please accept the agreement.

**Comment by jeffreycloudlife** [comment]
@microsoft-github-policy-service agree company="Cloud Life"

**Comment by jeffreycloudlife** [comment]
Had to check internally, but it's all good now! :)

**Comment by NikCharlebois** [comment]
Thanks for the contribution, may I also ask you to add an entry in the Changelog under the UNRELEASED section please? I will merge after, thanks.

**Comment by ykuijs** [comment]
@jeffreycloudlife, for future reference: You don't need to update the pages in the docs folder.....we are generating them based on the actual code. So all your changes will be overwritten anyways :wink:

**Comment by jeffreycloudlife** [comment]
> Thanks for the contribution, may I also ask you to add an entry in the Changelog under the UNRELEASED section please? I will merge after, thanks.

Done!

**Review by ykuijs — APPROVED** [review]
LGTM

**Pull request merged**
