### PR TITLE
TeamChannel & TeamUser - Fix for Teams with special characters in their name

### LINKED ISSUE #1579: Teams: TeamNames that are part of other names -> Not all attributes in DSC-Block
#### Details of the scenario you tried and the problem that is occurring
If you have a teamsname like "IT" and another with e.g. "IT-Infrastruktur", you find errors in the logfile.

#### Verbose logs showing the problem
Same message for each channel. Here only for one channel
```
    |---[22/38] Team {IT}
        |---[1/5] Abwesenheiten
VERBOSE: Attempting connection to {MicrosoftTeams} with:
VERBOSE: 
Name                           Value                                                                                   
----                           -----                                                                                   
DisplayName                    Abwesenheiten                                                                           
Credential                     System.Management.Automation.PSCredential                                               
TeamName                       IT
VERBOSE: Credential was specified. Connecting via User Principal
VERBOSE: Done performing authorization
VERBOSE: Executing Get-Team for parameters GroupId: , User: , Archived: , Visibility: , DisplayName: IT, MailNickName:
VERBOSE: Attempting to retrieve team from indexes [0 to 3]
VERBOSE: Retrieving groups list
VERBOSE: Done retrieving groups, getting team properties
VERBOSE: Done processing Get-Team
PS>TerminatingError(Get-TeamChannel): "Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'GroupId'. Specified method is not supported."
✅
```
#### Suggested solution to the issue
check coding (sorry no better idea)
```
Get-Team -displayname IT can give more than one resultobject (looks like wildcardsearching *IT*)

PS C:\> get-team -displayname IT | select GroupId,DisplayName

GroupId                              DisplayName
-------                              -----------
b429b63e-83fe-43a4-9773-0aa42f85ab29 IT
c0236ba1-1d2c-4f01-a39b-3c3deeb3f325 IT-Infra...
37b235e9-4665-4c76-806e-d03ef04ec068 IT-Supp...
cf61904d-f8e2-4970-8daf-70918c6b6934 IT-Int...
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
DSC-Config is written, only missing NewDisplayName and Description.
```
        TeamsChannel 18abc9b6-0afc-4316-8536-4945e89b2f73
        {
            Credential           = $Credscredential;
            DisplayName          = "Abwesenheiten";
            Ensure               = "Absent";
            TeamName             = "IT";
        }
        TeamsChannel f91e3ee0-82ed-4bb3-a68a-5284c24b9227
        {
            Credential           = $Credscredential;
            DisplayName          = "Interne Ankündigungen";
            Ensure               = "Absent";
            TeamName             = "IT";
        }
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.4770.amd64fre.rs1_release.211101-1440
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```Name            Version
----            -------
microsoft365dsc 1.21.1117.2
```

### PR DESCRIPTION
**Pull request by andikrueger**
#### Pull Request (PR) description
This PR fixes an issue mentioned in #1579 with Teams with special characters. These need to be encoded to not fail within the function.

This issue was partially fixed with #1658.

#### This Pull Request (PR) fixes the following issues
- Fixes #1579

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Not sure why the unit tests are failing, but can you please make sure you update your PR with the latest code? Thanks

**Comment by andikrueger** [comment]
Hope I fetched the latest changes into my branch. Currently it is failing with

```
Import-Module : The specified module 'PnP.PowerShell' was not loaded because no valid module file was found in any 
```

**Comment by andikrueger** [comment]
image

**Comment by NikCharlebois** [comment]
Ok, I believe I found the issue. Can you update your PR again and retry? Thanks

**Comment by andikrueger** [comment]
Looks like the unit tests passed. Thanks for the fix!

**Pull request merged**
