### PR TITLE
Minor fixes in MSFT_EXOClientAccessRule.psm1 and MSFT_EXOAuthenticationPolicyAssignment.psm1

### PR DESCRIPTION
**Pull request by kasaxena5**
#### Pull Request (PR) description
Added $Confirm:false flags in Set-TargetResource

### CODE REVIEW

**Comment by ykuijs** [comment]
Hi @kasaxena5 can you please add a description of this change to the Unreleased section of the changelog? That way we can track all changes that are implemented in a specific version.

**Comment by ricmestre** [comment]
Just want to ping about #4894, CAR has been deprecated on new tenants 2 years ago and customers are advised to use CAE instead, not sure why MS still didn't remove the feature completely.

**Comment by kasaxena5** [comment]
Added Change Logs

**Comment by kasaxena5** [comment]
> Just want to ping about #4894, CAR has been deprecated on new tenants 2 years ago and customers are advised to use CAE instead, not sure why MS still didn't remove the feature completely.

Not sure on this.

**Pull request merged**
