### PR TITLE
AADUser: Add support for MemberOf

### LINKED ISSUE #3820: AADUser: Add support for MemberOf
### Description of the issue

With things like group-based licensing etc, I'd like to be able to ensure that a user is a member of one or more groups.
While I realize that this is not feasible for ordinary users because group-membership can and will vary wildly, I would like to ensure that certain accounts exist and are properly licensed by having them added to one or more groups.
I've already added the code to my local copy of the repo and have a valid unit-test on hand, so I'm ready to do a PR

### Microsoft 365 DSC Version

DEV

### Which workloads are affected

Azure Active Directory

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### PR DESCRIPTION
**Pull request by salbeck-sit**
#### Pull Request (PR) description
AADUser: Adds support for property MemberOf

#### This Pull Request (PR) fixes the following issues
Fixes #3820

### CODE REVIEW

**Comment by salbeck-sit** [comment]
Basically it's a matter of choice. We're mostly using group-based licensing and recently I've begun preparing for 'pre-staging' resource-accounts for Teams Rooms and here I want to ensure that the account is made a member of the security-group that provides the correct license *without* at the same time maintaining a list of which accounts are members of the specific group.

Perhaps the examples should be clear in that regard, for instance by saying that use of AADUSer.MemberOf may collide with use of AADGroup.Member - something that the examples for AADGroup should also mention.
I've updated the readme for AADUser and AAGroup to explain the potential conflict

**Comment by salbeck-sit** [comment]
I've updated the changelog but now there's a conflict that I just can't see.

**Comment by salbeck-sit** [comment]
Phew. Some ugly trial-error rebasing seems to have solved the issue

**Comment by salbeck-sit** [comment]
PS You have the same 'conflict' within AADGroup where it's possible to specify Members *AND* MemberOf. When a group that is included elsewhere in another Group's MemberOf is configured with Members and the list doesn't contain that group - what then?
The same issue has existed for ages in dear old Group Policy Restricted Groups where you also find both Member and MemberOf, they also happily trip each other up.

My take is that if you want to control total membership of a group you use AADGroup -> Members.
If, on the other hand, you want to ensure (sic) membership of some group without wanting to control that group's membership, then use AADGroup -> MemberOf or AADUser -> MemberOf

**Comment by salbeck-sit** [comment]
PS I haven't updated the changelog - yet. When you're ready to approve, let me know and I'll include it in the PR

**Comment by salbeck-sit** [comment]
Ah. I accidentally closed the PR. That wasn't my intention

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
