### PR TITLE
M365 data at rest encryption policy assignment

### PR DESCRIPTION
**Pull request by kasaxena5**
#### Pull Request (PR) description
M365 data at rest encryption policy assignment

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Please resolve conflicts and prefix the resource name with EXO

**Comment by kasaxena5** [comment]
> Please resolve conflicts and prefix the resource name with EXO

Resolved and changed the prefix

**Review by NikCharlebois — APPROVED** [review]

**Comment by salbeck-sit** [comment]
Prefix is now EXOM365 - it should be just EXO. Please remove M365 from the resource-name

**Comment by FabienTschanz** [comment]
There is now an additional directory `MSFT_EXOM365DataAtRestEncryptionPolicy` available... This must be checked asap.

**Pull request merged**
