### PR TITLE
EXOAuthenticationPolicy: Recreate policy instead of changing it

### LINKED ISSUE #4819: EXOAuthenticationPolicy: Cannot change resources
### Description of the issue

After creating the policy it's not possible to change it, this is because ```Set-AuthenticationPolicy``` doesn't work and always fails with error message ```Object reference not set to an instance of an object```, the solution is to just remove the current policy and re-create it with the new settings.

### Microsoft 365 DSC Version

1.24.626.1

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
EXOAuthenticationPolicy "EXOAuthenticationPolicy-EXOAuthenticationPolicy_1"
        {
            AllowBasicAuthActiveSync           = $False;
            AllowBasicAuthAutodiscover         = $False;
            AllowBasicAuthImap                 = $False;
            AllowBasicAuthMapi                 = $False;
            AllowBasicAuthOfflineAddressBook   = $False;
            AllowBasicAuthOutlookService       = $False;
            AllowBasicAuthPop                  = $False;
            AllowBasicAuthPowerShell           = $False;
            AllowBasicAuthReportingWebServices = $False;
            AllowBasicAuthRpc                  = $False;
            AllowBasicAuthSmtp                 = $False;
            AllowBasicAuthWebServices          = $False;
            Credential                         = $CredsCredential;
            Ensure                             = "Present";
            Identity                           = "EXOAuthenticationPolicy_1";
        }
```

### Verbose logs showing the problem

```powershell
Object reference not set to an instance of an object
```

### Environment Information + PowerShell Version

```powershell
Win11/PS5.1
```

### PR DESCRIPTION
**Pull request by ricmestre**
#### Pull Request (PR) description

Unfortunately trying to change any existing ```EXOAuthenticationPolicy``` fails with the error message below, this is a problem in cmdlet ````Set-AuthenticationPolicy``` and the way to fix this is to just remove the current policy and recreate it with the new settings.

```Object reference not set to an instance of an object.```

#### This Pull Request (PR) fixes the following issues

- Fixes #4819

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Looping in PG folks responsible for the cmdlet.

//cc @Swatyario for visibility

**Comment by ricmestre** [comment]
By the way, other people already reported this issue, see https://techcommunity.microsoft.com/t5/windows-powershell/exchange-online-error-write-errormessage-object-reference-not/m-p/4127852

**Comment by NikCharlebois** [comment]
PG is aware of the issue and has it on their backlog. I recommend parking this until it's fixed since deleting and recreating will generate unnecessary entries in the audits.

**Comment by ricmestre** [comment]
Sure, just note that there are other EXO resources where this is also done, not sure if the Set cmdlets have issues or if don't exist though. I'll exclude this resource on our tool for now on deployments.

**Comment by FabienTschanz** [comment]
@NikCharlebois Any news on the situation? Is the PG still working on it or does it work now?

**Comment by NikCharlebois** [comment]
Haven't heard any updates from the team. Will go ahead and merge your proposed PR and will continue to track PG's response.

**Comment by ricmestre** [comment]
OK it's not the best solution but at least works, let me check the conflict and I'll update the branch

EDIT: You were faster than me thank you for checking the conflict :)

**Pull request merged**
