### PR TITLE
Aad role definition

### PR DESCRIPTION
**Pull request by ThorstenLoeschmann**
#### This Pull Request (PR) fixes the following issues

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/919)

### CODE REVIEW

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Few items

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-:-MM_eLCE0T3-jbzzjfBU:baiewfn)* status: all files reviewed, 11 unresolved discussions (waiting on @ThorstenLoeschmann)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 25 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dZny59PZ1n55RgMA:-MM_dZny59PZ1n55RgMB:bdz81yw) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L25)):*
> ```PowerShell
>         [Parameter()]
>         [System.Boolean]
>         $IsEnabled,
> ```

I believe this should be mandatory based on:
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsroledefinition?view=azureadps-2.0-preview
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 29 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dYCW32SSTREo8zTg:-MM_dYCW32SSTREo8zTh:b-gylz01) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L29)):*
> ```PowerShell
>         [Parameter()]
>         [System.String[]]
>         $RolePermissions,
> ```

I believe this should be mandatory
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 61 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_d1181MzPEoNc5-Hv:-MM_d1181MzPEoNc5-Hw:b-z3qt20) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L61)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message "Getting configuration of Azure AD Application"
> ```

Should be role definition
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 223 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dNuL1UsEjkIK6kn8:-MM_dNuL1UsEjkIK6kn9:b-tgrx48) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L223)):*
> ```PowerShell
>         New-AzureADMSRoleDefinition @currentParameters
>     }
>     # App should exist and will be configured to desired state
> ```

Role Definition
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 230 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dPOh7Nd4rO-bQdw3:-MM_dPOh7Nd4rO-bQdw4:b-tgrx48) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L230)):*
> ```PowerShell
>         Set-AzureADMSRoleDefinition @currentParameters
>     }
>     # App exists but should not
> ```

Role Definition
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 370 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dnBs0_BcspeS-gTQ:-MM_dnBs0_BcspeS-gTR:b-5r3282) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L370)):*
> ```PowerShell
>     try
>     {
>         $AADRoleDefinitions = Get-AzureADMSRoleDefinition -ErrorAction Stop
> ```

cast as an Array:
[array]$AADRoleDefinitions = ...
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 408 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_duqMDMgq1AQ_al-i:-MM_duqMDMgq1AQ_al-j:b-jbo9ws) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L408)):*
> ```PowerShell
> }
> 
> Export-ModuleMember -Function *-TargetResource
> ```

Add empty line at the end
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.schema.mof, line 12 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dz268Vj0IK-Zfv-O:-MM_dz268Vj0IK-Zfv-P:b-9ikv90) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.schema.mof#L12)):*
> ```
>     [Write, Description("Specifies template id for the role definition.")] String TemplateId;
>     [Write, Description("Specifies version for the role definition.")] String Version;
>     [Write, Description("Specify if the Azure AD App should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
> ```

Role Definition not app
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md, line 7 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_e3dx2gj3Sd7oiR7j:-MM_e3dx2gj3Sd7oiR7k:bvmcnlj) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md#L7)):*
> ```Markdown
> This resource configures an Azure Active Directory role definition.
> To configure custom roles you require an Azure AD Premium P1 license.
> The account used to configure role definitions based on this resource needs either to be a "Global Administrator" or a "Privileged role administrator".
> ```

Break line on two. This is a limitation of the wiki pages being generated from this file where lines can't be that long.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md, line 20 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_eA1X-s_4vB6odBsN:-MM_eA1X-s_4vB6odBsO:b-9tpqlx) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md#L20)):*
> ```Markdown
>   * Directory.Read.All
> 
> NOTE: All permisions listed above require admin consent.
> ```

add empty line
___
*[Tests/Unit/Stubs/Microsoft365.psm1, line 0 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_eHRKCsZ27wUk735K:-MM_eHRKCsZ27wUk735L:brslmtc) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Tests/Unit/Stubs/Microsoft365.psm1#L0)):*
What did you change in that file? This file should never be touched.

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/919)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @NikCharlebois and @ThorstenLoeschmann)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 262 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_rDLw2Sk4te5lv1XG:-MM_rDLw2Sk4te5lv1XH:b-d5zl1r) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b58bbee50cbb6ed376e385ba3a5be97c1c984a87/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L262)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.Boolean]
>         $IsEnabled,
> ```

You will need to mark these as Required instead of Write in the .schema.mof file as well

**Comment by ThorstenLoeschmann** [comment]
___
*[Tests/Unit/Stubs/Microsoft365.psm1, line  at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_eHRKCsZ27wUk735K:-MM_wNQk2p3fEXkOTV6i:b-qifhul) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Tests/Unit/Stubs/Microsoft365.psm1#L)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

What did you change in that file? This file should never be touched.
</blockquote></details>

what we did discuss before. Changing the parameter type to System.String[]

**Review by ThorstenLoeschmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/919)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 25 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dZny59PZ1n55RgMA:-MM_vv4a9c0W9_LSv4-H:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L25)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I believe this should be mandatory based on:
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsroledefinition?view=azureadps-2.0-preview
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 29 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dYCW32SSTREo8zTg:-MM_vvdH4aTd2KPdQ55A:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L29)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I believe this should be mandatory
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 61 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_d1181MzPEoNc5-Hv:-MM_vwcwBS8NJ36lvJsq:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L61)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Should be role definition
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 223 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dNuL1UsEjkIK6kn8:-MM_vy3X7MLp52bbw7rF:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L223)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Role Definition
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 230 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dPOh7Nd4rO-bQdw3:-MM_vzAOBhykpSWRmFu4:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L230)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Role Definition
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 370 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dnBs0_BcspeS-gTQ:-MM_w0rw1A128c1TnJfM:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L370)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

cast as an Array:
[array]$AADRoleDefinitions = ...
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 408 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_duqMDMgq1AQ_al-i:-MM_w2mo52dd41kg5CC2:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L408)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Add empty line at the end
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1, line 262 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_rDLw2Sk4te5lv1XG:-MM_w-MHBeN4OJM4fLGJ:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b58bbee50cbb6ed376e385ba3a5be97c1c984a87/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.psm1#L262)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

You will need to mark these as Required instead of Write in the .schema.mof file as well
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.schema.mof, line 12 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_dz268Vj0IK-Zfv-O:-MM_w3KQ4UaGlohiehxd:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/MSFT_AADRoleDefinition.schema.mof#L12)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Role Definition not app
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md, line 7 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_e3dx2gj3Sd7oiR7j:-MM_w6he9TKBGeG5EwFZ:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md#L7)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Break line on two. This is a limitation of the wiki pages being generated from this file where lines can't be that long.
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md, line 20 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-MM_eA1X-s_4vB6odBsN:-MM_w7ZfCfnk41f0m0Y2:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ef577fe98e89fa5ea44028489fdd1ecdb2268d5f/Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleDefinition/readme.md#L20)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

add empty line
</blockquote></details>

Done.

**Review by NikCharlebois — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/919#-:-MM_xIAb4GbDoU3MemUV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ThorstenLoeschmann)

**Pull request merged**
