### PR TITLE
Fix issue with ExcludedFileExtensions on ODSettings

### PR DESCRIPTION
**Pull request by desmay**
#### Pull Request (PR) description
 Fixed issue with ExcludedFileExtensions

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1110)

### CODE REVIEW

**Review by ykuijs — CHANGES_REQUESTED** [review]
One question about the implemented change

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1110#-:-MWAzOAT4Uspjlk-jgPo:bn2b3yj)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @desmay and @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_ODSettings/MSFT_ODSettings.psm1, line 377 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1110#-MWAzG2dAnOzOYjmcVEq:-MWAzG2dAnOzOYjmcVEr:bryltc3) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/1ea37be6503b5bf2c75a390bc530e2125d38e697/Modules/Microsoft365DSC/DSCResources/MSFT_ODSettings/MSFT_ODSettings.psm1#L377)):*
> ```PowerShell
>     Write-Verbose -Message ($Options | Out-String)
> 
>     if ($Options.ContainsKey("ExcludedFileExtensions"))
> ```

Why are you removing this parameter?

**Review by desmay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1110)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois and @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_ODSettings/MSFT_ODSettings.psm1, line 377 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1110#-MWAzG2dAnOzOYjmcVEq:-MWB0S-66OrlGCWVBmpT:b-ld5rxk) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/1ea37be6503b5bf2c75a390bc530e2125d38e697/Modules/Microsoft365DSC/DSCResources/MSFT_ODSettings/MSFT_ODSettings.psm1#L377)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Why are you removing this parameter?
</blockquote></details>

Its added above, I think was some leftover code when we converted from SPO to PNP

    if ($CurrentParameters.ContainsKey("ExcludedFileExtensions"))
    {
        $Options.Add("ExcludedFileExtensions", $CurrentParameters.ExcludedFileExtensions)
        $CurrentParameters.Remove("ExcludedFileExtensions") | Out-Null
    }

**Review by desmay — COMMENTED** [review]
The logic existed above this code, I think was left over from conversion from SPO > PNP 

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1110#-:-MWB0lHyAjsz24G4pkG0:b-kbtzj)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois and @ykuijs)

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1110#-:-MWB1Pzb3Ka2zW-i3GyY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
