### PR TITLE
fix: Remove Close-sessionsandreturnError

### LINKED ISSUE #2588: EXOSafeAttachmentRule & EXOSafeLinksPolicy : uses function that does not exist (Close-SessionsAndReturnError in catch)
#### Details of the scenario you tried and the problem that is occurring
The resources EXOSafeAttachmentRule & ExoSafelinkPolicy call function Close-SessionsAndReturnError in some catch blocks.
The function Close-SessionsAndReturnError however is no longer existing. Thus, there is no meaningfull error message logged in case of an error...

e.g.         
try
        {
            $SafeAttachmentRules = Get-SafeAttachmentRule -ErrorAction Stop
        }
        catch
        {
            Close-SessionsAndReturnError -ExceptionMessage $_.Exception
            $Message = 'Error calling {Get-SafeAttachmentRule}'
            New-M365DSCLogEntry -Error $_ -Message $Message -Source $MyInvocation.MyCommand.ModuleName
        }

#### Verbose logs showing the problem
The term 'Close-SessionsAndReturnError' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
#### Suggested solution to the issue
Remove Close-SessionsAndReturnError in the catch blocks

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $credential,
    [System.Management.Automation.PSCredential]
    $PSDSCcred
)

Configuration EXOSafeLinksPolicyAndRule
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential,
        [System.Management.Automation.PSCredential]
        $PSDSCcred
    )

    $OrganizationName = $cd.NonNodeData.OrganizationName
    $TenantId = $cd.NonNodeData.TenantId
    Import-DscResource -ModuleName 'Microsoft365DSC' 

    Node localhost
    {
        EXOSafeLinksPolicy "Safe Link Policy" 
        {
            AdminDisplayName           = "";
            CustomNotificationText     = "";
            DeliverMessageAfterScan    = $True;
            DoNotRewriteUrls           = @();
            EnableForInternalSenders   = $True;
            EnableOrganizationBranding = $False;
            EnableSafeLinksForTeams    = $True;
            Ensure                     = "Present";
            Identity                   = "Safe Links Baseline Policy";
            ScanUrls                   = $True;
            ApplicationId              = $Cd.NonNodeData.ApplicationId;
            CertificateThumbprint      = $Cd.NonNodeData.CertificateThumbprint;
            TenantId                   = $TenantId;
            PsDscRunAsCredential       = $PSDSCcred
        }
    }
}```

#### The operating system the target node is running
<!--
    
-->

#### Version of the DSC module that was used ('dev' if using current dev branch)
 1.22.1109.1

### PR DESCRIPTION
**Pull request by mibarm**

### CODE REVIEW

**Comment by mibarm** [comment]
@microsoft-github-policy-service agree [company="Swisscom"]

**Comment by mibarm** [comment]
@microsoft-github-policy-service agree company=Swisscom

**Comment by mibarm** [comment]
@NikCharlebois Hi Nik, not sure if you saw my first pull request or if you need any further information?
Many thanks

**Comment by andikrueger** [comment]
Could you create a helper method to reduce the code douplication? I would start the workflows afterwards.

**Comment by NikCharlebois** [comment]
@mibarm thanks for contributing! As Andi suggest, let's simply wrap all these calls into a function and I'll merge the PR after. Thanks

**Comment by mibarm** [comment]
Hi @andikrueger, @NikCharlebois 
as suggested, created a function. Not sure if the name of the function is okey or if you want a different naming.
Also regarding location in M365DSCUtil.psm1?
Let me know if you have any suggestions.
Also, this replaced code is used in many functions, would probaly make sense to change that on all the resources (separate pull request)
Thanks alot
Cheers
Michael

**Comment by andikrueger** [comment]
Could you have a look at this PR: https://github.com/microsoft/Microsoft365DSC/pull/2596

It feels like @ykuijs did make this change obsolete. If not, how do they differ?

**Comment by mibarm** [comment]
@andikrueger goes in the right direction yes, but "Close-SessionsAndReturnError" is still called first in the catch blocks in EXOSafeAttachmentRule, EXOSafeLinkPolicy and M365DSCUtil.psm before getting to the "New-M365DSCLogEntry" from @ykuijs. So it could still fail (because function Close-SessionsAndReturnErrors does not exist anymore)

**Comment by andikrueger** [comment]
@mibarm Thanks for the clarification. 

Could you please resolve the conflicts of this branch.

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
