### PR TITLE
TeamsTeam: Skip teams without displayname during export

### LINKED ISSUE #4406: TeamsTeam: ParameterBindingValidationException: Cannot validate argument on parameter 'DisplayName'. The character length (0) of the argument is too short. Specify an argument with a length that is greater than or equal to "1", and then try the command again.
### Description of the issue

It appears I have a Team with a blank/empty DisplayName which is causing the export to fail.

![TeamsTeam](https://github.com/microsoft/Microsoft365DSC/assets/141027342/deac85c9-e19e-4053-af81-98fea7eb4e4b)

`[2024/03/05 04:22:27]
{InvalidData}
System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'DisplayName'. The character length (0) of the argument is too short. Specify an argument with a length that is greater than or equal to "1", and then try the command again. ---> System.Management.Automation.ValidationMetadataException: The character length (0) of the argument is too short. Specify an argument with a length that is greater than or equal to "1", and then try the command again.
   at System.Management.Automation.ValidateLengthAttribute.ValidateElement(Object element)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.228.1\DSCResources\MSFT_TeamsTeam\MSFT_TeamsTeam.psm1: line 727
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.228.1\Modules\M365DSCReverse.psm1: line 649
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.228.1\Modules\M365DSCUtil.psm1: line 1357
at <ScriptBlock>, <No file>: line 6`

### Microsoft 365 DSC Version

1.24.228.1

### Which workloads are affected

Teams

### The DSC configuration

```powershell
Export-M365DSCConfiguration -Components @("TeamsTeam") -Credential $Credential -Path $FilePath -FileName $FileName -Verbose -Debug
```


### Verbose logs showing the problem

```powershell
VERBOSE: Dependencies were already successfully validated.
VERBOSE: Credential was specified. Connecting via User Principal
VERBOSE: Dependencies were already successfully validated.
✅
    |---[720/1764] @@@DATA@@@VERBOSE: Attempting connection to {MicrosoftTeams} with:
VERBOSE: 
Name                           Value                                                                                                                                                                                                                                           
----                           -----                                                                                                                                                                                                                                           
TenantId                                                                                                                                                                                                                                                                       
ManagedIdentity                False                                                                                                                                                                                                                                           
DisplayName                    @@@DATA@@@
GroupID                        @@@GUID@@@
Credential                     System.Management.Automation.PSCredential                                                                                                                                                                                                       
ApplicationId                                                                                                                                                                                                                                                                  
CertificateThumbprint                                                                                                                                                                                                                                                          



VERBOSE: Dependencies were already successfully validated.
VERBOSE: Credential was specified. Connecting via User Principal
VERBOSE: Dependencies were already successfully validated.
✅
    |---[721/1764] ❌
 Error Log created at {file://C:/temp/scott/debug/cwd/9724-M365DSC-ErrorLog.log}
⌛ Export took {1024 seconds}
Transcript stopped, output file is C:\temp\scott\debug\log\TeamsTeam.txt
```


### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.17763.5458
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.17763.5458
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### PR DESCRIPTION
**Pull request by malauter**
#### Pull Request (PR) description
Skip teams without displayname during export (orphaned/deleted Teams) because the Get method cannot be called without a display name.
Please see discussion in linked issue.

#### This Pull Request (PR) fixes the following issues
- Fixes #4406

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Would it be an option instead to first check if we can retrieve the Teams by DisplayName, and if we can't default back to retrieving it by GroupID? I believe there is still value in retrieving orphan Teams, at least to flag it to the user that some cleanup might be required.

**Comment by malauter** [comment]
During creation of a new team, the display name is mandatory. This is why the displayName parameter in the get method is set to mandatory and we cannot call the Get-TargetResource without a display name. Even if we could call it, we cannot re-import a team without display name. Maybe we should throw a warning in the export method if we find a time without display name?

**Comment by malauter** [comment]
So, _Get-Team_ returns the group without the display name and _Get-Team -GroupID xxx_ returns the group with display name?
Do you have a test environment to verify this? Cannot reproduce it in my lab.

**Comment by NikCharlebois** [comment]
> So, _Get-Team_ returns the group without the display name and _Get-Team -GroupID xxx_ returns the group with display name? Do you have a test environment to verify this? Cannot reproduce it in my lab.

Sorry I misunderstood the scenario here. Merging PR.

**Pull request merged**
