### PR TITLE
IntuneDeviceConfigurationWindows

### PR DESCRIPTION
**Pull request by MySimpleCode**
#### Pull Request (PR) description
PR:ResourceName: IntuneDeviceConfigurationPolicyWindows
Created new intune resource IntuneDeviceConfigurationPolicyWindows

#### This Pull Request (PR) fixes the following issues

None

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413)

### CODE REVIEW

**Review by ykuijs — CHANGES_REQUESTED** [review]
Overall this looks good, but I do have some coding guideline comments

> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-:-Mj-g0MwCR6C9Tx7OC71:bhydfny)* status: 3 of 6 files reviewed, 15 unresolved discussions (waiting on @MySimpleCode and @NikCharlebois)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-b3tj09d9A1WgyKQI):*
What kind of file is this?
___
*[t.txt, line 1 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-b8g59Fj6jizhpuDY:-Mj-b8g59Fj6jizhpuDZ:b-gebu6o) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/t.txt#L1)):*
> ```help
> 
> ```

Why is this file here? Potentially used during testing and accidentally ended up in the PR??
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 9 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-b_1u5wPNiVhPYtT8:-Mj-b_1u5wPNiVhPYtT9:b7ardjz) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L9)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $displayName,
> ```

Please use Pascal casing for all parameter names:
E.g. DisplayName
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 20 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-bPrtDnQ10Pl7IhP4:-Mj-bPru5cj2DEC4SOBq:bgnyl9v) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L20)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.String]                
> ```

Please remove the trailing spaces on this line (and on several other lines in the parameter declarations
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 884 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-c2VqEkWzoBXWBBlm:-Mj-c2VqEkWzoBXWBBln:bbq8jo5) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L884)):*
> ```PowerShell
>     try
>     {
>         #Connect-MSGraph -Credential $GlobalAdmin
> ```

I think this comment can be removed, correct?
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 897 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-cCjI-KlncSUDJ34b:-Mj-cCjI-KlncSUDJ34c:b-xwud0y) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L897)):*
> ```PowerShell
>         Write-Verbose -Message "Found Device Configuration Policy {$DisplayName}"
>         return @{
>             description                                           	= $policy.description                                           
> ```

Please remove all trailing spaces on this line and all subsequent lines
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 1144 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-cNNZAvpyxGWOHh-t:-Mj-cNNZAvpyxGWOHh-u:b93q5w0) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L1144)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.String]                
> ```

Same comment about the trailing spaces and Pascal casing as for the Get method
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 2048 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-d58q0Z8Z_Jgsn13W:-Mj-d58q0Z8Z_Jgsn13X:b93q5w0) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L2048)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.String]                
> ```

Same comment about the trailing spaces and Pascal casing as for the Get method
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 2944 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-dziF2bOAXrwyFiwh:-Mj-dziF2bOAXrwyFiwi:b93q5w0) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L2944)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.String]                
> ```

Same comment about the trailing spaces and Pascal casing as for the Get method
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 3923 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-eZ7U3Zs5kxCfd-Ku:-Mj-eZ7U3Zs5kxCfd-Kv:b8pw5yc) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L3923)):*
> ```PowerShell
>                 $jsonString = $jsonString.TrimEnd(",`r`n")
>                 $jsonString += "`r`n},`r`n"
>             }elseif($key -like 'networkProxyServer'){
> ```

Please add spaces before and after elseif and place the open brace on the next line
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 3926 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-efjw3UkkYeTL25vU:-Mj-efjw3UkkYeTL25vV:b-dx32iz) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L3926)):*
> ```PowerShell
>                 $jsonString += "{`r`n"
>                 $jsonString += "`"@odata.type`": `"microsoft.graph.windows10NetworkProxyServer`",`r`n"
>                 foreach($Entry in $Parameters.networkProxyServer){
> ```

Please add spaces after foreach and place the open brace on the next line, same for other statements (if, else, etc) in this function.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 3937 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-er8QBLDZfXR8eIXH:-Mj-er8R8yPg0q5OVm4S:bnr9l3v) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L3937)):*
> ```PowerShell
>                 $jsonString += "`r`n},`r`n"
>      
>                 #}  
> ```

Is there a reason for this comment?
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1, line 4016 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-f0d8-vkktRKUt7u5:-Mj-f0d8-vkktRKUt7u6:bidkvr) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.psm1#L4016)):*
> ```PowerShell
>                 $jsonString = $jsonString.TrimEnd(",`r`n")
>                 $jsonString += "`r`n},`r`n"
>              }elseif($key -like 'networkProxyServer'){
> ```

Please add spaces before and after elseif and place the open brace on the next line, same for other statements (if, else, etc) in this function.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.schema.mof, line 5 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-fOKi7uStuvvwslHi:-Mj-fOKj2kTB2NAIRJJj:b-geajbr) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.schema.mof#L5)):*
> ```
> {
> 
>     [Key, Description("Description of the device configuration policy for Windows 10.")] String displayName; 
> ```

Please use Pascal casing for all parameters
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.schema.mof, line 7 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1413#-Mj-fBkM83L859t-ZB-w:-Mj-fBkM83L859t-ZB-x:b-dgf827) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/55aed1101539557f5a81cfa761aec0fa89aee48a/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows/MSFT_IntuneDeviceConfigurationPolicyWindows.schema.mof#L7)):*
> ```
>     [Key, Description("Description of the device configuration policy for Windows 10.")] String displayName; 
>     [Write, Description("Display name of the device configuration policy for Windows 10.")] String description;
>     [Write, Description("N/A")] String	enterpriseCloudPrintDiscoveryEndPoint;	
> ```

Any possibility that you are a description for each parameter?

And please change the tab behind the type declaration to a space (on all lines)

**Comment by MySimpleCode** [comment]
Thanks for the comment. 
will update the found issues.

**Comment by MySimpleCode** [comment]
Hi @ykuijs  updated the code with the suggested approvements and code guidelines.
Haven't updated the requested descriptions yet.  Will start with that in the near feature, but this is one with a serious amount of parameters.

**Comment by RuudGijsbers** [comment]
Hi @MySimpleCode, is there a specific reason you don't use the cmdlets from the Microsoft.Graph.Intune module like $policyinfo? In my opinion $policy is duplicate. You can use the information from $policyinfo. If you want, we can schedule a short call, where I can explain a few things around creating resources

**Comment by MySimpleCode** [comment]
Hi @RuudGijsbers, to be honest, this pull request is just a first test, on what to expect from a PR, and just made a copy of the iOS version of this resource and updated it for the Windows version. I saw indeed some duplicates steps, but my thoughts where, there must be a reason for that.
A call  is fine. you can schedule one.

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
