### PR TITLE
SPOSiteScript: Fix unable to update existing item

### LINKED ISSUE #1108: SPOSiteScript: GlobalAdminAccount is required in Get-TargetResource
#### Details of the scenario you tried and the problem that is occurring
Applying or testing a SPOSiteScript using certificate throws error.

#### Verbose logs showing the problem
PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure
that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt
etc.
    + CategoryInfo          : OperationStopped: (:) [], CimException
    + FullyQualifiedErrorId : System.NotSupportedException
    + PSComputerName        : localhost

#### Suggested solution to the issue
GlobalAdminAccount is specified as required in Get-TargetResource
Remove parameter to not required https://github.com/microsoft/Microsoft365DSC/blob/1ea37be6503b5bf2c75a390bc530e2125d38e697/Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteScript/MSFT_SPOSiteScript.psm1#L48

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
            SPOSiteScript "SiteScript-$($siteScript.Key.Replace(' ', ''))"
            {
                Content               = $siteScriptContent
                Ensure                = "Present";
                Title                 = $siteScript.Title;
                ApplicationId         = $ApplicationId;
                TenantId              = $TenantId;
                CertificatePassword   = $CertificatePasswordCreds;
                CertificatePath       = $CertificatePath;
                CertificateThumbprint = $CertificateThumbprint;
            }


```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.317.1

### LINKED ISSUE #1112: SPOSiteScript: Unable to update existing site script
#### Details of the scenario you tried and the problem that is occurring
Existing site script is not updated by SPOSiteScript

#### Verbose logs showing the problem
No error is shown. Configuration seems to fail, but testing the configuration returns the resource not in desired state.

#### Suggested solution to the issue
Code references incorrect variable
https://github.com/microsoft/Microsoft365DSC/blob/1ea37be6503b5bf2c75a390bc530e2125d38e697/Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteScript/MSFT_SPOSiteScript.psm1#L280

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Not relevant
```

#### The operating system the target node is running
OsName : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture : 64-bit
WindowsVersion : 1809
WindowsBuildLabEx : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage : en-US
OsMuiLanguages : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.317.1

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description
SPOSiteScript was unable to update existing item due to wrong variable reference.
Also change the verbose message that the update failed into a warning (should it maybe be an error message)?
Made parameter GlobalAdminAccount optional in SPOSiteScript Get-TargetResource

#### This Pull Request (PR) fixes the following issues
    - Fixes #1112 
    - Fixes #1108 

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1113)

### CODE REVIEW

**Comment by ykuijs** [comment]
@jensotto Could you also add an entry to the changelog for this fix?

**Comment by jensotto** [comment]
Changelog updated

**Comment by ykuijs** [comment]
Please target the dev branch instead of master

**Comment by jensotto** [comment]
@ykuijs Done in PR #1119

**Pull request closed without merging**
