### PR TITLE
Update launch.json

### LINKED ISSUE #3922: Unit Tests Not Idempotent
### Description of the issue

When first running the unit tests in a new PowerShell session they all pass. When running them a second time, failures are present. Opening a new PowerShell session and again they pass first time and failures are produced in the second. To keep the logs concise I have removed all test files apart from one but the behavior is the same. `Test.ps1` is a helper file which simply contains the Unit Test code from `.github/workflows/Unit Tests.yml` 
```
# Test.ps1
Import-Module './Tests/TestHarness.psm1' -Force
$MaximumFunctionCount = 32767

try
{
    $results = Invoke-TestHarness -IgnoreCodeCoverage
}
catch
{
    $MaximumFunctionCount = 32767
    Import-Module './Tests/TestHarness.psm1' -Force
    $results = Invoke-TestHarness -IgnoreCodeCoverage
}
if ($results.FailedCount -gt 0)
{
    throw "{$($results.FailedCount)} Unit Test(s) Failed"
}
```

### Microsoft 365 DSC Version

DEV

### Which workloads are affected

Azure Active Directory

### The DSC configuration

_No response_

### Verbose logs showing the problem

```powershell
PS C:\Users\Fraser\Code\Microsoft365DSC> .\Test.ps1                                                                     Running all Microsoft365DSC Unit Tests                                                                                                                                                                                                          Starting discovery in 1 files.
Discovery found 15 tests in 713ms.
Running tests.
[+] C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1 5.1s (3.28s|1.17s)
Tests completed in 5.15s
Tests Passed: 15, Failed: 0, Skipped: 0 NotRun: 0
Running the tests took 0 hours, 0 minutes, 7 seconds
Completed running all Microsoft365DSC Unit Tests
PS C:\Users\Fraser\Code\Microsoft365DSC> .\Test.ps1
Running all Microsoft365DSC Unit Tests

Starting discovery in 1 files.
Discovery found 15 tests in 23ms.
Running tests.
[-] DSC Resource 'AADApplication'.The application should exist but it does not.Should return values from the get method 140ms (139ms|1ms)
 Expected strings to be the same, but they were different.
 Expected length: 6
 Actual length:   7
 Strings differ at index 0.
 Expected: 'Absent'
 But was:  'Present'
            ^
 at (Get-TargetResource @testParams).Ensure | Should -Be 'Absent', C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:93
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:93
[-] DSC Resource 'AADApplication'.The application should exist but it does not.Should create the application from the set method 20ms (19ms|1ms)
 Expected New-MgApplication in module MSFT_AADApplication to be called 1 times exactly, but was called 0 times
 at Should -Invoke -CommandName 'New-MgApplication' -Exactly 1, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:101
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:101
[-] DSC Resource 'AADApplication'.The application exists but it should not.Should return values from the get method 8ms (7ms|1ms)
 Expected Get-MgApplication in module MSFT_AADApplication to be called 1 times exactly, but was called 0 times
 at Should -Invoke -CommandName 'Get-MgApplication' -Exactly 1, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:142
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:142
[-] DSC Resource 'AADApplication'.The app exists and values are already in the desired state.Should return Values from the get method 7ms (6ms|1ms)
 Expected Get-MgApplication in module MSFT_AADApplication to be called 1 times exactly, but was called 0 times
 at Should -Invoke -CommandName 'Get-MgApplication' -Exactly 1, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:193
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:193
[-] DSC Resource 'AADApplication'.The app exists and values are already in the desired state.Should return true from the test method 54ms (54ms|1ms)
 Expected $true, but got $false.
 at Test-TargetResource @testParams | Should -Be $true, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:197
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:197
[-] DSC Resource 'AADApplication'.Values are not in the desired state.Should return values from the get method 9ms (9ms|1ms)
 Expected Get-MgApplication in module MSFT_AADApplication to be called 1 times exactly, but was called 0 times
 at Should -Invoke -CommandName 'Get-MgApplication' -Exactly 1, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:236
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:236
[-] DSC Resource 'AADApplication'.Assigning Permissions to a new Application.Should return values from the get method 11ms (10ms|1ms)
 Expected Get-MgApplication in module MSFT_AADApplication to be called 1 times exactly, but was called 0 times
 at Should -Invoke -CommandName 'Get-MgApplication' -Exactly 1, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:290
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:290
[-] DSC Resource 'AADApplication'.Assigning Permissions to a new Application.Should return false from the test method 14ms (13ms|1ms)
 RuntimeException: You cannot call a method on a null-valued expression.
 at Test-TargetResource, C:\Users\Fraser\Code\Microsoft365DSC\Modules\Microsoft365Dsc\DSCResources\MSFT_AADApplication\MSFT_AADApplication.psm1:796
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:294
[-] DSC Resource 'AADApplication'.Assigning Permissions to a new Application.Should call the new method 25ms (24ms|1ms)
 Expected New-MgApplication in module MSFT_AADApplication to be called 1 times exactly, but was called 0 times
 at Should -Invoke -CommandName 'New-MgApplication' -Exactly 1, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:299
 at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADApplication.Tests.ps1:299
Tests completed in 633ms
Tests Passed: 6, Failed: 9, Skipped: 0 NotRun: 0
Running the tests took 0 hours, 0 minutes, 0 seconds
Completed running all Microsoft365DSC Unit Tests
{9} Unit Test(s) Failed
At C:\Users\Fraser\Code\Microsoft365DSC\Test.ps1:16 char:5
+     throw "{$($results.FailedCount)} Unit Test(s) Failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ({9} Unit Test(s) Failed:String) [], RuntimeException
    + FullyQualifiedErrorId : {9} Unit Test(s) Failed
```
```


### Environment Information + PowerShell Version
Windows 11

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### PR DESCRIPTION
**Pull request by andikrueger**
- Fixes #3922

#### Pull Request (PR) description

This will fix an issue with the launch.json and how unit test need to be started in VSCode.

#### This Pull Request (PR) fixes the following issues

- Fixes #3922

### CODE REVIEW

**Comment by fraserdarwent** [comment]
Should we fix `Get current unit test code overage` at the same time?
That currently spits out:
```
System.Management.Automation.RuntimeException: No test files were found and no scriptblocks were provided. Please ensure that you provided at least one path to a *.Tests.ps1 file, or a directory that contains such file. Or that you provided a ScriptBlock test container.
at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.5.0\Pester.psm1: line 5042
at <ScriptBlock>, C:\Users\Fraser\Code\Microsoft365DSC\.vscode\GetTestCoverage.ps1: line 31
at <ScriptBlock>, <No file>: line 1
```

**Comment by andikrueger** [comment]
That would be good. Will look into it.

**Comment by fraserdarwent** [comment]
Looks like Pester v5 onwards requires a different way of passing data in https://pester.dev/docs/usage/data-driven-tests#providing-external-data-to-tests

**Comment by fraserdarwent** [comment]
This works.
`launch.json`
```
{
  "version": "0.3.0",
  "configurations": [
    {
      "type": "PowerShell",
      "request": "launch",
      "name": "Run current unit test",
      "script": "${file}",
      "args": [],
      "cwd": "${file}",
      "createTemporaryIntegratedConsole": true
    },
    {
      "type": "PowerShell",
      "request": "launch",
      "name": "Get current unit test code overage",
      "script": "${workspaceRoot}/.vscode/GetTestCoverage.ps1",
      "args": ["${file}"],
      "createTemporaryIntegratedConsole": true
    }
  ]
}
```
`GetTestCoversage.ps1`
```
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]
    $UnitTestFilePath
)

if ($UnitTestFilePath.EndsWith('Tests.ps1'))
{
    $unitTest = Get-Item -Path $UnitTestFilePath
    $unitTestName = "$($unitTest.Name.Split('.')[1])"

    $coveragePath = (Join-Path -Path $PSScriptRoot `
            -ChildPath "..\Modules\Microsoft365DSC\DSCResources\MSFT_$($unitTestName)\MSFT_$($unitTestName).psm1" `
            -Resolve)

    $config = New-PesterConfiguration
    $config.Run.Path = $UnitTestFilePath
    $config.CodeCoverage.Enabled = $true
    $config.CodeCoverage.Path = $coveragePath
    Invoke-Pester -Configuration $config
}
```

**Comment by andikrueger** [comment]
Thanks for the input. I’ll take a look how we can create a launcher that works for all versions of pester

**Comment by ykuijs** [comment]
Windows 10 and 11 automatically ship Pester v3.5 with it. This however is a very old version and should not be used. Since v5, Pester tests are very different in setup which is not backwards compatible. So we should always target v5+.

**Comment by fraserdarwent** [comment]
Can we get this in?

**Comment by andikrueger** [comment]
Sorry, totally lost sight of this PR. Will try to work on the update within the next days.

**Comment by andikrueger** [comment]
@ykuijs Could you please review this PR?

**Review by ykuijs — APPROVED** [review]
LGTM

**Pull request merged**
