### PR TITLE
MSFT_EXODistributionGroup: Added properties

### PR DESCRIPTION
**Pull request by levesquesamuel**
#### Pull Request (PR) description
Added multiple properties to this ressource

#### This Pull Request (PR) fixes the following issues
None

### CODE REVIEW

**Comment by andikrueger** [comment]
Thanks for your contribution! Could you please update the schema file and add an entry to the unreleased section of the changelog?

**Comment by ykuijs** [comment]
@levesquesamuel Could you please update this PR, so we can merge it? Please let us know if you need help or have questions.

**Comment by levesquesamuel** [comment]
Could you clarifiy why we need to add the properties to the schema? I've tested the export and it works. Also the "Set" doesn't currently handle these properties.

**Comment by andikrueger** [comment]
This needs to be done to be able to compile a configuration.

**Comment by levesquesamuel** [comment]
Ok, I'll complete the updates in early November. If you prefer to close this, I can submit another PR later.

**Comment by NikCharlebois** [comment]
Will re-open as a separate PR.

**Pull request closed without merging**
