### PR TITLE
Added Markdown option to New-DSCReportFromConfiguration

### PR DESCRIPTION
**Pull request by martincaddick**
_Very_ closely follows the HTML option

### CODE REVIEW

**Comment by martincaddick** [comment]
@nik while testing this I have noticed that it correctly handles this
image

but not this
image

resourceinstancename shouldn't be here should it?
image

**Comment by martincaddick** [comment]
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Please add the Markdown value in the ValidateSet of the New-M365DSCReportFromConfiguration function.

**Comment by martincaddick** [comment]
@NikCharlebois Changes made.

**Comment by martincaddick** [comment]
@microsoft-github-policy-service agree

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
