### PR TITLE
Adding DSC Resource EXOTransportRule

### PR DESCRIPTION
**Pull request by RobBiddle**
#### Pull Request (PR) description
Adds DSC Resource EXO_TransportRule

#### This Pull Request (PR) fixes the following issues
None

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1138)

### CODE REVIEW

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Few minor things, mostly related to the authentication parameters where EXO now needs to allow authentication with an Azure AD App.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1138#-:-MXit9QnATJLHxmeEZUx:b16imgs)* status: all files reviewed, 3 unresolved discussions (waiting on @RobBiddle)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1, line 694 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1138#-MXisPD85Hmg3YJ83fhC:-MXisPD85Hmg3YJ83fhD:b63rbc5) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/826d147de2c319542a5506329ec586c5bd61bd06/Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1#L694)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.Management.Automation.PSCredential]
>         $GlobalAdminAccount
> ```

Need to also support CertificateThumbprint, TenantID, ApplicationID and CertificateSecret like the other resources
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1, line 716 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1138#-MXisWe62P2f7PL3gh8M:-MXisWe62P2f7PL3gh8N:b-tzlnmm) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/826d147de2c319542a5506329ec586c5bd61bd06/Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1#L716)):*
> ```PowerShell
>         Write-Verbose -Message "Transport Rule $($Name) does not exist."
> 
>         $nullReturn = @{
> ```

Since this is such a big hashtable, maybe do something like what we're doing in the other EXO resources:

$nullReturn = $PSBoundParameters
$nullReturn.Ensure = "Absent"
return $nullReturn
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1, line 2716 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1138#-MXit-on9aNeyzvpU1c9:-MXit-on9aNeyzvpU1cA:bk8evoe) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/826d147de2c319542a5506329ec586c5bd61bd06/Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1#L2716)):*
> ```PowerShell
>         $result = Get-TargetResource @Params
>         $result.GlobalAdminAccount = Resolve-Credentials -UserName "globaladmin"
>         $content = "        EXOTransportRule " + (New-GUID).ToString() + "`r`n"
> ```

Take a look at how the other EXO resources are handling it and make sure to call into the Update-M365DSCExportAuthenticationResults cmdlets (like the other resources).

**Comment by RobBiddle** [comment]
Thanks for reviewing, I'll start working on the requested changes.

**Review by NikCharlebois — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1138#-:-MY4pjXf-wftmUIzG1LJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RobBiddle)

**Review by NikCharlebois — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RobBiddle)

**Pull request merged**
