### PR TITLE
Support  VM MI, wrap config items in region blocks

### PR DESCRIPTION
**Pull request by mlhickey**

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@mlhickey can you provide additional context and information around what this PR is trying to accomplish and what it fixes? Thanks

**Comment by mlhickey** [comment]
I have submitted a PR to the MSCloudLoginAssistant  repo to enable managed identity authentication on Azure VMs, using the managed identity of the VM to provide a more maintenance-free authN/authZ identity in place of a SPN & secret/certificate,
This PR is configured to support the use of that managed identity specifically in the AAD resources which leverage the Microsoft Graph PowerShell SDK.

**Comment by andikrueger** [comment]
@NikCharlebois This is the PR within MSCloudLoginAssistant: https://github.com/microsoft/MSCloudLoginAssistant/pull/123 and the issue describing the new functionality: https://github.com/microsoft/MSCloudLoginAssistant/issues/121

**Comment by NikCharlebois** [comment]
@mlhickey Can you please review the conflicts and correct them. I'll have a quick review of the PR. Thanks

**Comment by mlhickey** [comment]
Will do, looks like I need to merge changes in from updated MSFT_AADApplication which created the conflicts (addition of Owners)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mlhickey** [comment]
@NikCharlebois  - would it be simpler for me to re-base on the current dev branch and update from there since my branch was built off 1.22.720.1?

**Comment by NikCharlebois** [comment]
@mlhickey truly sorry for the delays. Yes, it probably will be easier for you to rebase at this stage. Let me know if you need any assistance.

**Pull request closed without merging**
