### PR TITLE
Alternative implementation of AADAdministrativeUnit

### PR DESCRIPTION
**Pull request by salbeck-sit**
#### Pull Request (PR) description
Alternative implementation of #2469

#### This Pull Request (PR) fixes the following issues
Implementation of AADAdministrativeUnit including support for Member and ScopedRoleMember

### CODE REVIEW

**Comment by salbeck-sit** [comment]
hmm. Graph-modules were updated. I'll do another test-run locally and see exactly what fails

**Comment by salbeck-sit** [comment]
It seems unit-testing has an issue with cmdlets that only exist in Graph's beta profile - such as New-MgAdministrativeUnitMemberByRef. If I do 'Select-MgProfile beta' before calling Invoke-TestHarness then tests pass. Which is odd, because I also do that explicitly in the Pester-script. But it seems to me that perhaps because Pester invokes the script and not Powershell, some commands are skipped

**Comment by salbeck-sit** [comment]
When I run unit-tests locally, everything passes. The tests that are run by the PR Action complains that microsoft.graph.* modules v1.15.0 are in use ? Something in the environment is obviously different. Could it be that the workflow-file specifies older Graph-versions ?

**Comment by salbeck-sit** [comment]
Nope. The workflow doesn't use module-versions but simply installs latest versions. Which may or may not be the same as versions in the Dependencies manifest. Another difference is that the workflow installs Pester v5.0.4 whereas I use v5.3.1. That shouldn't be an issue.

**Comment by salbeck-sit** [comment]
It is remotely possible to replace all calls to the beta-cmdlets with Invoke-MgGraphRequest and the corresponding Uris and a bunch of BodyParameter's, but I'd rather be able to create DSC-resources that utilize the beta-profile.
In any case, depending on whether and/or how you'll prefer to move forward, it would be nice to see a line or two about the issue in the M365DSC blog

**Comment by salbeck-sit** [comment]
I believe this is a Pester issue. See https://github.com/pester/Pester/issues/2256

**Comment by salbeck-sit** [comment]
Now using v1.0 cmdlet-names for everything but the AU itself (ie members and scopedrolemembers). Local test passes

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
