### PR TITLE
Introduces First Intune Resource: IntuneDeviceCategory

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Added Intune Support.

#### This Pull Request (PR) fixes the following issues
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/793)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs can I get a code review? This introduces our first Intune resource. Thanks mate!

**Review by ykuijs — CHANGES_REQUESTED** [review]
One small comment

> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/793#-:-MHpjCUh4hacGdm8hgpU:b-2w0prt)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCategory/MSFT_IntuneDeviceCategory.schema.mof, line 7 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/793#-MHpi_st3mJnZFKReIjZ:-MHpi_su-yzfouni_2AL:bybz6i1) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/adf5ba1bdd36ab5f95db960bacddcfa3c4dfd61d/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCategory/MSFT_IntuneDeviceCategory.schema.mof#L7)):*
> ```
>     [Write, Description("Description of the device category.")] String Description;
>     [Write, Description("Present ensures the category exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
>     [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
> ```

"SharePoint Global Admin" should be updated to the correct role

**Review by NikCharlebois — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/793)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCategory/MSFT_IntuneDeviceCategory.schema.mof, line 7 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/793#-MHpi_st3mJnZFKReIjZ:-MHpjtb2-t3ddtLtOc52:bsac2s1) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/adf5ba1bdd36ab5f95db960bacddcfa3c4dfd61d/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCategory/MSFT_IntuneDeviceCategory.schema.mof#L7)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

"SharePoint Global Admin" should be updated to the correct role
</blockquote></details>

Good catch. Done

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/793#-:-MHpoigPAwhLWmQ8ogMn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
