### PR TITLE
Fixes #3097

### LINKED ISSUE #3097: Update-M365DSCModule: Does not properly unload old modules and switch to new module
The current implementation of the update method does not properly uninstall and update the old packages. It should unload the old M365DSC Module and load the new module after the install.

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
* Updated the Update-M365DSCModule to unload dependencies before updating them and then to reload the new versions.

#### This Pull Request (PR) fixes the following issues
* FIXES #3097

### CODE REVIEW

**Review by ykuijs — COMMENTED** [review]
Just wondering:
Does this work? Can you unload the module from code that is being ran from inside that module? Don't you get some sort of "is use" errors?

**Comment by andikrueger** [comment]
I'm running a test right now. 

It worked good for most of the Update-M365DSCModule process.

1. The current M365DSC module is not removed properly.
2. There are issues with removing the Microsoft.Graph.Authentication dlls

```powershell
Checking Microsoft.Graph.Authentication                                                                                                                                                                           VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.                                                                                   VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Authentication.                                                                                                                  VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.23.0\./Microsoft.Graph.Authentication.psm1'.                                                       VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.                                                                                   VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Authentication.                                                                                                                  VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\./Microsoft.Graph.Authentication.psm1'.                                                       Uninstalling Microsoft.Graph.Authentication version {1.21.0}                                                                                                                                                      Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies\Desktop\Microsoft.Identity.Client.dll: Access to the path                          'Microsoft.Identity.Client.dll' is denied.                                                                                                                                                                        At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21                                                                                               + ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse                                                                                                                                       +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                           + CategoryInfo          : PermissionDenied: (Microsoft.Identity.Client.dll:FileInfo) [Remove-Item], UnauthorizedAccessException                                                                                   + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                              Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies\Desktop: The directory is not empty.                                               At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21                                                                                               + ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse                                                                                                                                       +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                           + CategoryInfo          : WriteError: (Desktop:DirectoryInfo) [Remove-Item], IOException                                                                                                                          + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                                         Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies\Microsoft.Graph.Auth.dll: Access to the path 'Microsoft.Graph.Auth.dll' is denied. At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21                                                                                               + ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse                                                                                                                                       +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                           + CategoryInfo          : PermissionDenied: (Microsoft.Graph.Auth.dll:FileInfo) [Remove-Item], UnauthorizedAccessException                                                                                        + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                              Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies\Microsoft.IdentityModel.JsonWebTokens.dll: Access to the path                      'Microsoft.IdentityModel.JsonWebTokens.dll' is denied.                                                                                                                                                            At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21                                                                                               + ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse                                                                                                                                       +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Ident...onWebTokens.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies\Microsoft.IdentityModel.Logging.dll: Access to the path
'Microsoft.IdentityModel.Logging.dll' is denied.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.IdentityModel.Logging.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies\Microsoft.IdentityModel.Tokens.dll: Access to the path
'Microsoft.IdentityModel.Tokens.dll' is denied.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.IdentityModel.Tokens.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies\System.IdentityModel.Tokens.Jwt.dll: Access to the path
'System.IdentityModel.Tokens.Jwt.dll' is denied.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (System.IdentityModel.Tokens.Jwt.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Dependencies: The directory is not empty.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Dependencies:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Microsoft.Graph.Authentication.Core.dll: Access to the path
'Microsoft.Graph.Authentication.Core.dll' is denied.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Graph.Authentication.Core.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Microsoft.Graph.Authentication.dll: Access to the path 'Microsoft.Graph.Authentication.dll' is
denied.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Graph.Authentication.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0\Microsoft.Graph.Core.dll: Access to the path 'Microsoft.Graph.Core.dll' is denied.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Graph.Core.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.21.0: The directory is not empty.
At C:\DEV\andikrueger-Microsoft365DSC\Microsoft365DSC\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:2819 char:21
+ ...                Remove-Item $($foundModule.ModuleBase) -Force -Recurse
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Program File...tication\1.21.0:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by NikCharlebois** [comment]
Yes, we should be allowed to unload dependencies but not the M365DSC module itself as Andi points out. I will investigate the permissions denied errors later today (hopefully).

**Comment by andikrueger** [comment]
I did some retesting this morning. It looks like the errors above were something with my system and not related to our module.

LGTM!

**Review by andikrueger — APPROVED** [review]
LGTM

**Pull request merged**
