### PR TITLE
PRIORITY / URGENT - Migrate MSCloudLoginAssistant authentication context access to cmdlets

### PR DESCRIPTION
**Pull request by FabienTschanz**
#### Pull Request (PR) description
This PR migrates the `$global:MSCloudLoginConnectionProfile` access to its specific workload cmdlet counterpart that was introduced with version 1.1.29 of MSCloudLoginAssistant. Without this change, every resource that uses any part of the authentication context will fail!

#### This Pull Request (PR) fixes the following issues
None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource parameter descriptions added/updated in the schema.mof.
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource settings.json file contains all required permissions.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

### CODE REVIEW

**Comment by ykuijs** [comment]
Please add the changelog entry under the 1.24.1211.1 version....we will include it in this weeks release

**Comment by FabienTschanz** [comment]
Alright, will do.

**Comment by FabienTschanz** [comment]
@ykuijs And done. Ready for review.

**Review by ykuijs — APPROVED** [review]
LGTM

**Comment by ykuijs** [comment]
Unit tests are failing because the Get-MSCloudLoginConnectionProfile function is not mocked and therefore unknown. Can you please add that to all unit test of impacted modules?

**Comment by FabienTschanz** [comment]
On my way.

**Comment by FabienTschanz** [comment]
Let's see how this one goes. I also added the two new commands to the unit tests template for the resource generator.

**Comment by FabienTschanz** [comment]
Still not quite. I'm working on it.

**Comment by ykuijs** [comment]
Nope, not yet. You can't mock functions that haven't been declared yet.

To solve it, add the function declaration (no function body required) with the same parameters to the file Tests\Unit\Stubs\Generic.psm1

**Comment by FabienTschanz** [comment]
Phew, that was a bunch of stuff to think about... Should have gotten it on the first try though.

**Comment by ykuijs** [comment]
That should do it. Thanks for implementing this so fast, really appreciated!

**Comment by FabienTschanz** [comment]
> That should do it. Thanks for implementing this so fast, really appreciated!

Sure thing. Hope the tests work (at least the couple ones I checked now did succeed on my machine). I missed a `Write-Verbose -Message $PSScriptRoot -Verbose` at the beginning of the MSCloudLoginAssistant.psm1 file, so we need to remove that in the future. I will also open a PR there that enables to disconnect the Microsoft Graph workload and also only disconnect a specific workload. But that's something for the future (maybe tomorrow if I'm bored 😆).

**Comment by ykuijs** [comment]
Nik already ran into that Verbose message when testing an export. Definitely something we need to fix, but not a P1 issue for now

**Comment by ykuijs** [comment]
Worked like a charm. Merging now!

**Pull request merged**
