### PR TITLE
AADAuthorizationPolicy: Implementing #2016

### LINKED ISSUE #2016: AADAuthorizationPolicy: New resource proposal
### Description
As described in https://docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta, the Authorization Policy provides a way to configure a number of basic tenant-properties that otherwise can only be managed in the portal which is what I'm trying to avoid (aren't we all...)

### Proposed properties
IsSingleInstance,
DisplayName,
Description,
AllowedToSignUpEmailBasedSubscriptions,
AllowedToUseSSPR,
AllowEmailVerifiedUsersToJoinOrganization,
AllowInvitesFrom,
BlockMsolPowerShell,
DefaultUserRoleAllowedToCreateApps,
DefaultUserRoleAllowedToCreateSecurityGroups,
DefaultUserRoleAllowedToReadOtherUsers,
DefaultUserRolePermissionGrantPoliciesAssigned,
GuestUserRole

(The DefaultUserRole... params are for the hash-table represented by defaultUserRolePermissions)
DisplayName and Description are optional as the policy is single-instance.

### Special considerations or limitations
At the moment, the Graph SDK doesn't contain any cmdlets for retrieving and/or modifying /policies/authorizationPolicy/authorizationPolicy. Invoke-MgGraphRequest works quite well, though.
I have most of the code ready in a forked repo but am struggling a bit with the unit-test.
I haven't found a clear way to devise tests that include mocks for Invoke-MgGraphRequest given that it is used both to GET the resource and to PATCH it. It may be that my less than intimate relationship with Pester is showing here.
It's possible that Mock can be used with -ParameterFilter to separate the two uses for unit-testing. Any input is welcome.

### PR DESCRIPTION
**Pull request by salbeck-sit**
#### Pull Request (PR) description
New AAD resource. First shot at OS collaboration. Comments and suggestions very welcome
#### This Pull Request (PR) fixes the following issues
Fixes #2016

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@salbeck-sit can you please look at the failing unit tests. Let us know if you need help fixing them.

**Comment by salbeck-sit** [comment]
fixed unit-test (Pester mocks Graph-cmdlets based on the v1.0 profile but here I use the beta profile which uses different syntax

**Comment by salbeck-sit** [comment]
oops, added missing param GuestUserRole to schema

**Comment by salbeck-sit** [comment]
I've run Update-M365Dependencies after a fresh pull and then I start a console and import ..\tests\TestHarness.psm1 and then lnvoke-TestHarness. I do see a number of failed tests but as far as I can tell, all tests for AADAuthorizationPolicy pass.
I'm obviously missing something, could you please enlighten me ?

**Comment by salbeck-sit** [comment]
@NikCharlebois could you please take a look at my previous comment in this PR. I think I need a bit of help to get it right.

**Review by NikCharlebois — APPROVED** [review]
LGTM

**Comment by NikCharlebois** [comment]
Let us approve and merge for now since we know these errors are false positive. Thanks for your contribution, awesome work!

**Pull request merged**
