### PR TITLE
SPOSiteScript: Remove mandatory GlobalAdminAccount

### LINKED ISSUE #1108: SPOSiteScript: GlobalAdminAccount is required in Get-TargetResource
#### Details of the scenario you tried and the problem that is occurring
Applying or testing a SPOSiteScript using certificate throws error.

#### Verbose logs showing the problem
PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure
that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt
etc.
    + CategoryInfo          : OperationStopped: (:) [], CimException
    + FullyQualifiedErrorId : System.NotSupportedException
    + PSComputerName        : localhost

#### Suggested solution to the issue
GlobalAdminAccount is specified as required in Get-TargetResource
Remove parameter to not required https://github.com/microsoft/Microsoft365DSC/blob/1ea37be6503b5bf2c75a390bc530e2125d38e697/Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteScript/MSFT_SPOSiteScript.psm1#L48

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
            SPOSiteScript "SiteScript-$($siteScript.Key.Replace(' ', ''))"
            {
                Content               = $siteScriptContent
                Ensure                = "Present";
                Title                 = $siteScript.Title;
                ApplicationId         = $ApplicationId;
                TenantId              = $TenantId;
                CertificatePassword   = $CertificatePasswordCreds;
                CertificatePath       = $CertificatePath;
                CertificateThumbprint = $CertificateThumbprint;
            }


```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.317.1

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description
Removed GlobalAdminAccount as mandatory parameter in SPOSiteScript Get-TargetResource 

#### This Pull Request (PR) fixes the following issues
    - Fixes #1108

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1109)

### CODE REVIEW

**Review by ykuijs — COMMENTED** [review]
@jensotto Could you also add an entry to the Changelog for this update?

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1109#-:-MW4WW3dClHPOrrnypAT:b-rvzgbn)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Comment by jensotto** [comment]
Changelog updated

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1109#-:-MWAzdMNAgMCKpoUovQW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Comment by ykuijs** [comment]
Immediately after merging this PR I noticed that you targeted the master branch, so I created a new PR to revert this change.

@jensotto, could you include this PR in PR #1113 (same resource) and make sure that PR is targetting the dev branch?

**Comment by jensotto** [comment]
@ykuijs I'll do that. But I just folowed the contribution guide. It specifically mentions that PR's should target the master branch. Maybe it should be updated to specify the dev branch as target.

**Comment by ykuijs** [comment]
@jensotto, great spot. I will make sure this gets updated. Sorry for that :wink:

**Pull request merged**
