### PR TITLE
Add separate check for strings

### PR DESCRIPTION
**Pull request by FabienTschanz**
#### Pull Request (PR) description
This PR improves the comparison of strings inside of `Compare-M365DSCComplexObject`. Previously, the comparison did not check for different line breaks (`\r\n` vs `\n`). The comparison was also updated to use `StringComparison.Ordinal`, a byte-wise check which does not take into consideration the current culture. 

#### This Pull Request (PR) fixes the following issues
None.

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource parameter descriptions added/updated in the schema.mof.
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource settings.json file contains all required permissions.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

### CODE REVIEW

**Comment by ricmestre** [comment]
Nitpicking, but comment *# Remove carriage return and line feed characters* is incorrect, you're replacing CRLF characters with LF so you could say you're only removing carriage return. Also not that it makes a difference but everything in M365DSC is done with CRLF in mind but you're actually replacing it with LF, again not that it makes a difference in the end result but just saying.

Also, this is something that is missing from plain string comparisons not inside CIM instances, I have a monitoring tool which I have to massage the results with something very similar so that they're not reported as drifts, can't just remember which function it is but it should be in *M365DSCUtil.psm1*

**Comment by FabienTschanz** [comment]
@ricmestre Will update my comment 👀  Is the function you mean `Test-M365DSCParameterState`?

**Review by ykuijs — APPROVED** [review]
LGTM

**Comment by ykuijs** [comment]
This PR looks fine with me. Are there any open actions based on the comment from @ricmestre?? Or can this PR be merged?

**Comment by FabienTschanz** [comment]
@ykuijs The logic was also added in `Test-M365DSCParameterState`, which I assume was the function @ricmestre was talking about since it essentially contains the same logic as `Compare-M365DSCComplexObject`.

**Comment by ricmestre** [comment]
Wasn't able to test it but it looks good to me.

**Comment by ykuijs** [comment]
@FabienTschanz Could you please update from Dev and make sure your changelog entry is placed under the Unreleased section?

**Comment by FabienTschanz** [comment]
> @FabienTschanz Could you please update from Dev and make sure your changelog entry is placed under the Unreleased section?

Will do, just a couple of minutes.

**Pull request merged**
