### PR TITLE
Teams v2 support

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Added support for Teams v2 PowerShell Module

#### This Pull Request (PR) fixes the following issues
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1211)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs, could you please do the honors?

**Review by ykuijs — DISMISSED** [review]
:lgtm:

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1211#-:-M_t1pyd0qS6S0wkjiOc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Comment by ykuijs** [comment]
Approved, but unit tests for several resources are failing. Could you please check and correct?

**Review by desmay — DISMISSED** [review]
> Reviewed 1 of 25 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
