### PR TITLE
Update Graph API Calls to be Dynamic Cloud Endpoint not hard-coded .com

### LINKED ISSUE #5212: AADGroup Get-TargetResource Get Assigned Licenses doesn't work with Government .us endpoints
### Description of the issue

AADGroup.Get-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint  (line 272) which results in failure with EntraID Government tenants.  

Correct call should be to do
$url = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "v1.0/groups/$($Group.Id)/assignedLicenses"

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

Export-M365DSCConfiguration -Credential $creds -tenantID <tenant>.onmicrosoft.us -Component @("AADGroup")

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5214: M365DSCDRGUtil.psm1 Update-IntuneDeviceConfigurationPolicy hard codes Commercial Graph API breaking Government
Update-IntuneDeviceConfigurationPolicy function call to Invoke-MgGraphRequest has hardcoded URL to commercial endpoint which breaks support for Intune Government

Correction should be something like this.
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/configurationPolicies/$DeviceConfigurationPolicyId"

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### LINKED ISSUE #5215: MSFT_AADServicePrincipal Get-TargetResource has hard coded Commercial Graph endpoints breaking Government
### Description of the issue

AADServicePrincipal.Get-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint in a number of locations which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl  for the graph hostname.

complexDelegatedPermissionClassifications 
delegatedPermissionClassifications

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5216: MSFT_AADApplication Get-TargetResource has hard coded Commercial Graph endpoints breaking Government
AADApplication.Get-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl  for the graph hostname.

onPremisesPublishing

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### LINKED ISSUE #5217: AADNamedLocationPolicy.Set-TargetResource has hard coded Commercial Graph endpoint breaking Government
### Description of the issue

AADNamedLocationPolicy.Set-TargetResource call to Invoke-MgGraphRequest use 2x hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl  for the graph hostname.

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5218: AADAdminConsentRequestPolicy.Set-TargetResourcehas hard coded Commercial Graph endpoints breaking Government
### Description of the issue

AADAdminConsentRequestPolicy.Set-TargetResource call to Invoke-MgGraphRequest use 1 hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + 'beta/policies/adminConsentRequestPolicy'

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5219: AADConditionalAccessPolicy.Set-TargetResource has hard coded Commercial Graph endpoints breaking Government
### Description of the issue

AADConditionalAccessPolicy.Set-TargetResource call to Invoke-MgGraphRequest use 2 hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/identity/conditionalAccess/policies/$($currentPolicy.Id)"
and 
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/identity/conditionalAccess/policies"

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5220: IntunePolicySets.Set-TargetResource has hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntunePolicySets.Set-TargetResource call to Invoke-MgGraphRequest use 2 hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Url = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceAppManagement/policySets/$($currentInstance.Id)/update"

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5221: IntuneAccountProtectionPolicy.Set-TargetResource has hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneAccountProtectionPolicy.Set-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/intents/$($currentPolicy.Identity)/updateSettings"
        
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5222: IntuneDeviceEnrollmentStatusPageWindows10.Set-TargetResource has hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneDeviceEnrollmentStatusPageWindows10.Set-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceEnrollmentConfigurations/$($policy.Id)/assign"
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceEnrollmentConfigurations/$($currentInstance.Id)/assign"
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceEnrollmentConfigurations/$DeviceEnrollmentConfigurationId/setpriority"

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5223: IntuneSettingCatalogCustomPolicyWindows10.Set-TargetResource has hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneSettingCatalogCustomPolicyWindows10.Set-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/configurationPolicies/$DeviceManagementConfigurationPolicyId"

FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5224: IntuneDeviceConfigurationWiredNetworkPolicyWindows10 Functions have hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneSettingCatalogCustomPolicyWindows10 functions call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

Get-DeviceConfigurationPolicyCertificate
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceConfigurations('$DeviceConfigurationPolicyId')/microsoft.graph.windowsWiredNetworkConfiguration/$CertificateName"

DeviceConfigurationPolicyCertificateId
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceConfigurations('$DeviceConfigurationPolicyId')/microsoft.graph.windowsWiredNetworkConfiguration/$CertificateName/`$ref"

Remove-DeviceConfigurationPolicyCertificateId
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceConfigurations('$DeviceConfigurationPolicyId')/microsoft.graph.windowsWiredNetworkConfiguration/$CertificateName/$certificateId/`$ref"
        
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5225: IntuneDeviceConfigurationSCEPCertificatePolicyWindows10 Functions have hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneDeviceConfigurationSCEPCertificatePolicyWindows10 functions call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

Get-DeviceConfigurationPolicyRootCertificate
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceConfigurations('$DeviceConfigurationPolicyId')/microsoft.graph.windows81SCEPCertificateProfile/rootCertificate"

Update-DeviceConfigurationPolicyRootCertificateId
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/deviceConfigurations('$DeviceConfigurationPolicyId')/microsoft.graph.windows81SCEPCertificateProfile/rootCertificate/`$ref"
      
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5226: IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10.Update-DeviceConfigurationGroupPolicyDefinitionValue have hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10.Update-DeviceConfigurationGroupPolicyDefinitionValue call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

Update-DeviceConfigurationGroupPolicyDefinitionValue
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/groupPolicyConfigurations/$DeviceConfigurationPolicyId/updateDefinitionValues"
    
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5227: IntuneAccountProtectionLocalUserGroupMembershipPolicy. Update-DeviceManagementConfigurationPolicy have hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneAccountProtectionLocalUserGroupMembershipPolicy. Update-DeviceManagementConfigurationPolicy call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

Update-DeviceManagementConfigurationPolicy
$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/ConfigurationPolicies/$DeviceManagementConfigurationPolicyId"
    
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5228: IntuneASRRulesPolicyWindows10.Set-TargetResource have hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneASRRulesPolicyWindows10.Set-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/intents/$($currentPolicy.Identity)/updateSettings"
            
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5229: IntuneDiskEncryptionMacOS.Set-TargetResource have hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneDiskEncryptionMacOS.Set-TargetResource call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

$Uri = $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceManagement/intents/$($currentInstance.Id)/updateSettings"
                    
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### LINKED ISSUE #5230: IntuneAppProtectionPolicyiOS Functions have hard coded Commercial Graph endpoints breaking Government
### Description of the issue

IntuneAppProtectionPolicyiOS Functions call to Invoke-MgGraphRequest use a hard coded graph.microsoft.com endpoint which results in failure with EntraID Government tenants.  

Correct call should use $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl for the graph hostname.

Get-IntuneAppProtectionPolicyiOSAssignment
$Url =  $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceAppManagement/iosManagedAppProtections('$IosManagedAppProtectionId')/assignments"

Update-IntuneAppProtectionPolicyiOSAssignment
$Url =  $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceAppManagement/iosManagedAppProtections('$IosManagedAppProtectionId')/assign"
        
Update-IntuneAppProtectionPolicyiOSApp
$Url =  $Global:MSCloudLoginConnectionProfile.MicrosoftGraph.ResourceUrl + "beta/deviceAppManagement/iosManagedAppProtections('$IosManagedAppProtectionId')/targetApps"
        
FYI: All calls to graph.microsoft.com need to be replaced with a cloud specific endpoint and Devs need to stop hard coding graph.microsoft.com

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

_No response_

### Verbose logs showing the problem

_No response_

### Environment Information + PowerShell Version

_No response_

### PR DESCRIPTION
**Pull request by mpoulson**
#### Pull Request (PR) description
Update REST API calls to graph.microsoft.com commercial endpoint to be dynamic based on detected cloud endpoints.  This is to resolve issues where calls to Microsoft Government IL4 (GCC-High, Azure Government IL4) fail.  

#### This Pull Request (PR) fixes the following issues
Fixes #5212 
Fixes #5214 
Fixes #5215 
Fixes #5216 
Fixes #5217
Fixes #5218 
Fixes #5219 
Fixes #5220 
Fixes #5221 
Fixes #5222 
Fixes #5223 
Fixes #5224 
Fixes #5225 
Fixes #5226 
Fixes #5227 
Fixes #5228 
Fixes #5229 
Fixes #5230

### CODE REVIEW

**Comment by mpoulson** [comment]
@microsoft-github-policy-service agree

**Comment by NikCharlebois** [comment]
Thanks @mpoulson I think this will require some additional testing before we can merge. Based on recent tests, the $Global:MsCloudLoginConnectionProfile values are not always exposed to the LCM when running the Start-DSCConfiguration cmdlet. We were discussing bringing the logic to determine the endpoints back into M365DSC instead of MSCloudLogin. Or keep it in there, but not rely on the Global scoped variable.

**Comment by mpoulson** [comment]
Understand.

I did also report a bug in the MSCloudLogin that the tenant_region_sub_scope doesn’t return a value on tenants that are not fully gcc-high licensed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mpoulson** [comment]
@NikCharlebois Do you have any update when we can get these changes for at least using the existing endpoint logic into the product?  The hard-coded graph.microsoft.com endpoints breaks gov support.

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
