### PR TITLE
Fix property naming and settings catalog handling

### LINKED ISSUE #5378: IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy/IntuneSecurityBaselineMicrosoftEdge: Not deploying correctly
### Description of the issue

I had tests that worked correctly but on latest version they're not anymore, these 2 resources deploy *without* errors but looking at the verbose logs looks like not all properties are being sent in the request and then *Test-DscConfiguration* then returns false. Check the 2 attached configuration for both these resources, and the properties that seem to be missing from the request, even though most likely there are more missing but I didn't bother to check.

IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy-IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy_1 -> PasswordAgeDays_AAD
IntuneSecurityBaselineMicrosoftEdge-IntuneSecurityBaselineMicrosoftEdge_1 -> authschemes, MicrosoftEdge_HTTPAuthentication_AuthSchemes

Additionally I also have 5 *IntuneDeviceConfigurationCustomPolicyWindows10* policies and one of them somehow stopped working for some random reason, this is super frustrating.

### Microsoft 365 DSC Version

1.24.1106.3

### Which workloads are affected

Intune

### The DSC configuration

```powershell
IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy "IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy-IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy_1"
        {
            AdministratorAccountName = "Administrator";
            ApplicationId            = $IntuneApplicationId;
            Assignments              = @(
                MSFT_IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicyAssignments{
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    groupId = '053dc89a-be83-411a-bad3-909904b7239e'
                    groupDisplayName = 'DummyGroupExclude'
                }
                MSFT_IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicyAssignments{
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    deviceAndAppManagementAssignmentFilterType = 'include'
                    deviceAndAppManagementAssignmentFilterId = 'd10a0779-7e0b-496f-81a2-f098aa09675f'
                    groupId = 'b0b8fd3f-af2a-453b-be57-80182d599f02'
                    groupDisplayName = 'DummyGroupInclude'
                }
            );
            BackupDirectory          = 1;
            CertificateThumbprint    = $IntuneCertThumbprint;
            Description              = "My revised description";
            DisplayName              = "IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy_1";
            Ensure                   = "Present";
            Identity                 = "cf9b4992-e9cb-4ba0-b657-54977e65cf3a";
            PasswordAgeDays_AAD      = 20;
            TenantId                 = $OrganizationName;
        }
-------------------------------------------------------------------------------------------------------------------------
        IntuneSecurityBaselineMicrosoftEdge "IntuneSecurityBaselineMicrosoftEdge-IntuneSecurityBaselineMicrosoftEdge_1"
        {
            ApplicationId                                           = $IntuneApplicationId;
            Assignments                                             = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    groupDisplayName = 'DummyGroupExclude'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = '053dc89a-be83-411a-bad3-909904b7239e'
                }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    groupDisplayName = 'DummyGroupInclude'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = 'b0b8fd3f-af2a-453b-be57-80182d599f02'
                }
            );
            authschemes                                             = "ntlm,negotiate";
            BasicAuthOverHttpEnabled                                = "0";
            BrowserLegacyExtensionPointsBlockingEnabled             = "1";
            CertificateThumbprint                                   = $IntuneCertThumbprint;
            Description                                             = "IntuneSecurityBaselineMicrosoftEdge_1";
            DisplayName                                             = "IntuneSecurityBaselineMicrosoftEdge_1";
            EdgeEnhanceImagesEnabled                                = "0";
            Ensure                                                  = "Present";
            ExtensionInstallBlocklist                               = "1";
            ExtensionInstallBlocklistDesc                           = @("*");
            Id                                                      = "4c45142a-87b4-4b36-8680-217c0e694780";
            InsecurePrivateNetworkRequestsAllowed                   = "0";
            InternetExplorerIntegrationReloadInIEModeAllowed        = "0";
            InternetExplorerIntegrationZoneIdentifierMhtFileAllowed = "0";
            InternetExplorerModeToolbarButtonEnabled                = "0";
            MicrosoftEdge_HTTPAuthentication_AuthSchemes            = "1";
            NativeMessagingUserLevelHosts                           = "0";
            PreventSmartScreenPromptOverride                        = "1";
            PreventSmartScreenPromptOverrideForFiles                = "1";
            RoleScopeTagIds                                         = @("0");
            SharedArrayBufferUnrestrictedAccessAllowed              = "0";
            SitePerProcess                                          = "1";
            SmartScreenEnabled                                      = "1";
            SmartScreenPuaEnabled                                   = "1";
            SSLErrorOverrideAllowed                                 = "0";
            TenantId                                                = $OrganizationName;
            TyposquattingCheckerEnabled                             = "1";
            WebSQLAccess                                            = "0";
        }
```

### Verbose logs showing the problem

```powershell
N/A
```

### Environment Information + PowerShell Version

```powershell
Win11/PS5.1
```

### PR DESCRIPTION
**Pull request by FabienTschanz**
#### Pull Request (PR) description
This PR fixes three issues with the settings catalog: One was a not handled case of a property name simplification, the second one in the same resource was an incorrectly generated property name, and the last issue in the second resource was a upper vs lower-case property name. 

#### This Pull Request (PR) fixes the following issues
- Fixes #5378

### CODE REVIEW

**Comment by ricmestre** [comment]
I'm still trying to figure out what's going on with *IntuneDeviceConfigurationCustomPolicyWindows10* and I'll test your diff once I'm finished with that one, but at least for *IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy* are you sure that *PasswordAgeDays_AAD* is the only property that needs the casing changed?

Additionally I remember that I already had to change the casing on that specific property a couple of times in my tests to cope with these issues, isn't there a better way to handle this?

**Comment by FabienTschanz** [comment]
The issue is that we use hashtables for the property lookups. Hashtables are case-sensitive regarding their properties, but I can try and check if the casing can be ignored. Unfortunately that will generate a bit of overhead. 

Edit: Yes, I'm sure of it. That's because this is one of the two properties with the name `PasswordAgeDays`, and this one only differs from the other one in its definition id.

**Comment by ricmestre** [comment]
Both seem to be working with this diff 👍 

I'll run all my unit/integration tests again just in case.

**Comment by NikCharlebois** [comment]
@ricmestre were your tests successful?

**Comment by ricmestre** [comment]
Unfortunately I found a couple of issues, of my own not DSC, so I had to fix them in the meantime.

I'm currently running the tests again right now, I'll let you know how it went in a couple of hours.

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
