### PR TITLE
Aad application permissions and roles

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Adds support for API permissions in AADApplication

#### This Pull Request (PR) fixes the following issues
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs or @ThorstenLoeschmann  can one of you two please do a code review? Thanks

**Review by ykuijs — CHANGES_REQUESTED** [review]
Two (equal) small comments/questions

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122#-:-MWexTF3CSCjxkBhU7mN:bzfk7gn)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1, line 515 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122#-MWewvA03pgc3kQ5_N6J:-MWewvA03pgc3kQ5_N6K:bn5y88x) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e4c6d2541921fd156dc68aa334839e5ead93fd7b/Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1#L515)):*
> ```PowerShell
>             Write-Verbose -Message "Permissions differ: $($permissionsDiff | Out-String)"
>             Write-Verbose -Message "Test-TargetResource returned $false"
>             return $false
> ```

Shouldn't we add some logic to create an item in the eventlog??
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1, line 528 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122#-MWex2jG8MNXMcC5AujN:-MWex2jG8MNXMcC5AujO:bn5y88x) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e4c6d2541921fd156dc68aa334839e5ead93fd7b/Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1#L528)):*
> ```PowerShell
>             Write-Verbose -Message "No Permissions exist for the current Azure AD App, but permissions were specified for desired state"
>             Write-Verbose -Message "Test-TargetResource returned $false"
>             return $false
> ```

Shouldn't we add some logic to create an item in the eventlog??

**Review by NikCharlebois — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1, line 515 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122#-MWewvA03pgc3kQ5_N6J:-MWiTH5i3pEdiOC9ZD4D:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e4c6d2541921fd156dc68aa334839e5ead93fd7b/Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1#L515)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Shouldn't we add some logic to create an item in the eventlog??
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1, line 528 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122#-MWex2jG8MNXMcC5AujN:-MWiTHr_4eG1ftC1UTrs:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/e4c6d2541921fd156dc68aa334839e5ead93fd7b/Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1#L528)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Shouldn't we add some logic to create an item in the eventlog??
</blockquote></details>

Done.

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1122#-:-MX2Ezc64vkPJA8gtOuY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
