### PR TITLE
Get mg device management device configuration changes   #3082

### LINKED ISSUE #3082: IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator and IntuneDeviceConfigurationPolicyiOS - Packet size exceeded error
#### Details of the scenario you tried and the problem that is occurring
When running a test-dscconfiguration on either of the above configurations an error is received:

The WS-Management service cannot process the request. The computed response packet size (992180) exceeds the maximum    envelope size that is allowed (512000).
 
Using DSCDebug I've seen that the error occurs when the below command is run:
$getValue = Get-MgDeviceManagementDeviceConfiguration `
                -ErrorAction Stop | Where-Object `
                -FilterScript { `
                    $_.DisplayName -eq "$($DisplayName)" `
            }

I think the problem occurs because the command is returning all the objects and then filtering it locally - leading to a pagesize error.
I think this may be specific to my environment as I'm unable to amend the MaxEnvelopeSizekb value this appears to relate to.

Despite this, I think the workaround I've found for it might be appropriate for the module as it's used in other configurations which don't generate errors for me.

#### Verbose logs showing the problem
The WS-Management service cannot process the request. The computed response packet size (992180) exceeds the maximum    envelope size that is allowed (512000).                                                                                     + CategoryInfo          : LimitsExceeded: (root/Microsoft/...gurationManager:String) [], CimException                   + FullyQualifiedErrorId : HRESULT 0x80338048                                                                            + PSComputerName        : localhost      
#### Suggested solution to the issue

My suggestion is to replace the lines:
$getValue = Get-MgDeviceManagementDeviceConfiguration `
                -ErrorAction Stop | Where-Object `
                -FilterScript { `
                    $_.DisplayName -eq "$($DisplayName)" `
            }

with:
$getValue = Get-MgDeviceManagementDeviceConfiguration -Filter "DisplayName eq '$Displayname'"

The command is also present on another line where the filter is on the $id value - that would need the same changes

This is the way the filtering is performed on other configurations such as IntuneDeviceConfigurationPolicyWindows10

Although I've only tried the above mentioned configurations it looks like there are a few configurations of the type IntuneDeviceConfigurationPolicyxxx where this could be amended

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator a1b23c45-d678-901e-23fa-bc456d7890e1
        {
            ApplicationId                                  = $ConfigurationData.NonNodeData.ApplicationId;
            ApplicationSecret                              = New-Object System.Management.Automation.PSCredential ('ApplicationSecret', (ConvertTo-SecureString $ConfigurationData.NonNodeData.ApplicationSecret -AsPlainText -Force));
            AppsBlockClipboardSharing                      = $False;
            AppsBlockCopyPaste                             = $False;
            AppsBlockYouTube                               = $True;
            AppsInstallAllowList                           = @(
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Azure Information Protection'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.ipviewer'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Edge'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.emmx'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Excel'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.office.excel'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Microsoft SharePoint'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.sharepoint'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Microsoft Teams'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.teams'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'OneDrive'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.skydrive'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'OneNote'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.office.onenote'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Outlook'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.office.outlook'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'PowerPoint'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.office.powerpoint'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Skype for Business'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.office.lync15'
            }
                MSFT_MicrosoftGraphapplistitem{
                    name = 'Word'
                    publisher = 'Microsoft Corporation'
                    appId = 'com.microsoft.office.word'
            });
            Assignments                                    = 
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = '12345678-90ab-cdef-1234-1234567890ab'
            };
            BluetoothBlocked                               = $False;
            CameraBlocked                                  = $False;
            CellularBlockDataRoaming                       = $False;
            CellularBlockMessaging                         = $False;
            CellularBlockVoiceRoaming                      = $False;
            CellularBlockWiFiTethering                     = $False;
            CompliantAppListType                           = "none";
            DateAndTimeBlockChanges                        = $True;
            Description                                    = "TEST TEST TEST TEST";
            DeviceSharingAllowed                           = $False;
            DiagnosticDataBlockSubmission                  = $False;
            DisplayName                                    = "Test Policy Android Device Management Device Configuation";
            Ensure                                         = "Present";
            FactoryResetBlocked                            = $True;
            GoogleAccountBlockAutoSync                     = $True;
            GooglePlayStoreBlocked                         = $False;
            Id                                             = "bb76ad2b-ab7f-43d1-59bd-a2d665b32aa3";
            KioskModeBlockSleepButton                      = $False;
            KioskModeBlockVolumeButtons                    = $False;
            LocationServicesBlocked                        = $False;
            NfcBlocked                                     = $False;
            PasswordBlockFingerprintUnlock                 = $False;
            PasswordBlockTrustAgents                       = $True;
            PasswordExpirationDays                         = 60;
            PasswordMinimumLength                          = 8;
            PasswordMinutesOfInactivityBeforeScreenTimeout = 15;
            PasswordPreviousPasswordBlockCount             = 12;
            PasswordRequired                               = $True;
            PasswordRequiredType                           = "alphanumeric";
            PasswordSignInFailureCountBeforeFactoryReset   = 5;
            PowerOffBlocked                                = $False;
            RequiredPasswordComplexity                     = "none";
            ScreenCaptureBlocked                           = $True;
            SecurityRequireVerifyApps                      = $False;
            StorageBlockGoogleBackup                       = $True;
            StorageBlockRemovableStorage                   = $True;
            StorageRequireDeviceEncryption                 = $True;
            StorageRequireRemovableStorageEncryption       = $True;
            TenantId                                       = $ConfigurationData.NonNodeData.TenantId;
            VoiceAssistantBlocked                          = $True;
            VoiceDialingBlocked                            = $False;
            WebBrowserBlockAutofill                        = $False;
            WebBrowserBlocked                              = $True;
            WebBrowserBlockJavaScript                      = $False;
            WebBrowserBlockPopups                          = $False;
            WebBrowserCookieSettings                       = "browserDefault";
            WiFiBlocked                                    = $False;
        }
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

### PR DESCRIPTION
**Pull request by menswearUK**
#### Pull Request (PR) description

It looks like there are a few different ways that usage of the command Get-MgDeviceManagementDeviceConfiguration has been implemented in the configurations.

some of them are using the graph cmdlet switches to filter before the object is returned and some are collecting all objects and  filtering one they are returned.  I've amended all the usages to use the  -Filter or -DeviceConfigurationId $id switches.

This addresses a specific problem I've been having with a couple of configurations but I think it's an appropriate change as it seems a more efficient way of running this command.

I've also added a filter of the output on AdditionalProperties.'@odata.type' - I did this as it's the way it's been implemented already on other configurations - it will filter out different configuration types which may happen to have the same display name.

#### This Pull Request (PR) fixes the following issues

Fixes #3082

### CODE REVIEW

**Comment by ykuijs** [comment]
Can you please update from the Dev branch? There are a new renames to resources (corrected typos) that now are causing conflicts.

**Comment by menswearUK** [comment]
Hi @ykuijs ,
I've resolved the conflicts now and it seems to have gone through the tests ok this time.  I might struggle to make any changes to the code over the next week or so but I'll do the best I can to complete any changes you need as quickly as possible

**Review by ykuijs — COMMENTED** [review]
I am fine with these changes. Just wondering what @William-Francillette thinks about these changes.

This might also have to get updated in the DRG as well.

**Comment by William-Francillette** [comment]
@ykuijs it makes sense - the server side filtering has already been implemented in the DRG and  adding the policy type filtering will prevent further issue with policy with duplicated names.
I'll update the DRG as well to add the @odata.type  in the filter 

Good job 💪

**Comment by William-Francillette** [comment]
@ykuijs I've updated the DRG to type the filter when retrieving a policy with displayName PR #3118

**Comment by ykuijs** [comment]
@menswearUK, three unit tests are failing. Can you please have a look?

You can run these locally:
- Make sure you have Pester v5.4.0 installed
- Open an elevated PowerShell window
- Go to the repo root folder
- Run `Import-Module .\Tests\TestHarness.psm1`
- Run `Invoke-QualityChecksHarness`
- Run `Invoke-TestHarness`

**Comment by ykuijs** [comment]
@menswearUK, can you have a look at fixing the unit tests?

**Comment by menswearUK** [comment]
@ykuijs Sorry for the delay, I was away last week and wasn't able to get any free time to look at this.
I've addressed the conflicts and spotted the errors in the 3 files - I also updated one of the test files as it was failing on the reverseDSC tests.  The test for those files are working for me now

**Review by ykuijs — APPROVED** [review]
LGTM

**Pull request merged**
