### PR TITLE
Update to M365DSCReport.psm1 due to typo in script

### PR DESCRIPTION
**Pull request by Harleycox**
Correcting a typo for the name of the Security & compliance.png file the M365DSCReport.psm1 script when it tries to pull it. Essentially it was missing an 'i' in compliance which meant it errored out every time it tries to call the .png file.

### CODE REVIEW

**Comment by ykuijs** [comment]
@Harleycox, great spot. One ask: Could you also add an entry in the [changelog](https://github.com/microsoft/Microsoft365DSC/blob/Dev/CHANGELOG.md) for this change. Please add this to the MISC header.

**Comment by ykuijs** [comment]
I have seen the 2nd PR you have submitted. Please update this PR with that change. Simply make the change, commit to the same branch and push the new commit to GitHub. That will automatically add the commit to this PR.

I will close the 2nd PR.

**Comment by Harleycox** [comment]
> I have seen the 2nd PR you have submitted. Please update this PR with that change. Simply make the change, commit to the same branch and push the new commit to GitHub. That will automatically add the commit to this PR.
> 
> I will close the 2nd PR.

Hi Ykuijs, apologies! Frist time committing, this should hopefully have now been done in the correct way. Please let me know if not.

**Review by ykuijs — APPROVED** [review]
LGTM

**Comment by ykuijs** [comment]
Thanks for the update @Harleycox! Please check-out the license agreement message earlier in the message thread and acknowledge if you are ok with it. After that we can merge the PR.

**Comment by Harleycox** [comment]
Read and confirmed

@microsoft-github-policy-service agree

**Comment by ssoabx** [comment]
Oh, I submitted a duplicate, was searching for SecurityAndCompliance and saw nothing. Thanks for fixing :)

**Comment by ykuijs** [comment]
No problem. Your contribution is very much appreciated. Better submit a duplicate than not fixing the issue at all 😉

**Pull request merged**
