### PR TITLE
New Encoding Helper Module

### LINKED ISSUE #904: Issue with New-M365DSCDeltaReport
#### Details of the scenario you tried and the problem that is occurring
New-M365DSCDeltaReport -Source "D:\Folder1\SB\SBTenantExtract.ps1" -Destination "D:\Folder1\PPE\PPETenantExtract.ps1" -OutputPath "D:\Folder1\Microsoft365DSC\Delta.html"

#### Verbose logs showing the problem
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:305 char:13
+             $drift = @{
+             ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:305 char:13
+             $drift = @{
+             ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Get-IconPath : Cannot bind argument to parameter 'ResourceName' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:669 char:52
+ ...         $iconPath = Get-IconPath -ResourceName $resource.ResourceName
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-IconPath], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-IconPath

Get-IconPath : Cannot bind argument to parameter 'ResourceName' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:669 char:52
+ ...         $iconPath = Get-IconPath -ResourceName $resource.ResourceName
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-IconPath], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-IconPath

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
We have used the below command to generate report of existing configuration from tenant and then ran the same cmdlet for a different tenant and tried to compare the difference in configurations between both the tenants

Export-M365DSCConfiguration -Quiet -Path "D:\Folder1\" -FileName "PPETenantExtract.ps1" -ConfigurationName 
"PPETenantConfig" -Workloads @("SPO","TEAMS","OD","SC","PP","O365","EXO") -GlobalAdminAccount (Get-Credential)

# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19846.amd64fre.winblue_ltsb_escrow.200923-1735
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

Name              : Microsoft365DSC
Path              : C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\Microsoft365DSC.psd1
Description       : This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online,
                    Exchange, Teams, etc.
ModuleType        : Manifest
Version           : 1.20.1104.1

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Introduced a new M365DSCStringEncoding module to ensure exported content is properly encoded and that no special characters will break the structure of the exported DSC content.

#### This Pull Request (PR) fixes the following issues
- Fixes #904

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/908)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs Can you do the review? Thanks

**Review by ykuijs — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/908)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/Modules/EncodingHelpers/M365DSCStringEncoding.psm1, line 76 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/908#-MMMnNCt-8-o4ej-PeKp:-MMMnNCu8y5hBiGpW5UF:b2zhrfw) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6d34bc42ab631ad28d666ec943cec8d0379fa51a/Modules/Microsoft365DSC/Modules/EncodingHelpers/M365DSCStringEncoding.psm1#L76)):*
> ```PowerShell
> 
>     return $newProperties
> }
> ```

Picky mode: Maybe end with an empty line?

**Review by ykuijs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/908#-:-MMMnb3TArVP7cX1dC4c:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ykuijs)

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/908#-:-MMN0JIc7FJLWLRGwUi6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
