### PR TITLE
Fix App Configuration Device Assignments and MOF Compilation

### LINKED ISSUE #4724: IntuneAppConfigurationDevicePolicy: Not working
### Description of the issue

I have 2 policies of this kind, one for Android and another for iOS and they have 2 different problems. I'm able to export them but:

Cannot apply the Android policy to a different tenant, the error message like whenever something bad happens in Graph side is not conclusive, and no, there's nothing additional in event viewer to debug this further.

For the iOS policy it's easy, the module is calling *Get-M365DSCDRGComplexTypeToString* on *MicrosoftGraphappConfigurationSettingItem1* instead of *MicrosoftGraphappConfigurationSettingItem* as referred in the schema so it complains when trying to compile the blueprint to MOF that that type doesn't exist. After changing the blueprint manually to the correct type I was able to compile it and apply the policy to another tenant but then there's another problem, *Test-DscConfiguration* returns false, it looks like *Assignments* is not working, this is because *groupDisplayName* is not being exported, only the *groupId*, and of course won't work when applying to a different tenant since those Ids don't exist in the target tenant.

@FabienTschanz Could you please have a look?

### Microsoft 365 DSC Version

1.24.529.1

### Which workloads are affected

Intune

### The DSC configuration

```powershell
IntuneAppConfigurationDevicePolicy "IntuneAppConfigurationDevicePolicy-Apple iOS - Outlook Configuration Profile"
        {
            Assignments          = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = '5f193407-78ae-4e74-8c36-ed2db0bcad90'
                }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = 'fd028132-7fb9-4f7c-b3d9-8767e2508b0b'
                }
            );
            Credential           = $Credscredential;
            Description          = "";
            DisplayName          = "Apple iOS - Outlook Configuration Profile";
            Ensure               = "Present";
            Id                   = "838c7429-3336-4e70-a896-807e0561b8ec";
            RoleScopeTagIds      = @("0");
            Settings             = @(
                MSFT_MicrosoftGraphappConfigurationSettingItem1{
                    AppConfigKey = 'com.microsoft.outlook.EmailProfile.AccountType'
                    AppConfigKeyType = 'stringType'
                    AppConfigKeyValue = 'ModernAuth'
                }
                MSFT_MicrosoftGraphappConfigurationSettingItem1{
                    AppConfigKey = 'com.microsoft.outlook.EmailProfile.EmailUPN'
                    AppConfigKeyType = 'stringType'
                    AppConfigKeyValue = '{{userprincipalname}}'
                }
                MSFT_MicrosoftGraphappConfigurationSettingItem1{
                    AppConfigKey = 'com.microsoft.outlook.EmailProfile.EmailAddress'
                    AppConfigKeyType = 'stringType'
                    AppConfigKeyValue = '{{mail}}'
                }
                MSFT_MicrosoftGraphappConfigurationSettingItem1{
                    AppConfigKey = 'com.microsoft.outlook.Mail.FocusedInbox'
                    AppConfigKeyType = 'booleanType'
                    AppConfigKeyValue = 'true'
                }
                MSFT_MicrosoftGraphappConfigurationSettingItem1{
                    AppConfigKey = 'com.microsoft.outlook.Contacts.LocalSyncEnabled'
                    AppConfigKeyType = 'booleanType'
                    AppConfigKeyValue = 'true'
                }
                MSFT_MicrosoftGraphappConfigurationSettingItem1{
                    AppConfigKey = 'com.microsoft.outlook.Mail.BlockExternalImagesEnabled'
                    AppConfigKeyType = 'booleanType'
                    AppConfigKeyValue = 'false'
                }
            );
            TargetedMobileApps   = @("ce0d9513-9e59-47d3-af47-5599f85c4104");
        }
        IntuneAppConfigurationDevicePolicy "IntuneAppConfigurationDevicePolicy-Android Work Profile - Outlook Configuration Profile"
        {
            Assignments          = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = '832e341f-af79-43e4-bfcb-aa31f2fb4112'
                }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = 'e2ac5083-d70c-4bd5-9b17-5e9bd5c23372'
                }
            );
            ConnectedAppsEnabled = $False;
            Credential           = $Credscredential;
            Description          = "";
            DisplayName          = "Android Work Profile - Outlook Configuration Profile";
            Ensure               = "Present";
            Id                   = "f2414a0b-9d79-4bff-b8b4-ed968fc6feb2";
            PackageId            = "app:com.microsoft.office.outlook";
            PayloadJson          = "eyJraW5kIjoiYW5kcm9pZGVudGVycHJpc2UjbWFuYWdlZENvbmZpZ3VyYXRpb24iLCJwcm9kdWN0SWQiOiJhcHA6Y29tLm1pY3Jvc29mdC5vZmZpY2Uub3V0bG9vayIsIm1hbmFnZWRQcm9wZXJ0eSI6W3sia2V5IjoiY29tLm1pY3Jvc29mdC5vdXRsb29rLkVtYWlsUHJvZmlsZS5BY2NvdW50VHlwZSIsInZhbHVlU3RyaW5nIjoiTW9kZXJuQXV0aCJ9LHsia2V5IjoiY29tLm1pY3Jvc29mdC5vdXRsb29rLkVtYWlsUHJvZmlsZS5FbWFpbFVQTiIsInZhbHVlU3RyaW5nIjoie3t1c2VycHJpbmNpcGFsbmFtZX19In0seyJrZXkiOiJjb20ubWljcm9zb2Z0Lm91dGxvb2suRW1haWxQcm9maWxlLkVtYWlsQWRkcmVzcyIsInZhbHVlU3RyaW5nIjoie3ttYWlsfX0ifSx7ImtleSI6ImNvbS5taWNyb3NvZnQub3V0bG9vay5NYWlsLkZvY3VzZWRJbmJveCIsInZhbHVlQm9vbCI6dHJ1ZX0seyJrZXkiOiJjb20ubWljcm9zb2Z0Lm91dGxvb2suQ29udGFjdHMuTG9jYWxTeW5jRW5hYmxlZCIsInZhbHVlQm9vbCI6dHJ1ZX0seyJrZXkiOiJjb20ubWljcm9zb2Z0Lm91dGxvb2suTWFpbC5CbG9ja0V4dGVybmFsSW1hZ2VzRW5hYmxlZCIsInZhbHVlQm9vbCI6ZmFsc2V9XX0=";
            ProfileApplicability = "default";
            RoleScopeTagIds      = @("0");
            TargetedMobileApps   = @("386d347e-51dd-419c-85c1-02918f07538b");
        }
```


### Verbose logs showing the problem

```powershell
VERBOSE: [  REDACTED]:                            [[IntuneAppConfigurationDevicePolicy]IntuneAppConfigurationDevicePolicy-Android Work Profile - Outlook Configuration Profile] Creating an Intune App          Configuration Device Policy with DisplayName {Android Work Profile - Outlook Configuration Profile}
[BadRequest] :
{
"_version": 3,
"Message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 1a34666b-2d89-4020-a16b-170a1732f322 - Url:
2405/StatelessAppMetadataFEService/deviceAppManagement/mobileAppConfigurations?api-version=5024-03-08",
"CustomApiErrorPhrase": "",
"RetryAfter": null,
"ErrorSourceService": "",
"HttpHeaders":
"{}"                                                                                                                                                                                             }
+ CategoryInfo          : InvalidOperation: ({ Headers = , b...Configuration }:) [], CimException
+ FullyQualifiedErrorId : BadRequest,Microsoft.Graph.Beta.PowerShell.Cmdlets.NewMgBetaDeviceAppManagementMobileAppConfiguration_Create
+ PSComputerName        : localhost
VERBOSE: [  REDACTED]: LCM:  [ End    Set      ]  [[IntuneAppConfigurationDevicePolicy]IntuneAppConfigurationDevicePolicy-Android Work Profile - Outlook Configuration Profile]  in 1.5980 seconds.             The PowerShell DSC resource '[IntuneAppConfigurationDevicePolicy
IntuneAppConfigurationDevicePolicy-Android Work Profile - Outlook Configuration Profile' with SourceInfo                                         'C:\temp\dsc\IntuneAppConfigurationDevicePolicy.ps1::34::9::IntuneAppConfigurationDevicePolicy' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are     logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
CategoryInfo          : InvalidOperation: (:) [], CimException
+ FullyQualifiedErrorId : NonTerminatingErrorFromProvider                                                                                                                                                         + PSComputerName        : localhost
VERBOSE: [  REDACTED]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
+ CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
+ FullyQualifiedErrorId : MI RESULT 1
+ PSComputerName        : localhost
```


### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise                                                                                                                                                            OsOperatingSystemSKU : EnterpriseEdition                                                                                                                                                                          OsArchitecture       : 64-bit                                                                                                                                                                                     WindowsVersion       : 2009                                                                                                                                                                                       WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250                                                                                                                                                    OsLanguage           : en-US                                                                                                                                                                                      OsMuiLanguages       : {en-US, en-GB}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                Name                           Value                                                                                                                                                                              ----                           -----                                                                                                                                                                              PSVersion                      5.1.22621.2506                                                                                                                                                                     PSEdition                      Desktop                                                                                                                                                                            PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                            BuildVersion                   10.0.22621.2506                                                                                                                                                                    CLRVersion                     4.0.30319.42000                                                                                                                                                                    WSManStackVersion              3.0                                                                                                                                                                                PSRemotingProtocolVersion      2.3                                                                                                                                                                                SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by FabienTschanz**
#### Pull Request (PR) description
This pull request adds the `groupDisplayName` property to the export and fixes an issue with the MOF compilation. Additionally, it improves the comparison of Intune assignments for more properties, including `collectionId`, `deviceAndAppManagementAssignmentFilterType` and `deviceAndAppManagementAssignmentFilterId`.

#### This Pull Request (PR) fixes the following issues
- Fixes #4724

### CODE REVIEW

**Comment by FabienTschanz** [comment]
@NikCharlebois The unit tests failed because the server threw a Error 500. The code passed the tests.

**Comment by FabienTschanz** [comment]
@NikCharlebois Sorry for the commit spam and the recent changes. There were some irregularities that appeared, and I forgot to set the PR to draft.

**Comment by NikCharlebois** [comment]
Let me know when this is ready to be reviewed and remove the draft mention from the title then as well. Thanks

**Comment by ricmestre** [comment]
@nikcharlebois I already reviewed it and tested it successfully, it solves all my issues I reported on #4724, the conversion from JWT to JSON can happen later.

**Comment by FabienTschanz** [comment]
@NikCharlebois Draft is removed

**Pull request merged**
