### PR TITLE
Add support for multiple Rank / group in the same configuration.

### PR DESCRIPTION
**Pull request by sandrola**
#### Pull Request (PR) description
Fix Issue with duplicated Key value in exported configuration
#### This Pull Request (PR) fixes the following issues
Fixes #3057

### CODE REVIEW

**Comment by ykuijs** [comment]
@sandrola, this PR looks like a duplicate of #3057. Is that true?

**Comment by sandrola** [comment]
Ok, I have see it now, but in #3057 the Groupid is now a Key, this eliminate the possibility to use the same configuration for multiple Tenant using the Group Displayname.

**Comment by andikrueger** [comment]
Thank you for this PR and the second look at this issue. I would take the discussion back to the initial issue #3057 and hold both PRs until we do have a common understanding.

**Comment by NikCharlebois** [comment]
We need to make sure that users writing the configuration manually aren't forced providing an ID, which doesn't exist just for configurations to compile. My recommendation is to put #3057 on hold and consider merging this PR here instead.

**Comment by ykuijs** [comment]
#3057 was merged. Closing this PR

**Pull request closed without merging**
