### PR TITLE
Add default Ensure value if not present

### LINKED ISSUE #5085: Resources using Test-M365DSCParameterState do not support default Ensure value when using -DesiredValues $PSBoundParameters
### Description of the issue

When trying to use EXODistributionGroup to create a resource without specifying 'Ensure', Test-TargetResource always returns True even if the resource doesn't exist

It looks like this is because Test-M365DSCParameterState is called with -DesiredValues $PSBoundParameters, which of course does *not* include parameters which have the 'default value' - therefore the value is not tested:

https://github.com/microsoft/Microsoft365DSC/blob/ca59c6cec43e920714a85d37a9e7e1fdd18a1c5f/Modules/Microsoft365DSC/DSCResources/MSFT_EXODistributionGroup/MSFT_EXODistributionGroup.psm1#L983

This seems to affect many resources using this template style (e.g. ADGroup)

Not sure the best way to fix. Perhaps $PSBoundParameters could be modified to always add Ensure = $Ensure?

### Microsoft 365 DSC Version

dev

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
Configuration Example
{
    param(
        [Parameter()]
        [System.String]
        $ApplicationId,

        [Parameter()]
        [System.String]
        $TenantId,

        [Parameter()]
        [System.String]
        $CertificateThumbprint
    )
    Import-DscResource -ModuleName Microsoft365DSC

    node localhost
    {
        EXODistributionGroup 'Distribution Group Name'
        {
            Alias                              = "DistributionGroupName";
            Identity                           = "Distribution Group Name";
            Name                               = "Distribution Group Name";
            PrimarySmtpAddress                 = "DistributionGroupName@contoso.onmicrosoft.com";
            Type                  = 'Security'
            ApplicationId         = $ApplicationId
            TenantId              = $TenantId
            CertificateThumbprint = $CertificateThumbprint
        }
    }
}
```

### Verbose logs showing the problem

```powershell
VERBOSE: [HOSTNAME]: LCM:  [ Start  Resource ]  [[EXODistributionGroup]Distribution Group Name::[DomainController]HOSTNAME]
VERBOSE: [HOSTNAME]: LCM:  [ Start  Test     ]  [[EXODistributionGroup]Distribution Group Name::[DomainController]HOSTNAME]
VERBOSE: [HOSTNAME]:                            [[EXODistributionGroup]Distribution Group Name::[DomainController]HOSTNAME] Testing Distribution Group configuration for {Distribution Group Name}
VERBOSE: [HOSTNAME]:                            [[EXODistributionGroup]Distribution Group Name::[DomainController]HOSTNAME] Getting configuration of Distribution Group for Distribution Group Name
VERBOSE: [HOSTNAME]:                            [[EXODistributionGroup]Distribution Group Name::[DomainController]HOSTNAME] Current Values: Alias=DistributionGroupName
ApplicationId=***
CertificateThumbprint=***
Ensure=Absent
Identity=Distribution Group Name
Name=Distribution Group Name
PrimarySmtpAddress=DistributionGroupName@contoso.onmicrosoft.com
TenantId=***
Type=Security
Verbose=True
VERBOSE: [HOSTNAME]:                            [[EXODistributionGroup]Distribution Group Name::[DomainController]HOSTNAME] Target Values: Alias=DistributionGroupName
ApplicationId=***
CertificateThumbprint=***
Identity=Distribution Group Name
Name=Distribution Group Name
PrimarySmtpAddress=DistributionGroupName@contoso.onmicrosoft.com
TenantId=***
Type=Security
Verbose=True
VERBOSE: [HOSTNAME]:                            [[EXODistributionGroup]Distribution Group Name::[DomainController]HOSTNAME] Test-TargetResource returned True
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.17763.6189
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.17763.6189
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### PR DESCRIPTION
**Pull request by FabienTschanz**
#### Pull Request (PR) description
This PR adds the default `Ensure` property value `Present` if it is not specified in the desired values and the resource is not a single instance element. 

#### This Pull Request (PR) fixes the following issues
- Fixes #5085 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource parameter descriptions added/updated in the schema.mof.
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource settings.json file contains all required permissions.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

### CODE REVIEW

**Comment by FabienTschanz** [comment]
@Borgquite Do you have the time to test it with your usecase?

**Review by ykuijs — APPROVED** [review]
LGTM

**Comment by ykuijs** [comment]
Great solution! I will merge this PR when @Borgquite confirms this solution solves the issue

**Comment by Borgquite** [comment]
Will do! Give me a day or so.

**Comment by ykuijs** [comment]
Our next release is Wednesday next week, so a day is no problem 😉

**Comment by FabienTschanz** [comment]
@Borgquite Any updates on the testing? Wednesday is just around the corner, would be awesome if we could integrate that.

**Comment by Borgquite** [comment]
@FabienTschanz Hey - sorry, stuff got in the way (although I'm still happy to do this).

On paper it looks fine so if you want to integrate I can get back to you if it's still a problem. I'll see if I can get round to it this afternoon (but keep getting asked to come into meetings... sigh)

**Review by NikCharlebois — APPROVED** [review]

**Comment by Borgquite** [comment]
@FabienTschanz @ykuijs Can see this has already been merged, but FWIW - just tested here and LGTM :) Thanks!

**Pull request merged**
