### PR TITLE
IntuneDeviceCompliancePolicyiOS

### LINKED ISSUE #353: IntuneDeviceCompliancePolicy
### Description
We want to fully setup new O365 tenants using DSC and as Intune is part of O365 we would like to see it include here too.     
The DevicePolicy should be seen here as the biggest pain point in a bigger effort to enable Intune configurations.

### Proposed properties
```

- description
- displayName
- passwordRequired
- passwordBlockSimple
- passwordRequiredToUnlockFromIdle
- passwordMinutesOfInactivityBeforeLock
- passwordExpirationDays
- passwordMinimumLength
- passwordMinimumCharacterSetCount
- passwordRequiredType
- passwordPreviousPasswordBlockCount
- requireHealthyDeviceReport
- osMinimumVersion
- osMaximumVersion
- mobileOsMaximumVersion
- mobileOsMaximumVersion
- earlyLaunchAntiMalwareDriverEnabled
- bitLockerEnabled
- secureBootEnabled
- codeIntegrityEnabled
- storageRequireEncryption
- activeFirewallRequired
- defenderEnabled
- defenderVersion
- signatureOutOfDate
- rtpEnabled
- antivirusRequired
- antiSpywareRequired
- deviceThreatProtectionEnabled
- deviceThreatProtectionRequiredSecurityLevel
- configurationManagerComplianceRequired
- tpmRequired
- validOperatingSystemBuildRanges
```

### PR DESCRIPTION
**Pull request by luigilink**
#### Pull Request (PR) description
This PR concerns the new Dsc Resource IntuneDeviceCompliancePolicyiOS

#### This Pull Request (PR) fixes the following issues
    - Fixes #353

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/958)

### CODE REVIEW

**Comment by luigilink** [comment]
It seems that the Unit Test check doesn't work. Do I have to change something in the code ?

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Awesome job on this one. Just two minor items in toh Export to fix.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/958#-:-MNhXxA17YF6a4RijNVO:bwtzjbz)* status: all files reviewed, 2 unresolved discussions (waiting on @luigilink)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1, line 426 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/958#-MNhXobjAW1NJDQrs1-m:-MNhXobjAW1NJDQrs1-n:brftuh9) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/4cdce6aafe74e0e75334d9d0605e79fbe2e08d75/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1#L426)):*
> ```PowerShell
>     try
>     {
>         [array]$configDeviceiOsPolicies = Get-DeviceManagement_DeviceCompliancePolicies -ErrorAction Stop
> ```

Add a filter to only get the iOS ones
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1, line 440 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/958#-MNhXiCb9M7q9Tt4hHe3:-MNhXiCcApKfysLbh5Hb:bdttszo) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/4cdce6aafe74e0e75334d9d0605e79fbe2e08d75/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1#L440)):*
> ```PowerShell
>             $result = Get-TargetResource @params
>             $result.GlobalAdminAccount = Resolve-Credentials -UserName "globaladmin"
>             $content += "        IntuneAppConfigurationPolicy " + (New-Guid).ToString() + "`r`n"
> ```

Update for IntuneDeviceCompliancePolicyiOS

**Review by luigilink — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/958)* status: all files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1, line 426 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/958#-MNhXobjAW1NJDQrs1-m:-MNhfuFD36ELs1iy337q:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/4cdce6aafe74e0e75334d9d0605e79fbe2e08d75/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1#L426)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Add a filter to only get the iOS ones
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1, line 440 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/958#-MNhXiCb9M7q9Tt4hHe3:-MNhfuqkCnAZKBr8Yjco:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/4cdce6aafe74e0e75334d9d0605e79fbe2e08d75/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyiOs/MSFT_IntuneDeviceCompliancePolicyiOs.psm1#L440)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Update for IntuneDeviceCompliancePolicyiOS
</blockquote></details>

Done.

**Comment by luigilink** [comment]
I have tests failed on EXOApplicationAccessPolicy but not on new test file any idea ?

**Review by NikCharlebois — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/958#-:-MNhuy2KDv2_kTf5PHAs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @luigilink)

**Pull request merged**
