### PR TITLE
Mailbox calendar configuration

### PR DESCRIPTION
**Pull request by kasaxena5**

### CODE REVIEW

**Comment by kasaxena5** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by ykuijs** [comment]
Hi @kasaxena5, thanks for your PR. Can you please make sure an entry is added in the Changelog under the Unreleased section (in alphabetical order please)?

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Add changelog entry

**Comment by kasaxena5** [comment]
Added Change Logs

**Pull request merged**
