### PR TITLE
MSFT_IntuneAppProtectionPolicyAndroid.psm1 remove Get-M365DSCIntuneAppProtectionPolicyAndroid function and fix #1955

### LINKED ISSUE #1955: MSFT_IntuneAppProtectionPolicyAndroid.schema.mof and MSFT_IntuneAppProtectionPolicyAndroid.ps1 have different properties
As mentioned in the discussion below, there is an issue with the IntuneAppProtectionPolicyAndroid resource. The schema and the properties within the ps1 are different. This causes the exported configuration to fail during compilation.

MSFT_IntuneAppProtectionPolicyAndroid.schema needs to be adjusted to reflect the needed properties.

### Discussed in https://github.com/microsoft/Microsoft365DSC/discussions/1947

<div type='discussions-op-text'>

<sup>Originally posted by **MichielBouman** May 17, 2022</sup>
I have successfully exported our Intune configuration and saved in M365TenantConfig.ps1. When I run the script I get a number of errors: 

At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:526 char:114
+ ...    = @(System.Collections.Generic.Dictionary`2[System.String,System.O ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:616 char:114
+ ...    = @(System.Collections.Generic.Dictionary`2[System.String,System.O ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:768 char:114
+ ...    = @(System.Collections.Generic.Dictionary`2[System.String,System.O ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:1306 char:121
+ ...      = System.Collections.Generic.Dictionary`2[System.String,System.O ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:1442 char:121
+ ...      = System.Collections.Generic.Dictionary`2[System.String,System.O ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:1491 char:121
+ ...      = System.Collections.Generic.Dictionary`2[System.String,System.O ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:1677 char:121
+ ...      = System.Collections.Generic.Dictionary`2[System.String,System.O ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:71 char:13
+             IsAssigned                              = $True;
+             ~~~~~~~~~~
The member 'IsAssigned' is not valid. Valid members are
'AllowedDataStorageLocations', 'AllowedInboundDataTransferSources', 'AllowedOutboundClipboardSharingLevel', 'AllowedOutboundDataTransferDestinations', 'ApplicationId', 'ApplicationSecret', 'Apps', 'Assignments',
'CertificateThumbprint', 'ContactSyncBlocked', 'Credential', 'DataBackupBlocked', 'DependsOn', 'Description', 'DeviceComplianceRequired', 'DisableAppPinIfDevicePinIsSet', 'DisplayName', 'Ensure', 'ExcludedGroups',
'FingerprintBlocked', 'ManagedBrowserToOpenLinksRequired', 'MaximumPinRetries', 'MinimumPinLength', 'OrganizationalCredentialsRequired', 'PeriodBeforePinReset', 'PeriodOfflineBeforeAccessCheck',
'PeriodOfflineBeforeWipeIsEnforced', 'PeriodOnlineBeforeAccessCheck', 'PinCharacterSet', 'PinRequired', 'PrintBlocked', 'PsDscRunAsCredential', 'SaveAsBlocked', 'SimplePinBlocked', 'TenantId'.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:72 char:13
+             ManagedBrowser                          = "microsoftEdge" ...
+             ~~~~~~~~~~~~~~
The member 'ManagedBrowser' is not valid. Valid members are
'AllowedDataStorageLocations', 'AllowedInboundDataTransferSources', 'AllowedOutboundClipboardSharingLevel', 'AllowedOutboundDataTransferDestinations', 'ApplicationId', 'ApplicationSecret', 'Apps', 'Assignments',
'CertificateThumbprint', 'ContactSyncBlocked', 'Credential', 'DataBackupBlocked', 'DependsOn', 'Description', 'DeviceComplianceRequired', 'DisableAppPinIfDevicePinIsSet', 'DisplayName', 'Ensure', 'ExcludedGroups',
'FingerprintBlocked', 'ManagedBrowserToOpenLinksRequired', 'MaximumPinRetries', 'MinimumPinLength', 'OrganizationalCredentialsRequired', 'PeriodBeforePinReset', 'PeriodOfflineBeforeAccessCheck',
'PeriodOfflineBeforeWipeIsEnforced', 'PeriodOnlineBeforeAccessCheck', 'PinCharacterSet', 'PinRequired', 'PrintBlocked', 'PsDscRunAsCredential', 'SaveAsBlocked', 'SimplePinBlocked', 'TenantId'.
At C:\Users\mbo457\Documents\M365DSC\Intune_Settings_UWV\M365TenantConfig.ps1:105 char:13
+             IsAssigned                              = $False;
+             ~~~~~~~~~~
The member 'IsAssigned' is not valid. Valid members are
'AllowedDataStorageLocations', 'AllowedInboundDataTransferSources', 'AllowedOutboundClipboardSharingLevel', 'AllowedOutboundDataTransferDestinations', 'ApplicationId', 'ApplicationSecret', 'Apps', 'Assignments',
'CertificateThumbprint', 'ContactSyncBlocked', 'Credential', 'DataBackupBlocked', 'DependsOn', 'Description', 'DeviceComplianceRequired', 'DisableAppPinIfDevicePinIsSet', 'DisplayName', 'Ensure', 'ExcludedGroups',
'FingerprintBlocked', 'ManagedBrowserToOpenLinksRequired', 'MaximumPinRetries', 'MinimumPinLength', 'OrganizationalCredentialsRequired', 'PeriodBeforePinReset', 'PeriodOfflineBeforeAccessCheck',
'PeriodOfflineBeforeWipeIsEnforced', 'PeriodOnlineBeforeAccessCheck', 'PinCharacterSet', 'PinRequired', 'PrintBlocked', 'PsDscRunAsCredential', 'SaveAsBlocked', 'SimplePinBlocked', 'TenantId'.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingArgument

Any ideas how to solve these errors?
Thanks,
Michiel</div>

### PR DESCRIPTION
**Pull request by menswearUK**
#### Pull Request (PR) description

This change amends the get-targetresource function to eliminate function Get-M365DSCIntuneAppProtectionPolicyAndroid.
The function is not needed as we already gather all the information required when we call Get-MgDeviceAppManagementAndroidManagedAppProtection.

I've added a function to gather a list of the parameters and any amendments required to allow the export function to work correctly.

Get-MgDeviceAppManagementAndroidManagedAppProtection is using the beta profile.  Whilst this isn't required for this update the function I've removed used the beta profile for gathering data and I'll need it for future updates as there are some values not returned by using v1.0.

It also no longer returns the parameters which cause error #1955.  I've tested the export function and have been able to use the config as exported to create a new policy

#### This Pull Request (PR) fixes the following issues

fixes #1955

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@menswearUK the parameters you are trying to remove are being returned by the function:
image
I believe the fix should be to add those to the .schema.mof file instead of trying to remove them from the .psm1 file

**Comment by menswearUK** [comment]
Hi Nik,
I'd removed them as we had been having some trouble getting the JSON configuration to work with those values in the iOS configuration and didn't want to generate the same problem with the android config -  I think that's all sorted now so I should be able to add them in.

I don't think isAssigned is required as the value is automatically set based on the content of assignments

Can you advise if the other code changes are acceptable?  If so I'll add in those parameters to this branch

**Comment by NikCharlebois** [comment]
All other changes make total sense. Let's add back the values and keep IsAssigned in there as to not cause any breaking changes. Thanks

**Comment by menswearUK** [comment]
Hi Nik,
I've added the parameters in now - they are functioning ok and I've added them to the tests file.  I also found I needed to tweak the  set-target resource function as it was not setting the assignments and excluded groups when amending a policy, only when creating.
I've added IsAssigned but it doesn't appear to do much - the value sets itself based on the assignments and it doesn't matter what you specify in the config (although it doesn't cause any errors either, it just doesn't set the value) - I've had to put a check in the test-targetresource so it doesn't incorrectly detect drift.

**Comment by menswearUK** [comment]
Hi @NikCharlebois ,
I've updated the changelog with the amendments I've made. I also tweaked the tests file so the parameters and return objects only need to be specified in one place.
Is there anything else you need me to change for this update?  I'm still not sure about the isAssigned parameter as I don't really think it's doing anything, I've tested it with a few configurations and it always sets the value based on the value of assignments and ignores the configuration document.  It was never included in the schema.mof for this configuration but it was exporting that value to the config docs in the initial release.  It is present in this update but if you'd prefer I can remove it.

**Comment by menswearUK** [comment]
@NikCharlebois 
I've just realised that if the ...version values are not set they don't export - and because the set method demands a value for every parameter it'll cause a failure for configs where these values are not specified.  So it'll fix one error and create another.  I'll need to change the json construction so it omits null values.
I'd been intending to amend the set-targetresource function anyway but I'd hoped to do things incrementally.  My ultimate intention was to use New-MgDeviceAppMgtAndroidManagedAppProtection, etc instead of the direct calls - would this be acceptable or shall I stick to constructing a json and Invoke-MgGraphRequest?

**Comment by NikCharlebois** [comment]
@menswearUK we should try to call into the cmdlet wherever possible instead of direct calls. Let me know when you've had a chance to refactor the PR and I'll review it. Thanks again for all your hard work!

**Review by NikCharlebois — APPROVED** [review]
LGTM

**Comment by menswearUK** [comment]
Hi @NikCharlebois ,
If this is looking ok I've just added some final amendments - nothing major, just removal of some commented lines and commenting out a write-host I used while testing.  I've also added the updates into the changelog file, which I'd removed previously to clear conflicts.
Hopefully this is good to go now, if there's anything else you want adding or amending please let me know - otherwise I won't amend this branch any further.  Thanks

**Review by NikCharlebois — APPROVED** [review]
LGTM

**Pull request merged**
