### PR TITLE
EXOJournalRule - New Resource

### LINKED ISSUE #543: EXOJournalRule

### LINKED ISSUE #1157: ExchangeOnline: M365DSC does not collect Journal rules
### Description
M365DSC does not collect Journal rules from EXO
Using EXO PowerShell command Get-JournalRule collect the below properties

### Proposed properties

Name                :
Recipient           :
JournalEmailAddress : 
Scope               : 
Enabled             : 

### Special considerations or limitations
N/A

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Initial Release of EXOJournalRule

#### This Pull Request (PR) fixes the following issues
- Fixes #1157
- Fixes #543

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs Can you please do a code review on this new resource? Thanks

**Review by ykuijs — CHANGES_REQUESTED** [review]
Few minor comments

> Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-:-Mf3etl_40Uyz5GID5hr:b-ls1mz8)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @NikCharlebois and @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1, line 226 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3e1PABKjmYKvOWcSl:-Mf3e1PABKjmYKvOWcSm:b-mxwdyq) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1#L226)):*
> ```PowerShell
>     if ($Ensure -eq 'Present' -and $currentValues.Ensure -eq 'Absent')
>     {
>         Write-Verbose -Message "Creating new Journal Rule {$Name}"
> ```

Maybe add the to be configured value, just like we do in the Set section

"to {$enabledValue}"
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1, line 244 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3dtntCtcAqwE8MLxW:-Mf3dtntCtcAqwE8MLxX:bceilk5) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1#L244)):*
> ```PowerShell
>             if ($Enabled -eq $true)
>             {
>                 Write-Host "TADA!!!"
> ```

Probably some testing still in here :smile: 
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1, line 256 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3eC1769cP24y7B2In:-Mf3eC1769cP24y7B2Io:b45sypm) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1#L256)):*
> ```PowerShell
>     elseif ($Ensure -eq 'Absent' -and $currentValues.Ensure -eq 'Present')
>     {
>         Remove-JournalRule -Identity $Name | Out-Null
> ```

Add Verbose message that the rule will be removed
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.schema.mof, line 6 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3eRZf4wkhjbAyXP7Q:-Mf3eRZf4wkhjbAyXP7R:b-zez9vt) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.schema.mof#L6)):*
> ```
> {
>     [Key, Description("Name of the Journal Rule")] String Name;
>     [Key, Description("The JournalEmailAddress parameter specifies a recipient object to which journal reports are sent. You ean use any value that uniquely identifies the recipient.")] String JournalEmailAddress;
> ```

Typo in "You can", ean must be can

**Review by NikCharlebois — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1, line 226 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3e1PABKjmYKvOWcSl:-Mf3wqfWESpqMN96U1-a:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1#L226)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Maybe add the to be configured value, just like we do in the Set section

"to {$enabledValue}"

</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1, line 244 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3dtntCtcAqwE8MLxW:-Mf3wd9v9jg6okz2vS_2:b-cs1i3n) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1#L244)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Probably some testing still in here :smile: 
</blockquote></details>

HAHAHAHAHAH. Good find!
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1, line 256 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3eC1769cP24y7B2In:-Mf3wyCjAeJo_En2ZLMs:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.psm1#L256)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Add Verbose message that the rule will be removed
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.schema.mof, line 6 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-Mf3eRZf4wkhjbAyXP7Q:-Mf3x8sq3f06nkeO9djp:b4gmmhc) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/2498820a78eb921954ccb89af24ca29bf1b86309/Modules/Microsoft365DSC/DSCResources/MSFT_EXOJournalRule/MSFT_EXOJournalRule.schema.mof#L6)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Typo in "You can", ean must be can
</blockquote></details>

Nice this is taking from docs.microsoft.com. I'll send them a PR to fix it up there too. Thanks

**Review by ykuijs — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @ykuijs)

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/1326#-:-Mf7oZCW3TnT0jr5cXGW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
