### PR TITLE
IntuneDeviceConfigurationPolicyiOS

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Initial Release

#### This Pull Request (PR) fixes the following issues
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/956)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
And the award for "Author of the resource with the most properties goes to..."

@ykuijs Can you do me the honors of reviewing this 127 properties resource?

**Review by ykuijs — CHANGES_REQUESTED** [review]
Why did you delete all of the *.Tests.ps1 files?

> Reviewed 4 of 137 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/956#-:-MNgeh562__BLxlN-uqA:bxfoeni)* status: 4 of 137 files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.psm1, line 1222 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/956#-MNgdlR8-jGrpurJ0XIj:-MNgdlR8-jGrpurJ0XIk:bgae9xa) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b8ad96cc17b4782cba5ba6d7fb77fe34f04c76c8/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.psm1#L1222)):*
> ```PowerShell
>         -InboundParameters $PSBoundParameters
> 
>     $currentCategory = Get-TargetResource @PSBoundParameters
> ```

Why did you name this variable currentCategory. Wouldn't make currentPolicy more sense?
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.schema.mof, line 6 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/956#-MNgeIcyEtdhWj_Zrdax:-MNgeIcyEtdhWj_Zrday:bdtnfci) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b8ad96cc17b4782cba5ba6d7fb77fe34f04c76c8/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.schema.mof#L6)):*
> ```
>     [Key, Description("Display name of the device configuration policy for iOS.")] String DisplayName;
>     [Write, Description("Description of the device configuration policy for iOS.")] String Description;
>     [Write, Description("N/A")] Boolean AccountBlockModification;
> ```

Aren't descriptions available for these properties or did you forget to update these fields? Maybe it is an idea to reference documentation to prevent having to copy/paste all descriptions?

**Review by NikCharlebois — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/956)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.psm1, line 1222 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/956#-MNgdlR8-jGrpurJ0XIj:-MNiEonn7z-JESp0ib2c:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b8ad96cc17b4782cba5ba6d7fb77fe34f04c76c8/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.psm1#L1222)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Why did you name this variable currentCategory. Wouldn't make currentPolicy more sense?
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.schema.mof, line 6 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/956#-MNgeIcyEtdhWj_Zrdax:-MNiFZ4c49UgygAQHhdf:b7u0o5x) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/b8ad96cc17b4782cba5ba6d7fb77fe34f04c76c8/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyiOS/MSFT_IntuneDeviceConfigurationPolicyiOS.schema.mof#L6)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Aren't descriptions available for these properties or did you forget to update these fields? Maybe it is an idea to reference documentation to prevent having to copy/paste all descriptions?
</blockquote></details>

Description are not available yet in a consistent manner on docs.microsoft.com

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 137 files at r1, 1 of 133 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/956#-:-MNiHD2a7OP2EMP_QxmZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NikCharlebois)

**Pull request merged**
