### PR TITLE
Add ManagedIdentity support to resource generator

### PR DESCRIPTION
**Pull request by mlhickey**
#### Pull Request (PR) description
Add ManagedIdentity switch support to resource generator.

#### This Pull Request (PR) fixes the following issues
None

### CODE REVIEW

**Comment by andikrueger** [comment]
@mlhickey Just out of curiosity: what kind of code editor or code formatting rules are you using? The formatting looks good. On the other hand, it changes the quoting styles from double quotes to single quotes.

@NikCharlebois Do we have a preferred style for quotes?

**Comment by mlhickey** [comment]
Everything is done in VS Code with PS extension - Allman for style,  standard is to use single quotes for non-evaluated strings.  I’ve noticed it seems to vary across resources.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by andikrueger** [comment]
vscode should respect the settings file within the .vscode folder… it’s interesting, as I did not see a changes of quote styles on my end in the past.

**Comment by mlhickey** [comment]
I agree, purpose behind that folder but...

**Comment by andikrueger** [comment]
Good point. Looks like we need to implement this change within the .vscode settings. This was introduced with V 1.19.1 and targets the PSScriptAnalyzer Rule: https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidusingdoublequotesforconstantstring?view=ps-modules

Prior to implementing this change, we need to consider the impact.

**Comment by mlhickey** [comment]
Q - should we consider offering use of Update- when New- isn't available/relevant for a given noun, e.g. AuthorizationPolicy?

**Comment by andikrueger** [comment]
Authorization Policy is a singleton within the tenant. Therefore there is no New function available. (see: https://learn.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-1.0)

Updating policies would be valid case for M365DSC.  Is it worth the efforts to modify DRG for this case? Are there more objects within graph without a new method?

**Comment by mlhickey** [comment]
Yup, just an example.  The effort is minimal, but if there are only a few unique then maybe it doesn't matter - if it isn't broken then ...

**Comment by andikrueger** [comment]
DRG has a great benefit over all other approaches. It gives us the opportunity to build new and even rebuild existing resources on the fly. As soon as there are changes to the APIS, we can react in a fast way (e.g. like in #2272 / #2280)

I just went through the DRG code. The change would not be that big, as there is already code to change the default noun for the parameters:

https://github.com/microsoft/Microsoft365DSC/blob/b8624c55452713cf6a487513144186cfb9689770/ResourceGenerator/M365DSCResourceGenerator.psm1#L948-L952

and if I see it correctly, this line needs some updating too:

https://github.com/microsoft/Microsoft365DSC/blob/b8624c55452713cf6a487513144186cfb9689770/ResourceGenerator/M365DSCResourceGenerator.psm1#L1223

Which would result in a new parameter :D so that the change can be made.

Would be worth a try.

**Comment by mlhickey** [comment]
Yup.  In my test I set a flag early around 1011:
`$hasNew = (-not [System.String]::IsNullOrEmpty($cmdletCommandDetails))`
then do conditional based on that around 1250 and 2095 (relative based on code addition)

**Review by NikCharlebois — APPROVED** [review]

**Pull request merged**
