### PR TITLE
EXOSafeLinksPolicy: Updated with DeliverMessageAfterScan option

### PR DESCRIPTION
**Pull request by Swampen**
#### Pull Request (PR) description
Update to the EXOSafeLinksPolicy resource to include the DeliverMessageAfterScan option
Doc: https://docs.microsoft.com/en-us/powershell/module/exchange/New-SafeLinksPolicy?view=exchange-ps

#### This Pull Request (PR) fixes the following issues
None

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/947)

### CODE REVIEW

**Review by NikCharlebois — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-:-MNPFeaVAG-J5QHZq7CN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Swampen)

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Minor things

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-:-MNPJpmw9zHcRom8Asaw:b-keg023)* status: all files reviewed, 2 unresolved discussions (waiting on @Swampen)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1, line 108 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-MNPJdu2-w3jC6oOvcJe:-MNPJdu3BXdMNXSDhZlB:b-6l1f1h) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6483cb9b480775688722b827d620ed35bdfda732/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1#L108)):*
> ```PowerShell
>                 AllowClickThrough         = $AtpPolicyForO365.AllowClickThrough
>                 BlockUrls                 = $AtpPolicyForO365.BlockUrls
>                 EnableATPForSPOTeamsODB   = $AtpPolicyForO365.EnableATPForSPOTeamsODB
> ```

Please align all '=' signed for readibility
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1, line 173 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-MNPJ_3a6oHssFNu5ABY:-MNPJ_3b42jOixSuM97F:be2qxix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6483cb9b480775688722b827d620ed35bdfda732/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1#L173)):*
> ```PowerShell
>         [Parameter()]
>         [Boolean]
>         $EnableSafeLinksForO365Clients = $false,
> ```

To be consistent, let's set $true as the default value cross all functions

**Comment by Swampen** [comment]
Not sure what happened here.. I kept working on new resources, so these changes will be included in a different PR. Should I have created a new branch perhaps?

**Comment by Swampen** [comment]
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1, line 173 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-MNPJ_3a6oHssFNu5ABY:-MNPMY_d1yd6BoIslwVG:bzb65db) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6483cb9b480775688722b827d620ed35bdfda732/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1#L173)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

To be consistent, let's set $true as the default value cross all functions
</blockquote></details>

Reverted to PR for DeliverMessageAfterScan

**Comment by Swampen** [comment]
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1, line 108 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-MNPJdu2-w3jC6oOvcJe:-MNPMPdVDdqBqrUukNDI:bzb65db) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6483cb9b480775688722b827d620ed35bdfda732/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1#L108)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Please align all '=' signed for readibility
</blockquote></details>

Reverted to PR for DeliverMessageAfterScan

**Review by Swampen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/947)* status: all files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1, line 108 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-MNPJdu2-w3jC6oOvcJe:-MNPPvQy71p0pOKE6ICw:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6483cb9b480775688722b827d620ed35bdfda732/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1#L108)):*
<details><summary><i>Previously, Swampen (Ole-Martin Heggen) wrote…</i></summary><blockquote>

Reverted to PR for DeliverMessageAfterScan
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1, line 173 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/947#-MNPJ_3a6oHssFNu5ABY:-MNPQ18u0KVA1d92Vdzg:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/6483cb9b480775688722b827d620ed35bdfda732/Modules/Microsoft365DSC/DSCResources/MSFT_EXOAtpPolicyForO365/MSFT_EXOAtpPolicyForO365.psm1#L173)):*
<details><summary><i>Previously, Swampen (Ole-Martin Heggen) wrote…</i></summary><blockquote>

Reverted to PR for DeliverMessageAfterScan
</blockquote></details>

Done.

**Review by NikCharlebois — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Swampen)

**Pull request merged**
