### PR TITLE
Added Export-M365DiagnosticData cmdlet

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description
This PR adds a function to collect diagnostic information (DSC Verbose logs, M365Dsc event log, PowerShell info and OS info) into a Zip package. It has the possibility to anonymize information by replacing server name, domain name and url with generic text.

#### This Pull Request (PR) fixes the following issues

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/899)

### CODE REVIEW

**Review by NikCharlebois — CHANGES_REQUESTED** [review]
Just a naming changing required

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/899#-:-MLx-rqO43TFskOwiEph:byde814)* status: all files reviewed, 2 unresolved discussions (waiting on @ykuijs)

___
*[Modules/Microsoft365DSC/Microsoft365DSC.psd1, line 141 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/899#-MLx-dAS7NUAyVKb7vYR:-MLx-dB590nNFQUTmXX3:bjoy6zf) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/41bcea29747a1aef454c12a8b46d92114d1e1e45/Modules/Microsoft365DSC/Microsoft365DSC.psd1#L141)):*
> ```PowerShell
>         'Compare-M365DSCConfigurations',
>         'Export-M365DSCConfiguration',
>         'Export-M365DiagnosticData',
> ```

Please rename to Export-M365DSCDiagnosticData
___
*[Modules/Microsoft365DSC/Modules/M365DSCLogEngine.psm1, line 139 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/899#-MLx-kkTBW5QYmPvnXC-:-MLx-kkTBW5QYmPvnXC0:bjoy6zf) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/41bcea29747a1aef454c12a8b46d92114d1e1e45/Modules/Microsoft365DSC/Modules/M365DSCLogEngine.psm1#L139)):*
> ```PowerShell
> }
> 
> function Export-M365DiagnosticData
> ```

Please rename to Export-M365DSCDiagnosticData

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/899)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/Microsoft365DSC.psd1, line 141 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/899#-MLx-dAS7NUAyVKb7vYR:-MLx0wN60VA6Ia_WWX-5:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/41bcea29747a1aef454c12a8b46d92114d1e1e45/Modules/Microsoft365DSC/Microsoft365DSC.psd1#L141)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Please rename to Export-M365DSCDiagnosticData
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/Modules/M365DSCLogEngine.psm1, line 139 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/899#-MLx-kkTBW5QYmPvnXC-:-MLx0wqBD_2V6Fs0rH-i:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/41bcea29747a1aef454c12a8b46d92114d1e1e45/Modules/Microsoft365DSC/Modules/M365DSCLogEngine.psm1#L139)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Please rename to Export-M365DSCDiagnosticData
</blockquote></details>

Done.

**Review by NikCharlebois — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/899#-:-MLx3GkeAbxjDpbG9oEO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Review by NikCharlebois — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/899)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Pull request merged**
